### DISCUSSION TITLE
如何添加socks5代理节点

### DISCUSSION THREAD

**Discussion by woqq111** [clash-verge-rev/clash-verge-rev#1638] [Q&A] [answered]
我不太清楚clash verge如何添加socks5节点，我是win11，比如我添加了如下节点：

```
proxies:
- name: dante
  type: socks5
  server: xxx
  port: 12121
  username: xxx
  password: xxx
```

我在全局模式下使用这个节点，测试连通性为ERROR，但是可以上网，但是我无法连接内网

我使用`curl -v -x socks5://username:password@ip:port url`在mobaxterm那个本地的终端运行，也是可以收到内网网页内容的，说明我这个代理服务是没有问题的，应该是clash verge没配置好

请问有人能指点我一下怎么配置吗
