### DISCUSSION TITLE
Clash.Meta会处理IPv6的DNS请求么？

### DISCUSSION THREAD

**Discussion by atbug** [clash-verge-rev/clash-verge-rev#1813] [Q&A]
我的全局扩展配置里有

```yaml
dns:
  use-system-hosts: false
  nameserver:
    - https://chromium.dns.nextdns.io
    - https://chrome.cloudflare-dns.com/dns-query
  fallback:
    - https://chromium.dns.nextdns.io
    - https://chrome.cloudflare-dns.com/dns-query
```

但是我用wireshark能探测到一大批指向ISP的IPv6的DNS请求，我用的是TUN模式。
