### DISCUSSION TITLE
我需要多个浏览器多开DMM账号，求问怎么配置实现。

### DISCUSSION THREAD

**Discussion by skbamboo** [clash-verge-rev/clash-verge-rev#1883] [Q&A]
总所周知DMM是禁止同IP多开账号的。
所以我想借由我已购买多重节点来完成。
已知条件
1.一个拥有多个日本梯子的订阅链接（已拥有
2.多个浏览器，且不同的浏览器应用不用的端口（已拥有）

求问
clsah verge 怎么设置一个订阅链接同时应用两个节点+且分配不同的端口。

**Comment by wonfen** [comment]
无法做到。

**Reply by sagasm** [reply]
1. 试试listeners入站, 开不同的监听协议和端口.
2. 或者不同的浏览器使用不同的路径, 试试PROCESS-PATH规则,

**Reply by skbamboo** [reply]
我，纯小白。求问2的详细实行方案

**Reply by sagasm** [reply]
我觉得还是1方便点, 你详细说一下不同的浏览器应用不用的端口是如何设定的, 我看看能不能做出规则来

**Reply by skbamboo** [reply]
几个浏览器都是用SwitchyOmega 插件手动设置端口的。
然后本地多开Clash Verge和Trojan-Qt5。一个软件输出一个端口。

**Reply by sagasm** [reply]
一个Clash Verge就可以管理所有出站为啥要多开

**Reply by skbamboo** [reply]
> 就是不会才多开qaq

**Reply by sagasm** [reply]
在全局扩展配置中添加:
```
listeners:
- name: s1
  type: socks
  port: 1081
  listen: 0.0.0.0
  proxy:proxy1
- name: s2
  type: socks
  port: 1082
  listen: 0.0.0.0
  proxy: proxy2
```
  
就可以添加两个socks5代理, 出站代理名称分别是proxy1, proxy2
