### DISCUSSION TITLE
有什么办法简单的添加一个代理吗

### DISCUSSION THREAD

**Discussion by ayasechan** [clash-verge-rev/clash-verge-rev#2100] [Q&A] [answered]
一个 socks5 代理 一定要自己从头写配置吗

**Comment by Dragon1573** [comment, marked as answer]
现在的 `v2.3.2+autobuild.0713.2c9aa4b` 里，可以针对单个订阅右键选择「编辑节点」，把 `socks5://` 形式的 URL 贴进去即可。

按照格式手写也是可以的。

```yaml
append:
  - type: 'socks5'
    name: '🇯🇵 日本 (下北泽)-01 1.0x'
    server: '11.45.1.4'
    port: 1919
    username: 'homo810'
    password: '1145141919810'
    udp: true
    ip-version: 'ipv6'
```
