### DISCUSSION TITLE
clash配置文件中通过 proxy-providers 导入的 hysteria2 节点默认被过滤

### DISCUSSION THREAD

**Discussion by TomZhang1019** [clash-verge-rev/clash-verge-rev#2204] [Q&A]
本地配置文件中, 使用`proxy-providers`代理集写入机场类型配置, 然后在`proxy-groups`代理组中使用 `use`来使用时, 为什么会默认过滤掉hysteria2协议的节点, 即使这些节点是可用的, 同时也没有在配置文件中设置过滤
通过`proxies`单独配置节点就没事

```yaml
proxy-providers:
  自建:
    type: http
    url: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" 
    interval: 86400
    path: ./provider_zijian.yaml
    health-check:
      enable: true
      interval: 1800
      url: http://www.gstatic.com/generate_204
```

```yaml
proxy-groups:
  - { name: 节点选择, type: select, proxies: [香港HGC, DIRECT], use: [自建] }
```

![屏幕截图 2024-11-29 191401](https://github.com/user-attachments/assets/8f141b3f-7d5e-420e-bb68-9ea156414d20)
