### DISCUSSION TITLE
`dns.fake-ip-filter`如何使用以添加整个域名后缀？

### DISCUSSION THREAD

**Discussion by Silvigarabis** [clash-verge-rev/clash-verge-rev#2363] [Q&A] [answered]
我现在需要在`dns.enhanced-mode`中使用`fake-ip`模式，但由于一些原因，我要将部分域名排除在外，使其能返回真实结果。
不过，我想偷懒，不愿意将域名一个个添加到`dns.fake-ip-filter`列表中，所以我尝试了：

```yaml
dns:
  fake-ip-filter:
    - *.domain.ltd
```

还有这样：
```yaml
dns:
  fake-ip-filter:
    - domain:domain.ltd
```

以及这样：
```yaml
dns:
  fake-ip-filter:
    - DOMAIN-SUFFIX,domain.ltd
```

但上边这些方法都不起作用。

是否有一种方法能将整个域名后缀添加到这个列表中呢？

**Comment by HozumiMoa** [comment, marked as answer]
通配符*要加引号
```yaml
dns:
  fake-ip-filter:
    - '*.domain.ltd'
```
