### DISCUSSION TITLE
请问扩展配置里可以实现覆盖代理组的功能吗？

### DISCUSSION THREAD

**Discussion by iaw-dlay** [clash-verge-rev/clash-verge-rev#2372] [Q&A] [answered]
我想要单独编辑代理组内的节点，但是现有的订阅右键菜单里的“编辑代理组”功能仅能编辑整个的代理组，而不能单独修改代理组内的节点；所以打算覆盖掉代理组再单独进行编辑。
软件版本为2.0.2

我看官网上的“[使用教程>扩展配置/脚本](https://www.clashverge.dev/guide/extend.html)”里有如下描述
>- v1.7.x 版本的 Merge配置 改名为 扩展配置 ，且prepend/append功能移动至订阅右键菜单中的可视化编辑器中实现（例如：prepend->rules移动至订阅右键菜单的 编辑规则 中的 prepend）。扩展配置仅用于配置项覆写/合并。

然后在[历史归档>Merge配置](https://www.clashverge.dev/guide/merge.html)里写着：
> - 需要覆盖的配置项和原配置文件中的书写方式一样。

但是我尝试了下，直接把原来的proxy-groups复制到扩展配置里，会直接报错`failed to put configs with status "400”`，然后又尝试自己写了两个proxy-groups进行覆盖也是会报错400
```
proxy-groups:
  - name: tast01
    type: select
    proxies:
      - 🇭🇰 Hong Kong 01
      - 🇭🇰 Hong Kong 02
      - 🇭🇰 Hong Kong 03
      - 🇭🇰 Hong Kong 04
      - 🇭🇰 Hong Kong 05
      - 🇭🇰 Hong Kong 06
      - 🇭🇰 Hong Kong 07
      - 🇭🇰 Hong Kong 08
      - 🇭🇰 Hong Kong 09
      - DIRECT
  - name: tast02
    type: select
    proxies:
      - 🇭🇰 Hong Kong 01
      - 🇭🇰 Hong Kong 02
      - 🇭🇰 Hong Kong 03
      - 🇭🇰 Hong Kong 04
      - 🇭🇰 Hong Kong 05
      - 🇭🇰 Hong Kong 06
      - 🇭🇰 Hong Kong 07
      - 🇭🇰 Hong Kong 08
      - 🇭🇰 Hong Kong 09
```

所以我想问一下扩展配置里可以实现覆盖代理组的功能吗，以及具体要如何实现？
