### DISCUSSION TITLE
求助各位大佬 如何配置dns可以防止泄露

### DISCUSSION THREAD

**Discussion by lpxks** [clash-verge-rev/clash-verge-rev#2526] [Q&A]
通过dns泄露检测网站 似乎存在泄露风险 求各位大佬指教。我一直使用的都是默认配置。
![image](https://github.com/user-attachments/assets/a2dd3835-546f-493b-a889-ed28e3c27680)

**Comment by SyberRabbit** [comment]
试试这个？
```
dns:
  enable: true
  ipv6: false
  default-nameserver:
    - 127.0.0.1
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "+.exmaple.com"
  use-hosts: true
  nameserver:
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
  nameserver-policy:
    geosite:cn:
      - 127.0.0.1
      - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - https://1.1.1.1/dns-query
    - https://223.5.5.5/dns-query
  use-system-hosts: false
```
