### DISCUSSION TITLE
为什么在全局脚本里指定了enhanced-mode为fake-ip但是生成的配置里enhanced-mode是redir-host？

### DISCUSSION THREAD

**Discussion by xovow** [clash-verge-rev/clash-verge-rev#2926] [Q&A]
这是全局扩展脚本中的dns配置
```
const dnsConfig = {
  'enable': true,
  'prefer-h3': true,
  'ipv6': true,
  'enhanced-mode': 'fake-ip',
  'fake-ip-range': '198.18.0.1/16',
  'fake-ip-filter': [
    // 本地主机 / 设备
    "+.lan",
    "+.local",
    // Windows 网络出现小地球图标
    "+.msftconnecttest.com",
    "+.msftncsi.com",
    // QQ 快速登录检测失败
    "localhost.ptlogin2.qq.com",
    "localhost.sec.qq.com",
    // 微信快速登录检测失败
    "localhost.work.weixin.qq.com"
  ],
  'default-nameserver': ['223.5.5.5', '119.29.29.29'],
  'nameserver': [
    'https://dns.alidns.com/dns-query', 'https://doh.pub/dns-query'
  ],
  'nameserver-policy': {
    'geosite:google,youtube,telegram,gfw,geolocation-!cn': [
      'https://dns.cloudflare.com/dns-query', 'https://dns.google/dns-query'
    ],
  }
};
```
这是当前配置中的dns情况
```
dns:
  enable: true
  prefer-h3: true
  ipv6: true
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  nameserver-policy:
    geosite:google,youtube,telegram,gfw,geolocation-!cn:
    - https://dns.cloudflare.com/dns-query
    - https://dns.google/dns-query
    ```
