### DISCUSSION TITLE
分享一下简单的添加自定义规则、自定义 hosts 的方法

### DISCUSSION THREAD

**Discussion by nibazshab** [clash-verge-rev/clash-verge-rev#3126] [Show and tell]
有时候希望某个域名和IP不要走代理？那就：订阅-全局扩展脚本-右键-编辑文件

写入如下内容
```js
// Define main function (script entry)

// 修改这里
const domainList = [
  "bing.com",
];

// 以及这里
const ipList = [
  "150.158.163.31",
];

const newRules = [
  ...domainList.map(domain => `DOMAIN-SUFFIX,${domain},DIRECT,no-resolve`),
  ...ipList.map(ip => `IP-CIDR,${ip}/32,DIRECT,no-resolve`)
];

function main(config, profileName) {
  config.rules = [
    ...newRules,
    ...config.rules
  ];

  return config;
}
```

遇到了即使开代理也打不开的页面，必须要改 hosts？那就：订阅-全局扩展覆写配置-右键-编辑文件

```yaml
# Profile Enhancement Merge Template for Clash Verge

profile:
  store-selected: true

dns:
  use-system-hosts: false

# 修改这里
hosts:
  www.google.com: 8.8.8.8
  res.google.com: 8.8.8.8,1.1.1.1,2.2.2.2
  api.googole.com: 8.8.8.8
```
