### DISCUSSION TITLE
我发现最好的防dns泄露是系统代理加全局

### DISCUSSION THREAD

**Discussion by 13098724567** [clash-verge-rev/clash-verge-rev#3373] [General]
貌似很多Clash系客户端用tun都有dns泄露的问题，甚至开全局都没用但是换成系统代理就没问题了

**Comment by 13098724567** [comment]
怪了，我刚才测试的时候ClashVerge全局tun是会泄露dns的就算开了严格路由也是这样，怎么现在又好了

**Reply by 13098724567** [reply]
> 怪了，我刚才测试的时候ClashVerge全局tun是会泄露dns的就算开了严格路由也是这样，怎么现在又好了

也许是我重装了软件导致的？之前一直都是覆盖升级

**Comment by 13098724567** [comment]
不过隔壁flclash是确确实实有这问题

**Comment by xiaoziguys** [comment]
没用的，最好的防止泄漏就是做好dns的分流配置然后使用doh。不过就算不泄漏你udp一样解析不了。
```
  # 在这里指定代理的规则，和规则走国外dns，并且国外的dns也要有对应的ip规则。
  nameserver-policy:
    "rule-set:copilot":
       - https://101.101.101.101/dns-query # quad 101 dns
       - https://8.8.8.8/dns-query  # google DoH
    "geosite:geolocation-!cn":
      - https://101.101.101.101/dns-query # quad 101 dns
       - https://8.8.8.8/dns-query  # google DoH
  # nameserver和fallback都配置国内的
  nameserver:
    - https://223.6.6.6/dns-query  # 阿里DoH
  fallback:
    - 119.29.29.29
  
  default-nameserver: [119.29.29.29, 223.6.6.6]
```
