### DISCUSSION TITLE
tun 模式，localhost 无法解析成 127.0.0.1

### DISCUSSION THREAD

**Discussion by tudan110** [clash-verge-rev/clash-verge-rev#3575] [Q&A] [answered]
使用 tun 模式，发现 localhost 不能被正确解析成 127.0.0.1

![image](https://github.com/user-attachments/assets/028c8897-b455-4fa7-b110-e7c209b76a78)

参考网上看到资料编辑 “全局扩展覆写配置” 如下，依旧不能正确解析 127，求大佬们指导

```yaml
# Profile Enhancement Merge Template for Clash Verge

profile:
  store-selected: true

dns:
  enable: true 
  ipv6: true # true/false 是否启用 ipv6 支持
  use-hosts: true
  use-system-hosts: true
  # 从 v0.18.8 版本开始，TUN 模式建议使用 fake-ip 模式，redir-host 将无法进行远端 DNS 解析
  enhanced-mode: fake-ip # redir-host/fake-ip
  # use-hosts: true # 查询 hosts 并返回 IP 记录
  default-nameserver: # 用于 DoH/DoT 的 Bootstrap Server
    - 223.5.5.5  # 阿里公共 DNS
    - 223.6.6.6  # 阿里公共 DNS
    - 119.29.29.29 # DNSPOD 公共 DNS
  fake-ip-range: 198.18.0.1/16 # Fake IP 地址池 (CIDR 形式)
  fake-ip-filter: # 微软系 APP 无法登陆使用等问题，通过添加 fake-ip-filter 解决
    # === Local ===
    - "localhost"
    - "127.0.0.1"
    - "::1"
    - "*.lan"
    - "*.local"
    # === Microsoft Windows Serivice ===
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
  nameserver: # GeoIP 为 CN 时使用的 DNS NameServer（使用DoH/DoT）
    - https://doh.pub/dns-query   # DNSPod DoH
    - https://dns.alidns.com/dns-query  # 阿里 DoH
    #- https://[2400:3200::1]/dns-query  # 阿里 DoH
    #- https://[2400:3200:baba::1]/dns-query # 阿里 DoH
  fallback: # GeoIP 不是 CN 时使用的 DNS NameServer（使用DoH/DoT）
    #- https://doh.dns.sb/dns-query    # DNS.SB DoH
    - https://dns.google/dns-query    # Google DoH
    - https://1.1.1.1/dns-query   # Cloudflare DoH
    #- https://1.0.0.1/dns-query   # Cloudflare DoH
  fallback-filter:
    geoip: true # 启用 GeoIP
    ip-cidr:
      - 240.0.0.0/4
      - 127.0.0.1/8
      - 0.0.0.0/32
    domain:
      - +.google.com
      - +.facebook.com
      - +.twitter.com
      - +.youtube.com
      - +.xn--ngstr-lra8j.com
      - +.google.cn
      - +.googleapis.cn
      - +.googleapis.com
      - +.gvt1.com
  hosts:
    localhost: 127.0.0.1
    127.0.0.1: 127.0.0.1
    ::1: ::1

# interface-name: Ethernet  # 出口网卡名称（已注释），建议使用自动检测出口网卡模式👇
tun:  # Tun 配置
  enable: true  # 启用 Tun 模式
  # 使用 system statck 需要 Clash Premium 2021.05.08 及更高版本
  stack: system  # gvisor/system 使用 system stack 请按照本文后面防火墙放行程序
  dns-hijack:   
    - 198.18.0.2:53  # 本地劫持 DNS 地址，无需修改
  auto-route: true
  auto-detect-interface: true  # 自动检测出口网卡
  redirect-to-tun:
    - 127.0.0.0/8
```
