### ISSUE TITLE
[BUG] clash-verge-rev 会自动定时覆盖系统的DNS为223.5.5.5

### ISSUE THREAD

**Issue by Alexios-cd** [clash-verge-rev/clash-verge-rev#1023]
### 问题描述 / Describe the bug

clash-verge-rev 会自动定时覆盖系统的DNS为223.5.5.5
手动修改之为1.1.1.1 或者114.114.114.114之后只要开着clash-verge-rev 软件，会被自动覆盖为 223.5.5.5
某些页面在使用223.5.5.5之后会打不开。

希望可以不覆盖系统的dns或者可以在软件有个位置自定义dns

### 复现步骤 / To Reproduce

clash-verge-rev 开一段时间就会DNS就会自动覆盖为 223.5.5.5

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.4.1 (23E224)

### 日志 / Log

暂无

**Comment by wzsjackson** [comment]
我也碰到了，有什么解决办法吗

**Comment by lhb1998** [comment]
对我来说，覆盖DNS的触发条件为“更新订阅”

**Comment by wzsjackson** [comment]
> 对我来说，覆盖DNS的触发条件为“更新订阅”

切换节点也会

**Comment by xishang0128** [comment]
这是预期行为,劫持dns的条件为必须是公网,所以verge会修改一次dns,以确保劫持

**Comment by dotSpecs** [comment]
> 这是预期行为,劫持dns的条件为必须是公网,所以verge会修改一次dns,以确保劫持
> 
> 劫持后dns请求都由内核接管,修改配置中的dns即可

麻烦问下“修改配置中的dns”是指怎么修改呀？偶尔就会遇到这个 timeout 的问题

```
[TCP] dial DIRECT (match DomainKeyword/-cn) 127.0.0.1:55529 --> xxx.com:80 error: connect failed: dial tcp x.x.x.x:80: i/o timeout
```

**Comment by zhqqqy** [comment]
> > 这是预期行为,劫持dns的条件为必须是公网,所以verge会修改一次dns,以确保劫持
> > 劫持后dns请求都由内核接管,修改配置中的dns即可
> 
> 麻烦问下“修改配置中的dns”是指怎么修改呀？偶尔就会遇到这个 timeout 的问题
> 
> ```
> [TCP] dial DIRECT (match DomainKeyword/-cn) 127.0.0.1:55529 --> xxx.com:80 error: connect failed: dial tcp x.x.x.x:80: i/o timeout
> ```
他的意思是修改你的代理配置里面的dns，在最前面加上你要的dns,就是verge目录下的profiles 里面的文件。然后加上dns 配置
```yaml
dns:
    enable: true
    ipv6: false
    default-nameserver: ["这里是你要的dns",223.5.5.5, 119.29.29.29]
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
```
但是这应改有个问题就是只要设置自动更新配置，又会改回去
