### ISSUE TITLE
[BUG] 使用 Clash Meta 内核开启tun模式出现 connect error: dns resolve failed: context deadline exceeded

### ISSUE THREAD

**Issue by DeadAt17** [clash-verge-rev/clash-verge-rev#104]
使用 Clash Meta 内核开启tun模式出现 connect error: dns resolve failed: context deadline exceeded，之前版本使用 Clash Premium 内核就没有这个问题。
![Snipaste_2023-12-08_17-13-15](https://github.com/clash-verge-rev/clash-verge-rev/assets/126842426/77a1937b-e9ce-4921-8ad4-53cff0dd4c91)

**Comment by wonfen** [comment]
感觉像你的机场配置文件的问题。

**Comment by DeadAt17** [comment]
> 感觉像你的机场配置文件的问题。

emmm... 这是我的配置文件

`mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: Rule
log-level: silent
external-controller: 127.0.0.1:9090

#DNS设置
dns:
  enable: true
  listen: 0.0.0.0:53
  #DNS服务器
  default-nameserver:
    - 8.8.8.8
    - 8.8.4.4
    - 114.114.114.114
  #DoH服务器
  nameserver:
    - https://doh.360.cn/dns-query
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  #列表中的域名将不会被解析为fake ip，这些域名相关的解析请求将会返回它们真实的IP地址
  fake-ip-filter:
    - '*.lan'
    - xsus.buzz

#本地代理
proxies:

#远程订阅(代理集合)
proxy-providers:

  MyProxy: &MyProxy #建立锚点
     #多机场用户请使用Sub-Store生成自己的订阅地址并替换以下url地址
    url: http://110.40.198.132:15051/sub?target=clash&url=xxxxx
    path: ./proxy/MyProxy.yaml
    type: http
    interval: 86400
    health-check:
      enable: true
      interval: 3600
      url: http://cp.cloudflare.com/generate_204
      
  #美国节点
  MyProxy-US:
    <<: *MyProxy #引用锚点内容
    path: ./proxy/MyProxy-US.yaml
    filter: "美|美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|California|芝加哥|🇺🇸|United States|US"
  
  #香港节点
  MyProxy-HK:
    <<: *MyProxy #引用锚点内容
    path: ./proxy/MyProxy-HK.yaml
    filter: "香港|🇭🇰|HK|中港|沪港|Hong"
  
  #日本节点
  MyProxy-JP:
    <<: *MyProxy #引用锚点内容
    path: ./proxy/MyProxy-JP.yaml
    filter: "日本|东京|Tokyo|大阪|埼玉|🇯🇵|JP|Japan"

    #日本节点
  MyProxy-KR:
    <<: *MyProxy #引用锚点内容
    path: ./proxy/MyProxy-KR.yaml
    filter: "韩国|首尔|Seoul|🇰🇷|KR|Korea"
  
  #台湾节点
  MyProxy-TW:
    <<: *MyProxy #引用锚点内容
    path: ./proxy/MyProxy-TW.yaml
    filter: "台|台湾|Taiwan|TW"
  
  #新加坡节点
  MyProxy-SG:
    <<: *MyProxy #引用锚点内容
    path: ./proxy/MyProxy-SG.yaml
    filter: "狮城|新加坡|Singapore|🇸🇬|SG"
  
#策略组
proxy-groups:

- name: Proxy
  type: url-test
  url: 'http://www.YouTube.com/generate_204'
  interval: 600
  tolerance: 200
  lazy: true
  use:
    - MyProxy
  icon: https://raw.githubusercontent.com/fanmingming/Rules/main/Filter/Proxy.png

- name: Bilibili
  type: select
  proxies:
  - HK
  - TW
  - DIRECT
  icon: https://raw.githubusercontent.com/fanmingming/Rules/main/Filter/Bilibili.png

- name: OpenAI
  type: select
  proxies:
  - US
  - SG
  - TW
  #icon: https://raw.githubusercontent.com/fanmingming/Rules/main/Filter/Google.png

- name: TikTok
  type: select
  proxies:
  - US
  - TW
  - JP
  - SG
  - KR
  icon: https://raw.githubusercontent.com/fanmingming/Rules/main/Filter/Bilibili.png

- name: US
  type: select
  icon: https://raw.githubusercontent.com/fanmingming/Rules/main/Country/US.png
  use:
    - MyProxy-US

- name: HK
  type: url-test
  icon: https://raw.githubusercontent.com/fanmingming/Rules/main/Country/HK02.png
  use:
    - MyProxy-HK

- name: JP
  type: url-test
  icon: https://raw.githubusercontent.com/fanmingming/Rules/main/Country/JP.png
  use:
    - MyProxy-JP

- name: KR
  type: url-test
  icon: https://raw.githubusercontent.com/fanmingming/Rules/main/Country/KR.png
  use:
    - MyProxy-KR

- name: TW
  type: url-test
  icon: https://raw.githubusercontent.com/fanmingming/Rules/main/Country/TW02.png
  use:
    - MyProxy-TW

- name: SG
  type: url-test
  icon: https://raw.githubusercontent.com/fanmingming/Rules/main/Country/SG.png
  use:
    - MyProxy-SG

#远程规则集合声明
rule-providers:

  Bilibili-rules:
    type: http 
    behavior: classical
    interval: 86400
    name: Bilibili
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/BiliBili/BiliBili.yaml
    path: ./rules/BiliBili.yaml

  OpenAI-rules:
    type: http 
    behavior: classical
    interval: 86400
    name: OpenAI
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml
    path: ./rules/OpenAI.yaml
  
  Bing-rules:
    type: http 
    behavior: classical
    interval: 86400
    name: Bing
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.yaml
    path: ./rules/Bing.yaml
  
  TikTok-rules:
    type: http 
    behavior: classical
    interval: 86400
    name: TikTok
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.yaml
    path: ./rules/TikTok.yaml
    
  Google-rules:
    type: http 
    behavior: classical
    interval: 86400
    name: Google
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Google/Google.yaml
    path: ./rules/Google.yaml

  Spotify-rules:
    type: http 
    behavior: classical
    interval: 86400
    name: Spotify
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Spotify/Spotify.yaml
    path: ./rules/Spotify.yaml

  reject:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt
    path: ./rules/reject.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt
    path: ./rules/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt
    path: ./rules/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt
    path: ./rules/private.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt
    path: ./rules/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt
    path: ./rules/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt
    path: ./rules/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt
    path: ./rules/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt
    path: ./rules/applications.yaml
    interval: 86400

  teams:
    type: http
    behavior: classical
    path: "./rules/Teams.yaml"
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Teams/Teams.yaml
    interval: 86400

  github:
      type: http
      behavior: classical
      path: "./rules/github.yaml"
      url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml
      interval: 86400
  
  gfw:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt
    path: ./rules/gfw.yaml
    interval: 86400

  Tencent:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Tencent/Tencent.yaml
    path: ./rules/Tencent.yaml
    interval: 86400
#分流规则引用
rules:
# - DOMAIN,sso.pccw.com,DIRECT
# - DOMAIN-SUFFIX,.LoginEJS.,DIRECT
# - DOMAIN-SUFFIX,.wsoccp07.,DIRECT
# - DOMAIN-SUFFIX,＋.hkcsl.,DIRECT
# - DOMAIN-SUFFIX,＋.hkt.*,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- RULE-SET,Bilibili-rules,Bilibili
- RULE-SET,OpenAI-rules,OpenAI
- RULE-SET,Bing-rules,Proxy
- RULE-SET,Google-rules,Proxy
- RULE-SET,Spotify-rules,Proxy
- RULE-SET,TikTok-rules,TikTok
- RULE-SET,applications,DIRECT
- RULE-SET,private,DIRECT
- RULE-SET,reject,REJECT
- RULE-SET,tld-not-cn,Proxy
- RULE-SET,github,Proxy
- RULE-SET,proxy,Proxy
#- RULE-SET,gfw,Proxy
- RULE-SET,telegramcidr,Proxy
- RULE-SET,teams,DIRECT
- RULE-SET,Tencent,DIRECT
- GEOIP,CN,DIRECT
- MATCH,DIRECT`

**Comment by LevineWoo** [comment]
建议取消default-nameserver，直接使用转成ip的doh3写进nameserver中。
试试这个？
  nameserver:
    - https://223.5.5.5/dns-query#h3=true

**Comment by Aut0matas** [comment]
> 建议取消default-nameserver，直接使用转成ip的doh3写进nameserver中。 试试这个？ nameserver: - [223.5.5.5/dns-query#h3=true](https://223.5.5.5/dns-query#h3=true)

clash-verge没有控制该字段的gui,手动更改又会被更新订阅覆盖，请问有什么好办法么

**Comment by DeadAt17** [comment]
> 建议取消default-nameserver，直接使用转成ip的doh3写进nameserver中。 试试这个？ nameserver: - https://223.5.5.5/dns-
改了之后还是存在这个问题
query#h3=true
![微信图片_20231211142806](https://github.com/clash-verge-rev/clash-verge-rev/assets/126842426/da1b0a2b-98b5-49c2-9a0a-3b2149496bbe)

```
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
dns:
    enable: true
    ipv6: false
    #default-nameserver: [223.5.5.5, 119.29.29.29]
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    #nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    nameserver: ['https://223.5.5.5/dns-query#h3=true']
    fallback: ['208.67.220.222:5353', 'tls://1.0.0.1:853', 'https://cloudflare-dns.com/dns-query', 'https://dns.google/dns-query']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
```

**Comment by DeadAt17** [comment]
> 建议取消default-nameserver，直接使用转成ip的doh3写进nameserver中。 试试这个？ nameserver: - https://223.5.5.5/dns-query#h3=true


改了之后还是存在这个问题
query#h3=true
![微信图片_20231211142806](https://github.com/clash-verge-rev/clash-verge-rev/assets/126842426/da1b0a2b-98b5-49c2-9a0a-3b2149496bbe)

```
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
dns:
    enable: true
    ipv6: false
    #default-nameserver: [223.5.5.5, 119.29.29.29]
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    #nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    nameserver: ['https://223.5.5.5/dns-query#h3=true']
    fallback: ['208.67.220.222:5353', 'tls://1.0.0.1:853', 'https://cloudflare-dns.com/dns-query', 'https://dns.google/dns-query']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
```

**Comment by Binly42** [comment]
我这里好像是今天才出现这个症状的

env:
- debian bookworm 12.2
- 1.3.8 appimage 手动解包执行

我一开始倒是完全没见 `context deadline exceeded`的日志, 
反而是换用 Clash Premium 内核 之后才看到的:
```log
12-16 17:42:01WARN
[TCP] dial failed error=all DNS requests failed, first error: Post "https://dns.cloudflare.com/dns-query": context deadline exceeded proxy=🐟 漏网之鱼 lAddr=198.18.0.1:33340 rAddr=bitbucket.org:22 rule=Match rulePayload=
12-16 17:42:06WARN
[TCP] dial failed error=all DNS requests failed, first error: Post "https://doh.mullvad.net/dns-query": context deadline exceeded proxy=🐟 漏网之鱼 lAddr=198.18.0.1:32804 rAddr=packages.debian.org:443 rule=Match rulePayload=
```

此时的 runtime config:
```yaml
mode: global
mixed-port: 7890
allow-lan: true
log-level: info
ipv6: true
secret: ''
external-controller: 127.0.0.1:9090
dns:
  enabled: true
  ipv6: true
  listen: 127.0.0.1:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver-policy:
    '*.google.com': 8.8.8.8
    '*.tw': 1.1.1.1
    testflight.apple.com: 8.8.8.8
    '*.tmall.com': 223.5.5.5
    '*.taobao.com': 223.5.5.5
    '*.alicdn.com': 223.5.5.5
    '*.aliyun.com': 223.5.5.5
    '*.alipay*.com': 223.5.5.5
    '*.alibaba*.com': 223.5.5.5
    '*.alimama*.com': 223.5.5.5
    '*.qq.com': 114.114.114.114
    '*.tencent.com': 114.114.114.114
    '*.weixin.com': 114.114.114.114
    '*.qpic.cn': 114.114.114.114
    '*.jd.com': 114.114.114.114
    '*.bilibili.com': 114.114.114.114
    hdslb.com: 114.114.114.114
    '*.163.com': 119.29.29.29
    '*.126.com': 119.29.29.29
    '*.126.net': 114.114.114.114
    '*.127.net': 114.114.114.114
    '*.netease.com': 114.114.114.114
    '*.10010.com': 114.114.114.114
    '*.unicompayment.com': 114.114.114.114
    '*.ximalaya.com': 114.114.114.114
    '*.baidu.com': 114.114.114.114
    '*.bdstatic.com': 114.114.114.114
  nameserver:
  - https://dns.alidns.com/dns-query
  fallback:
  - https://dns.cloudflare.com/dns-query
  - https://doh.mullvad.net/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
  enable: true
tun:
  inet6-address: null
  enable: true
  stack: gvisor
  dns-hijack:
  - any:53
  auto-route: true
  auto-detect-interface: true
hosts:
  mtalk.google.com: 108.177.125.188
  raw.githubusercontent.com: 151.101.76.133
```
其实这里也有点小bug, 我已经切成了 direct mode 居然还是显示 global ...

顺带一提, global proxy 是一切正常的, 只有直连才有问题


---

实测
改回 clash.meta 内核 之后, 换用下面这套配置的话就也正常:
```yaml
mode: direct
mixed-port: 7890
allow-lan: true
log-level: info
ipv6: true
secret: ''
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://doh.dns.sb/dns-query
  - https://dns.cloudflare.com/dns-query
  - https://dns.twnic.tw/dns-query
  - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
tun:
  enable: true
  stack: gvisor
  dns-hijack:
  - any:53
  auto-route: true
  auto-detect-interface: true
bind-address: '*'
```

**Comment by wonfen** [comment]
现在还有问题吗？

**Comment by how1ewu** [comment]
很奇怪，出现了大量的dns解析错误，特别是直连和国内节点，境外节点倒是没什么问题。日志一般为：error: dns resolve failed: lookupXXX: i/o timeout，例如：
```yaml
 [TCP] dial 🗺️ 全球直连 (match DomainSuffix/qq.com) 127.0.0.1:59854(SogouInput) --> ios.rqd.qq.com:443 error: dns resolve failed: lookup ios.rqd.qq.com: i/o timeout
```
我的配置文件如下：
```yaml
port: 7890
socks-port: 7891
mixed-port: 7892
redir-port: 7893
tproxy-port: 7894
allow-lan: false
bind-address: "*"
ipv6: true
external-controller: 127.0.0.1:9090
mode: rule
log-level: info
dns:
  enabled: true
  ipv6: true
  default-nameserver:
    - 223.5.5.5
    - 8.8.8.8
    - 119.29.29.29
    - 180.184.1.1
  nameserver:
    - 121.251.251.250
    - 223.5.5.5
    - 119.29.29.29
    - 180.184.1.1
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.8.8
    - https://1.1.1.1/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite: 
      - gfw
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"
      - "+.githubusercontent.com"
      - "+.googlevideo.com"
      - "+.msftconnecttest.com"
      - "+.msftncsi.com"
```
