### ISSUE TITLE
[Feature] 希望优化下强制走代理的场景，切换另一个订阅后必须手动更改Merge的内容

### ISSUE THREAD

**Issue by RipperTs** [clash-verge-rev/clash-verge-rev#1044]
### 功能描述 / Feature description

比如有个订阅A，里面proxy-groups的name是：`自动选择`  
然后新建一个 `Merage` 规则，使其指定的进行强制走代理 `自动选择`     
大概是下面的样子：   

```yaml
prepend-rules:
- PROCESS-NAME,BitBrowser Helper,自动选择
```

加下来我又购买/添加了一个订阅B，而里面没有 `自动选择`，而是 `🔰国外流量`等等之类的， 这时候我从订阅A切换到订阅B就会报错，因为 `Merage` 规则里面强制写死了 `自动选择` 这个代理， 而这个代理在B订阅中是不存在的

那么我现在的方法是，手动更改 `Merage` 里面的节点名称，这对后面维护来说很不方便，比较很多人都会购买一些备用的订阅线路！

因此，希望出一个统一的代理变量，比如： `AUTO-PROXY` 之类的，用来表示自动获取切换后新订阅的代理节点

大概是这个意思吧

### 使用场景 / Use case

切换订阅

**Comment by xishang0128** [comment]
@RipperTs 再merge一个策略组是会死人吗

**Comment by RipperTs** [comment]
这不是一个好的处理方式，假设订阅有n多呢？

**Comment by xishang0128** [comment]
@RipperTs https://wiki.metacubex.one/config/proxy-groups/#include-all-proxies

**Comment by PctAIGM** [comment]
```
prepend-proxy-groups:
  - name: "AllProxy"
    type: url-test
    url: 'https://www.gstatic.com/generate_204'
    interval: 300
    tolerance: 150
    lazy: true
    include-all-proxies: true
    exclude-filter: "(?i)jp|日本"
```

这是我的做法供参考
