### ISSUE TITLE
[BUG] 无法修改系统代理使用的服务器地址

### ISSUE THREAD

**Issue by Dragon1573** [clash-verge-rev/clash-verge-rev#1089]
### 问题描述 / Describe the bug

> [!NOTE]
>
> 关联 #344 ，但它 **已被锁定** 无法讨论。

借助 Merge Profile ，不论任意修改 `bind-address` ，系统代理使用的服务器地址永远为 `127.0.0.1` 。

### 复现步骤 / To Reproduce

1. 安装 _Alpha_ `x64` 版本
2. 假设你已经有一个可用的本地/远程订阅，添加一个 _Merge_ 配置文件
3. 编辑配置文件，写入以下内容
4. 重新激活订阅
5. 打开系统代理模式，点击齿轮图标进入详细设置
6. 在 **当前系统代理** 部分，你应该能看到诸如 `服务地址：127.0.0.1:7890` 的字样，无论如何改变下方的 `bind-address` 并重新激活订阅，服务地址的IP部分始终保持 `127.0.0.1`

```yaml
# Profile Enhancement Merge Template for Clash Verge
bind-address: 192.168.2.31  # 此处按照你的情况修改为可用的IP地址，例如你设备的局域网地址
```

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 专业版 23H2 (22635.3646)

### 日志 / Log

<details><summary><code>logs/2024-05-28-2327.log</code></summary>

```log
2024-05-28 23:27:06 INFO - register hotkey ALT+R clash_mode_rule
2024-05-28 23:27:06 INFO - register hotkey ALT+G clash_mode_global
2024-05-28 23:27:06 INFO - register hotkey ALT+D clash_mode_direct
2024-05-28 23:27:06 INFO - register hotkey ALT+S toggle_system_proxy
2024-05-28 23:27:06 INFO - register hotkey ALT+T toggle_tun_mode
```

</details>
<details><summary><code>logs/service/2024-05-28-2327.log</code></summary>

```log
# 启动前清空了一切日志
time="2024-05-28T23:27:05.0269748+08:00" level=info msg="Start initial configuration in progress"
time="2024-05-28T23:27:05.0355341+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-05-28T23:27:05.0360721+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-05-28T23:27:05.0489723+08:00" level=info msg="Initial configuration complete, total time: 14ms"
time="2024-05-28T23:27:05.0499564+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9097"
time="2024-05-28T23:27:05.0514661+08:00" level=info msg="Sniffer is closed"
time="2024-05-28T23:27:05.0524749+08:00" level=info msg="Mixed(http+socks) proxy listening at: 192.168.2.31:57890"
time="2024-05-28T23:27:05.0554742+08:00" level=info msg="Start initial Compatible provider 🎬哔哩哔哩"
time="2024-05-28T23:27:05.0554742+08:00" level=info msg="Start initial Compatible provider ⚓️其他流量"
time="2024-05-28T23:27:05.0564721+08:00" level=info msg="Start initial Compatible provider 🍎苹果服务"
time="2024-05-28T23:27:05.0564721+08:00" level=info msg="Start initial Compatible provider default"
time="2024-05-28T23:27:05.0564721+08:00" level=info msg="Start initial Compatible provider 🚀直接连接"
time="2024-05-28T23:27:05.0564721+08:00" level=info msg="Start initial Compatible provider 🔰国外流量"
time="2024-05-28T23:27:05.0564721+08:00" level=info msg="Start initial Compatible provider ✈️Telegram"
time="2024-05-28T23:27:05.0564721+08:00" level=info msg="Start initial Compatible provider 🎬Netflix"
time="2024-05-28T23:27:05.0564721+08:00" level=info msg="Start initial Compatible provider 🎬国外媒体"
time="2024-05-28T23:27:05.0564721+08:00" level=info msg="Start initial Compatible provider 🎬Youtube"
# 日志到此为止，以下后续内容关闭了系统代理并开启了 TUN 模式，与本问题无关
time="2024-05-28T23:35:46.7828576+08:00" level=info msg="Start initial configuration in progress"
time="2024-05-28T23:35:46.7862439+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-05-28T23:35:46.7862439+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-05-28T23:35:46.7957461+08:00" level=info msg="Initial configuration complete, total time: 12ms"
time="2024-05-28T23:35:46.7991981+08:00" level=info msg="Sniffer is closed"
time="2024-05-28T23:35:46.801978+08:00" level=warning msg="[TUN] default interface changed by monitor,  => WLAN"
...
```

</details>

**Comment by Dragon1573** [comment]
## 完整日志文件

- [logs/2024-05-28-2327.log](https://github.com/clash-verge-rev/clash-verge-rev/files/15472736/2024-05-28-2327.log)
- [logs/service/2024-05-28-2327.log](https://github.com/clash-verge-rev/clash-verge-rev/files/15472746/2024-05-28-2327.log)

**Comment by snakem982** [comment]
试试加上配置
allow-lan: true

**Comment by Dragon1573** [comment]
这个是否必须在 _Merge Profile_ 中增加？检查 _当前配置_ ，此设置项是存在的。

-----

## 当前配置

```yaml
mode: rule
mixed-port: 57890
allow-lan: true
log-level: debug
ipv6: true
secret: # 此处省略
external-controller: 127.0.0.1:9097
dns:
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 191.98.1.0/24
  nameserver:
  - 192.168.2.1
  fallback:
  - 114.114.114.114
  - 114.114.115.115
  - 223.5.5.5
  - 223.6.6.6
  - 8.8.4.4
  - 8.8.8.8
  - 1.1.1.1
  fake-ip-filter:
  - <local>
  - 10.*.*.*
  - 172.16.*.*
  - 172.17.*.*
  - 172.18.*.*
  - 172.19.*.*
  - 172.20.*.*
  - 172.21.*.*
  - 172.22.*.*
  - 172.23.*.*
  - 172.24.*.*
  - 172.25.*.*
  - 172.26.*.*
  - 172.27.*.*
  - 172.28.*.*
  - 172.29.*.*
  - 172.30.*.*
  - 172.31.*.*
  - 192.168.*.*
  # 此处省略两个企业内网域名
  - '*.cn'
bind-address: 192.168.2.31
tun:
  stack: mixed
  device: Meta
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  strict-route: false
  mtu: 1500
  enable: false
proxies: # 此处省略
proxy-providers: {}
proxy-groups: # 此处省略
rule-providers: {}
rules: # 此处省略
```
