### ISSUE TITLE
[Feature] 能否合并订阅

### ISSUE THREAD

**Issue by tianlongJ** [clash-verge-rev/clash-verge-rev#1092]
### 功能描述 / Feature description

多个订阅合并到一起，和单订阅一样节点自动切换自动更新订阅

### 使用场景 / Use case

多个订阅合并到一起，和单订阅一样节点自动切换自动更新订阅

**Comment by miaozilong** [comment]
同求

**Comment by liweishu** [comment]
> 不求你会看文档，自己参考“懒人配置”，本身内核就可以 https://wiki.metacubex.one/example/conf/

@MajoSissi 

网上可以搜到很多这种配置，配置有注释并不难懂，但是对不懂的人来说，最难的是不懂这些配置到底用在哪里！
大多数用这类软件的人，对内核不了解，GUI 下完全不知道这些配置到底从哪里导入并使用。

**Comment by gaoqiangks** [comment]
> 不求你会看文档，自己参考“懒人配置”，本身内核就可以 https://wiki.metacubex.one/example/conf/

我觉得大部分用户都能搜到这些配置, 但是经常有一个问题就是, "这些配置放在哪里, 要改哪个文件?"

**Comment by wangshuai-007** [comment]
经测试,前面的[懒人配置](https://wiki.metacubex.one/example/conf/)是可行的

操作方法如下:
* 在 `订阅`中新建一个`Local`类型的本地配置

<img width="1446" height="930" alt="Image" src="https://github.com/user-attachments/assets/6dc029c8-c825-4a88-9314-8015b5b73b48" />

* 右键新增的配置点击`编辑文件`
把懒人配置的所有内容粘贴进去,需要填写自己的订阅地址

```yml
##我的示例如下:
proxy-providers:
  p1:
    url: "https://xxxx.com?clash=3&extend=1" ##主要填这个
    type: http
    interval: 86400
    path: ./proxy_provider/p1.yml
    health-check: {enable: true,url: "https://www.gstatic.com/generate_204",interval: 300}
    override:
      additional-prefix: "[p1]"
### 其它配置
```

订阅会自动下载在`Clash Verge`目录,默认是`%APPDATA%\io.github.clash-verge-rev.clash-verge-rev`

我加了一个`path`配置,这样对应订阅`yml`文件就会在`%APPDATA%\io.github.clash-verge-rev.clash-verge-rev\proxy_provider`


保存成功后会拉取一次订阅;假如本地要更新;就要**把本地的文件(p1.yml)删除**重新拉取

多个订阅的合并里面用的节点名称正则匹配(`filter`);把同一个地区的放到一个`proxy-groups`中;

要修改订阅,简单的方法就是右键订阅配置,使用`编辑规则` `编辑节点` `编辑代理组` 调整

想要更多的个性化的功能(比如专门给AI用的订阅,节点,规则)请使用js脚本:

右键你的订阅,选择`扩展脚本` 脚本内容可参考:[convert.js](https://github.com/powerfullz/override-rules/blob/main/convert.js)(注意,**本地proxy-providers不直接兼容**[convert.js](https://github.com/powerfullz/override-rules/blob/main/convert.js)要会写代码才能使用)



或者,也可以使用[Sub-Store](https://github.com/sub-store-org/Sub-Store)合并订阅

---------
[Sub-Store](https://github.com/sub-store-org/Sub-Store)需要部署

配合这个[convert.js](https://github.com/powerfullz/override-rules/blob/main/convert.js)的`Mihomo`配置加上规则可以组合出完整的订阅

我写了文章介绍了合并方法
[使用sub-store合并多个机场的订阅](https://blog.wangshuai.app/2026-01-31-clash-verge%E5%90%88%E5%B9%B6%E8%AE%A2%E9%98%85/)

同时我还改写js实现了 `Clash for Windows`中的`Parsers`的`prepend-rules` `append-proxies` `append-proxy-groups`功能

方便添加自己的规则和代理及代理组
