### ISSUE TITLE
[BUG] 刚切换订阅节点的时候，代理会不按规则走

### ISSUE THREAD

**Issue by zxmqq1234** [clash-verge-rev/clash-verge-rev#1124]
### 问题描述 / Describe the bug

我有2个订阅
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/50194103/450a9c85-c380-4d35-b0e2-dae2ac11f65c)

刚切换订阅节点的时候，网页访问的代理会不按规则走
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/50194103/e2b99937-1881-4d29-b0d7-dd9c8595281c)
这是我预设的代理规则 ↑↑↑↑↑

这是链接的情况
![1717487190740](https://github.com/clash-verge-rev/clash-verge-rev/assets/50194103/358054ff-afed-4f72-91d8-0fded6d67a22)

也有解决办法，就是点击一次连接的右上角，全部关闭，就正常了
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/50194103/755e0470-a2aa-4be3-92dd-7a2c20545c81)

### 复现步骤 / To Reproduce

同上描述

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

WIN11

### 日志 / Log

可能不需要log？如有需要，我操作后补充~

**Comment by dongchengjie** [comment]
杂项设置里的”自动关闭连接”启用了吗？
配置文件中profile的值有修改成false呢？
```
profile:
  store-selected: true
  # 储存 API 对策略组的选择，以供下次启动时使用
  store-fake-ip: true
  # 储存 fakeip 映射表，域名再次发生连接时，使用原有映射地址
```
