### ISSUE TITLE
[BUG] 内网域名流量无法被Clash代理

### ISSUE THREAD

**Issue by Ares-X** [clash-verge-rev/clash-verge-rev#1285]
### 问题描述 / Describe the bug

**症状：浏览器访问内网华硕路由器域名一直无响应**

### 复现步骤 / To Reproduce

1. 启用了系统代理，未启用tun模式
2. 浏览器访问 router.asus.com 无响应/超时
3. Clash连接记录内无法看到这条请求
4. 日志中显示匹配到了直连规则
```
07-02 01:59:00INFO
[TCP] 127.0.0.1:57596(com.apple.WebKit.Networking) --> router.asus.com:80 match RuleSet(Lan) using DIRECT
07-02 01:59:00INFO
[TCP] 127.0.0.1:57598(com.apple.WebKit.Networking) --> router.asus.com:80 match RuleSet(Lan) using DIRECT
```
使用Curl通过代理可以看到响应内容，但是连接不会结束

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/30471149/66e02082-a570-4ac4-ab6b-0c4f9095275f)

DNS相关配置如下：
```
dns:
    enable: true
    ipv6: false
    default-nameserver: [223.5.5.5, 119.29.29.29]
    enhanced-mode: redir-host
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    fallback: ['https://doh.dns.sb/dns-query', 'https://dns.cloudflare.com/dns-query', 'https://dns.twnic.tw/dns-query', 'tls://8.8.4.4:853']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
    nameserver-policy:
      ‘router.asus.com’ : ‘192.168.1.2’
hosts:
  services.googleapis.cn: 74.125.193.94
  time.android.com: 203.107.6.88
  ipv6.msftconnecttest.com: 2a01:111:2003::52 #勿删
  www.msftconnecttest.com: 13.107.4.52 #勿删
  router.asus.com: 192.168.1.2
```

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.5

### 日志 / Log

07-02 01:59:00INFO
[TCP] 127.0.0.1:57596(com.apple.WebKit.Networking) --> router.asus.com:80 match RuleSet(Lan) using DIRECT
07-02 01:59:00INFO
[TCP] 127.0.0.1:57598(com.apple.WebKit.Networking) --> router.asus.com:80 match RuleSet(Lan) using DIRECT
