### ISSUE TITLE
[Feature] 新增节点自动测速优选延迟最低的节点

### ISSUE THREAD

**Issue by KleinPan** [clash-verge-rev/clash-verge-rev#1307]
### 功能描述 / Feature description

有些节点会失效，每次需要手动选有效的节点，希望自动定时测速，然后选择可用节点

### 使用场景 / Use case

节点失效情况下减少人为操作

**Comment by wonfen** [comment]
本来就有这功能，在配置文件里定义就行了，如果用机场的话，机场一般都会提供自动选择

**Comment by leic4u** [comment]
urltest 和 fallback 都能实现你想要的这个效果。

**Comment by KleinPan** [comment]
> 本来就有这功能，在配置文件里定义就行了，如果用机场的话，机场一般都会提供自动选择

你好，可以指一下路吗？帮助里没有写哪里配置文件可以定义

**Comment by leic4u** [comment]
@KleinPan  https://wiki.metacubex.one/config/proxy-groups/url-test/

**Comment by KleinPan** [comment]
> @KleinPan https://wiki.metacubex.one/config/proxy-groups/url-test/

机场方没提供这个，我自己搞了一下，会出现个红色图钉📌，不过好像并不能自动优选，玩不来。。

**Comment by leic4u** [comment]
@KleinPan 你可以把你订阅文件的 proxy-group 部分贴一下

**Comment by KleinPan** [comment]
proxy-groups:
  - name: 🔰 选择节点
    type: select
    proxies:
      - 🇯🇵 免费-日本1-Ver.6
      - 🇯🇵 免费-日本2-Ver.7
      - 🇯🇵 免费-日本3-Ver.6
      - 🇯🇵 免费-日本4-Ver.7
      - 🇯🇵 免费-日本5-Ver.8
      - 🇯🇵 免费-日本6-Ver.7
      - DIRECT
  - name: 🌏 爱奇艺&哔哩哔哩
    type: select
    proxies:
      - DIRECT
  - name: 📺 动画疯
    type: select
    proxies:
      - 🔰 选择节点
      - DIRECT
  - name: 🎮 Steam 登录/下载
    type: select
    proxies:
      - DIRECT
      - 🔰 选择节点
  - name: 🎮 Steam 商店/社区
    type: select
    proxies:
      - 🔰 选择节点
      - DIRECT
  - name: 🌩️ Cloudflare
    type: select

**Comment by Yamooya** [comment]
> 本来就有这功能，在配置文件里定义就行了，如果用机场的话，机场一般都会提供自动选择

您好，我在最新版（1.7.2）遇到了自动测速失效。情况是APP启动后不会进行延迟测试，但当切换页面后，再返回代理页才会延迟测试，已排除是网络延迟问题，1.6.6版本没有这个问题，相同配置文件在其他代理软件上也没问题。

**Comment by leic4u** [comment]
> 您好，我在最新版（1.7.2）遇到了自动测速失效。情况是APP启动后不会进行延迟测试，但当切换页面后，再返回代理页才会延迟测试，已排除是网络延迟问题，1.6.6版本没有这个问题，相同配置文件在其他代理软件上也没问题。

我这里复现了一下，重启应用，左侧菜单未切换，也不切换策略组，确实不会出现测速结果，但是把策略组关闭再展开后，就能正常看到测速结果了，url-test 也会自动选择到延迟最低的节点上去。

**Comment by leic4u** [comment]
@KleinPan 改成这样：

```
- name: 🔰 选择节点
  type: url-test
  url: http://www.apple.com/library/test/success.html
  interval: 300
  proxies:
    - 🇯🇵 免费-日本1-Ver.6
    - 🇯🇵 免费-日本2-Ver.7
    - 🇯🇵 免费-日本3-Ver.6
    - 🇯🇵 免费-日本4-Ver.7
    - 🇯🇵 免费-日本5-Ver.8
    - 🇯🇵 免费-日本6-Ver.7
    - DIRECT
```
