### ISSUE TITLE
1.7.x 代理组怎么添加？？

### ISSUE THREAD

**Issue by LiweiDong** [clash-verge-rev/clash-verge-rev#1312]
### 问题描述 / Describe the bug

以前是这样写的 

```
prepend-proxy-groups:
  - name: Lamucal
    type: select
    proxies:
      - 🚀 节点选择
      - ♻️ 自动选择
      - 🎯 全球直连
      - 🌍 国外媒体
      - DIRECT

```

### 复现步骤 / To Reproduce

现在给我整不会了

```
# Profile Enhancement Groups Template for Clash Verge

prepend: []

append: []

delete: []
```

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.3.1 (23D60)

### 日志 / Log

无

**Comment by noenif** [comment]
同问 ,1.6.2配置无效

**Comment by noenif** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/25174520/993e6859-0553-467f-9e65-af96716121ff)
以前文档这样配置有效的

**Comment by noenif** [comment]
> ### 问题描述 / Describe the bug
> 以前是这样写的
> 
> ```
> prepend-proxy-groups:
>   - name: Lamucal
>     type: select
>     proxies:
>       - 🚀 节点选择
>       - ♻️ 自动选择
>       - 🎯 全球直连
>       - 🌍 国外媒体
>       - DIRECT
> ```
> 
> ### 复现步骤 / To Reproduce
> 现在给我整不会了
> 
> ```
> # Profile Enhancement Groups Template for Clash Verge
> 
> prepend: []
> 
> append: []
> 
> delete: []
> ```
> 
> ### 操作系统 / OS
> MacOS
> 
> ### 操作系统版本 / OS Version
> 14.3.1 (23D60)
> 
> ### 日志 / Log
> 无

https://clash-verge-rev.github.io/guide/extend.html

**Comment by LiweiDong** [comment]
> https://clash-verge-rev.github.io/guide/extend.html

这个我看了，并没有解决问题。

> v1.7.x 版本的 Merge配置 改名为 扩展配置 ，且prepend/append功能移动至订阅右键菜单中的可视化编辑器中实现（例如：prepend-rules移动至订阅右键菜单的 编辑规则 中的 prepend）。扩展配置仅用于配置项覆写/合并。

如上，【编辑规则】确实是可视化操作了。 【编辑代理组】还是要写配置文件，我不知道语法是什么样的 。也没有示例。

**Comment by MystiPanda** [comment]
prepend:
  - name: Lamucal
    type: select
    proxies:
      - 🚀 节点选择
      - ♻️ 自动选择
      - 🎯 全球直连
      - 🌍 国外媒体
      - DIRECT

**Comment by MystiPanda** [comment]
就这么简单

**Comment by LiweiDong** [comment]
> 就这么简单

知道了，以为要写在[]括号里。。

还有个问题，【自定义的代理组】，在编辑规则的【可视化UI里不显示】，需要用高级模式自己写。

**Comment by MystiPanda** [comment]
是的，现在只能这样，后续会尝试获取

**Comment by MystiPanda** [comment]
> 还有个问题，【自定义的代理组】，在编辑规则的【可视化UI里不显示】，需要用高级模式自己写。

现在可以了

**Comment by ryuujo1573** [comment]
Hi @LiweiDong,
Thank you for your updates.
I was confused for the migration from 1.6 to 1.7: should I put `prepend-rules` along with `prepend-proxy-groups` into `prepend` section under specific config? Here's the original merge config:

```yaml

prepend-rules:
  - DOMAIN-SUFFIX,______.com,M
  - DOMAIN-SUFFIX,_________.com,M
  - DOMAIN-SUFFIX,________.com,M
  - DOMAIN-SUFFIX,_______.com,M
  - DOMAIN-SUFFIX,cloudflare.com,M
  - IP-CIDR,172.16.0.0/16,M
  - IP-CIDR,10.210.0.0/16,M-PROD
  - IP-CIDR,10.205.0.0/16,M-PROD
  

prepend-proxies: []

prepend-proxy-groups:
  - name: M
    type: select
    interface-name: en0   # select intranet adapter
    proxies:
      - DIRECT
  - name: M-PROD
    type: select
    interface-name: ppp0  # select VPN tunnel
    proxies:
      - DIRECT

append-rules: []
append-proxies: []

append-proxy-groups: []

```

**Comment by loda13** [comment]
想要编辑现有的规则，如何append 下面这段其中一行
```
proxy-groups:
  - name: Proxies
    proxies:
      - auto #想要新增这一行
```
