### ISSUE TITLE
[BUG] 1.7.3切换订阅提示不能初始化GeoIp

### ISSUE THREAD

**Issue by zhoujun681** [clash-verge-rev/clash-verge-rev#1377]
### 问题描述 / Describe the bug

 1.7.3切换订阅提示不能初始化GeoIp，1.6正常。
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/8337790/080e18bb-ef90-4941-9025-04d8202fd55c)

### 复现步骤 / To Reproduce

点击订阅切换

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

window11

### 日志 / Log

can'tinitialGeolP:can'tdownload
MMDB: Get
\"https://github.com/MetaCubeX/meta-
rules-
dat/releases/download/latest/geoip.me
tadb\:dial tcp:lookup github.com on
192.168.3.1:53: read udp 2.0.1.3:57879-
>192.168.3.1:53:i/o time0ut

**Comment by ahua666** [comment]
这种
```
- GEOIP,CN,🎯 全球直连,no-resolve
- GEOIP,CN,🎯 全球直连
```
可以先注释掉试下
```
# - GEOIP,CN,🎯 全球直连,no-resolve
# - GEOIP,CN,🎯 全球直连
```
先导入注释后的配置后连上节点，再重新导入有GEOIP的配置

**Comment by Bobbypower** [comment]
linux

**Comment by arloor** [comment]
昨天也遇到了，[https://wiki.metacubex.one/config/general/#geoip](https://wiki.metacubex.one/config/general/#geoip)中**自定义GEO下载地址**也没有配置这个geoip.metadb下载地址的方式：

```yaml
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"
```

**Comment by arloor** [comment]
> 这种
> 
> ```
> - GEOIP,CN,🎯 全球直连,no-resolve
> - GEOIP,CN,🎯 全球直连
> ```
> 
> 可以先注释掉试下
> 
> ```
> # - GEOIP,CN,🎯 全球直连,no-resolve
> # - GEOIP,CN,🎯 全球直连
> ```
> 
> 先导入注释后的配置后连上节点，再重新导入有GEOIP的配置

好像需要勾选“使用代理更新才能”，重新导入才能成功吧

**Comment by arloor** [comment]
看了下内核的代码，大概在这块：
```golang
	if _, err := os.Stat(C.Path.MMDB()); os.IsNotExist(err) {
		log.Infoln("Can't find MMDB, start download")
		if err := mmdb.DownloadMMDB(C.Path.MMDB()); err != nil {
			return fmt.Errorf("can't download MMDB: %s", err.Error())
		}
	}

	if initGeoIP != 2 {
		if !mmdb.Verify(C.Path.MMDB()) {
			log.Warnln("MMDB invalid, remove and download")
			if err := os.Remove(C.Path.MMDB()); err != nil {
				return fmt.Errorf("can't remove invalid MMDB: %s", err.Error())
			}
			if err := mmdb.DownloadMMDB(C.Path.MMDB()); err != nil {
				return fmt.Errorf("can't download MMDB: %s", err.Error())
			}
		}
		initGeoIP = 2
	}
```

再跟了下代码，默认的下载地址是这几个：

```golang
		GeoXUrl: GeoXUrl{
			Mmdb:    "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.metadb",
			ASN:     "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb",
			GeoIp:   "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat",
			GeoSite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat",
		},
```

可以都是github的地址，因为众所周知的原因，github下载是不稳定的，换成[https://github.com/MetaCubeX/meta-rules-dat](https://github.com/MetaCubeX/meta-rules-dat)列出的cdn地址就行了：

```yaml
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: 'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb'
  asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"
```

另外，asn的下载地址还是github上，但是不阻塞我的使用，可能是因为我没用到asn的规则。

另外，geoip.metadb和country.mmdb应该是同一个功能但不同格式的东西
