### ISSUE TITLE
[BUG] 测速会跳过DIRECT

### ISSUE THREAD

**Issue by utopeadia** [clash-verge-rev/clash-verge-rev#1483]
### 问题描述 / Describe the bug

使用测速、fallback、负载均衡时，不会对直连节点进行测速，在一些操作中DIRECT速度可以作为判断是否使用直连的依据，比如以下场景：
使用SS和端口转发暴露“家里云”“内网NAS”等服务，可以通过一个配置组来实现回家连入局域网自动使用直连，离开局域网自动使用端口转发节点：
```
name: 回家节点
    type: url-test
    url: 某个局域网内网地址
    proxies:
      - DIRECT
      - SS端口转发
```
但是由于DIRECT无法进行测速，则无法进行切换，无论内网还是外网默认均被切换到了转发
![image](https://github.com/user-attachments/assets/be4bae49-3aeb-478f-ba34-df96e454ab4e)

### 复现步骤 / To Reproduce

测速

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11 23h2

### 日志 / Log

非配置问题
