### ISSUE TITLE
[BUG] merge.yaml里面定义DOMAIN正常，但是RULE-SET失败

### ISSUE THREAD

**Issue by wjx0912** [clash-verge-rev/clash-verge-rev#1491]
### 问题描述 / Describe the bug

```
rule-providers:
  gemini:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.yaml"
    path: ./ruleset/gemini.yaml
    interval: 86400

proxy-groups:
  - { name: AUTO, type: select, include-all: true }
  - { name: GeminiProxy, type: url-test, include-all: true, filter: "D43" }

rules:
  - DOMAIN,gemini.google.com,GeminiProxy         # (1)用这个可以访问gemini
  - RULE-SET,gemini,GeminiProxy                  # (2)换成这个就不行了
  - GEOIP,LAN,AUTO
  - GEOIP,CN,AUTO
  - MATCH,AUTO
 ```

希望用订阅的，而不是自己定义的网址。检查了./ruleset/gemini.yaml是有下载的（内容正常）。

还请各位大佬不吝赐教～～～

### 复现步骤 / To Reproduce

none

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

12.6

### 日志 / Log

none
