### ISSUE TITLE
[BUG] 系统dns被覆盖，无法通过扩展配置或者全局扩展配置进行覆盖，依然会生效

### ISSUE THREAD

**Issue by Moouna** [clash-verge-rev/clash-verge-rev#1511]
### 问题描述 / Describe the bug

订阅中包含dns配置后采用扩展配置、全局配置无法覆盖，依然会对系统网络的dns服务器地址进行覆盖

### 复现步骤 / To Reproduce

使用了订阅功能
订阅下来的文件是
`dns:
  enable: true
  ipv6: false
  nameserver:
    - 223.5.5.5`
之后我在这个订阅上的扩展配置和全局配置中均填写了如下配置
`dns:
  enable: false
  use-system-hosts: true
  nameserver:
    - 192.168.20.23
    - 192.168.13.23
`
扩展脚本和全局脚本中的配置
`
function main(config, profileName) {
  config["dns"]["enable"] = false
  config["dns"]["nameserver"] = ["192.168.20.23"]
  return config;
}
`
点击查看当前配置
`
dns:
  enable: false
  ipv6: false
  nameserver:
  - 192.168.20.23
`
但是打开网络的dns，依然被覆盖为了223.5.5.5
无法生效
客户端版本Clash.Verge_1.7.5_x64.dmg

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.4.1 (23E224)

### 日志 / Log

none

**Comment by xishang0128** [comment]
覆盖系统dns和设置无关,覆盖是为了给代理核心劫持,这是预期行为

**Comment by Moouna** [comment]
> 覆盖系统dns和设置无关,覆盖是为了给代理核心劫持,这是预期行为

但是
1. 局域网环境，我需要有dns服务的配置
2.我的代理核心有十几项的dns服务配置，只取了第一个是不是完全不合理
3.是否dns服务器应该改为对dns列表进行合并
因为我还有规则在配置，比如局域网内部的域名需要跳过的时候走默认的dns，现在如果采用代理核心覆盖导致我局域网很多域名没法正常解析了

**Comment by eunrui** [comment]
是的，merge的怎么配都没用，只要打开软件就会变成223.5.5.5，无论DNS下的nameserver和default-server是否有内容，都会覆盖成223.5.5.5，在公司内网的时候也在头痛这个问题，目前只能开启后再手动去改一遍DNS，这个issue怎么就关闭了呢，我搜索了下issue中其他人有这样的问题，关联issue[#1247]

**Comment by mistingrain** [comment]
@eunrui  @Moouna    DNS配置中加入下面这行就行了
default-nameserver:
  **- system**

**Comment by eunrui** [comment]
> @eunrui @Moouna DNS配置中加入下面这行就行了 default-nameserver: **- system**

```
dns:
  use-system-hosts: true
  nameserver:
    - system
    - 10.128.128.61
    - 202.106.0.20
  default-nameserver:
    - system
    - tls://10.128.128.61
    - tls://202.106.0.20
```

是这个意思吗? 方便发个例子不
