### ISSUE TITLE
[BUG]  全局拓展配置不支持追加节点，代理组、规则功能

### ISSUE THREAD

**Issue by witt-bit** [clash-verge-rev/clash-verge-rev#1523]
### 问题描述 / Describe the bug

```yaml
# 规则
prepend-rules:

append-rules:

# 节点
prepend-proxies:
append-proxies:

# 代理组
prepend-proxy-groups:
append-proxy-groups:

```

在全局拓展配置中配置这几个Key无效，之前支持的，现在不支持了，需要在所有订阅中共享，Windows和Linux客户端都不支持

### 复现步骤 / To Reproduce

无

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

无
