### ISSUE TITLE
[BUG] 设置中TUN模式的DNS劫持只能有一项

### ISSUE THREAD

**Issue by Alexius66** [clash-verge-rev/clash-verge-rev#1545]
### 问题描述 / Describe the bug

在拓展配置中加入如下的TUN配置：
```
tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 9000
  strict-route: true
```
之后运行时订阅显示：
```
tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  mtu: 9000
  strict-route: true
  device: Mihomo
```

### 复现步骤 / To Reproduce

如上，且直接将这段配置加入配置文件也得到相同结果

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

22635.4010

### 日志 / Log

应该与日志无关，希望开发者支持TUN模式DNS同时劫持多项，内核是支持这个特性的。
下为官方文档中提供的快捷配置写法：
```tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
```
