### ISSUE TITLE
[BUG] macOS系统中 mihomo TUN模式无法与tailscale同时使用

### ISSUE THREAD

**Issue by yudshj** [clash-verge-rev/clash-verge-rev#1626]
### 问题描述 / Describe the bug

macOS下 clash verge rev 的 tun模式无法与tailscale同时使用。

怀疑是macOS系统NAT规则优先级配置问题（或是[auto-redirect](https://wiki.metacubex.one/config/inbound/tun/#auto-redirect)无法在macOS下正常工作）。

### 复现步骤 / To Reproduce

依次安装tailscale.app, clash verge.app；
登陆到tailscale；
启用clashverge的tun模式；
a. 打开终端 Terminal.app，输入“curl google.com“
b. 打开终端 Terminal.app，输入“curl 100.123.0.1“（某tailscale内网ip）

结果：
1. 当关闭tailscale时，a指令可以正常工作（tun模式正常），b无返回
2. 当开启tailscale时，b指令可以正常工作，a返回 "curl: (52) Empty reply from server"

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

Sequoia 15.0 Beta

### 日志 / Log

日志中无法找到tailscale节点的相关信息。

**Comment by yudshj** [comment]
已关闭互联网共享，如下图所示。

<img width="469" alt="截屏2024-08-25 15 32 48" src="https://github.com/user-attachments/assets/0220032c-9065-4b05-9de5-6b1ed3bc16b3">

**Comment by yudshj** [comment]
Tailscale配置如下图所示。

<img width="712" alt="截屏2024-08-25 15 33 35" src="https://github.com/user-attachments/assets/fe3e4255-e845-49e8-a86a-9a011f278637">

**Comment by xuexue49** [comment]
win下也存在这种情况，开启tailscale直接无法上网

**Comment by PrintNow** [comment]
@yudshj @xuexue49  试一下这样可不可行（我是 Windows 环境）。

先启动 tailscale，然再启动 clash，config 按照如下配置：
```yaml
tun:
  exclude-interface:
    - Tailscale
    - Rustdesk
  route-exclude-address:
    - 100.64.0.0/10
    - 10.0.0.0/8
    - 223.5.5.5/32
    - 1.1.1.1/32
```

![image](https://github.com/user-attachments/assets/78bcfba5-e2be-470c-9c96-8c54f2f4b1d7)

![image](https://github.com/user-attachments/assets/88b66d71-f3b7-4b6f-9af5-0921b396c75a)
