### ISSUE TITLE
[BUG] connect error: encoding/hex: invalid byte: U+0069 'i'

### ISSUE THREAD

**Issue by Morphey3020** [clash-verge-rev/clash-verge-rev#1780]
### 问题描述 / Describe the bug

Trying to connect to the proxy results in the following error: connection error: encoding/hex: invalid byte: U+0069 'i'. I have attached an image from Wireshark below. I am experiencing the same problem on **Windows 10** and **Linux**.
![Screenshot](https://github.com/user-attachments/assets/c475a5fa-8768-48f3-8c38-faf3a65388ce)

### 复现步骤 / To Reproduce

1. Create a local config file with the following contents:
profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080]
      override-destination: true

dns:
  enable: true
  prefer-h3: false
  listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: redir-host
  fake-ip-range: 28.0.0.1/8
  use-hosts: true
  default-nameserver:
    - https://1.1.1.1/dns-query
  nameserver:
    - https://1.1.1.1/dns-query
  fallback:
    - https://1.1.1.1/dns-query
  proxy-server-nameserver:
    - https://1.1.1.1/dns-query

proxies:
  - name: Reality
    type: vless
    server: skull-512.com
    port: 443
    udp: true
    uuid: _
    flow: xtls-rprx-vision
    packet-encoding: xudp

    tls: true
    servername: skull-512.com
    alpn:
      - h2
      - http/1.1
    fingerprint: firefox
    client-fingerprint: firefox
    skip-cert-verify: false
    reality-opts:
      public-key: _
      short-id: _

    network: tcp

    smux:
      enabled: false
2. Go to Proxies ==> Global ==> Reality.
3. Test with any website.
4. An error will appear in the logs.

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Debian 12 (Gnome 43.9).

### 日志 / Log

time="2024-09-27T16:33:07.604107684+07:00" level=debug msg="[DNS] skull-512.com --> [] AAAA from https://1.1.1.1:443/dns-query"
time="2024-09-27T16:33:07.70109823+07:00" level=warning msg="[TCP] dial GLOBAL 28.0.0.1:33678 --> www.github.com:443 error: skull-512.com:443 connect error: encoding/hex: invalid byte: U+0069 'i'"
time="2024-09-27T16:33:07.711818704+07:00" level=debug msg="[DNS] cache hit skull-512.com --> [94.247.42.234] A, expire at 2024-09-27 16:38:07"
time="2024-09-27T16:33:07.711906425+07:00" level=debug msg="[DNS] cache hit skull-512.com --> [] AAAA, expire at 2024-09-27 17:03:07"
time="2024-09-27T16:33:07.808026674+07:00" level=warning msg="[TCP] dial GLOBAL 28.0.0.1:33678 --> www.github.com:443 error: skull-512.com:443 connect error: encoding/hex: invalid byte: U+0069 'i'"

**Comment by tedli** [comment]
怎么解的？应该怎么配？我用 xray run -c client.json 可以通，但是配到 clash-verge 里，也是报`encoding/hex: invalid byte: `

**Comment by tedli** [comment]
Hi @Morphey3020 ,
Thanks for reply.
I finally got it solved myself. It's weird that you have to set `udp: true` along with `network: tcp`.

```yaml
- name: 🇺🇸 DC9-REALITY 🚀😁
   type: vless
   server: xx.yy.zz
   port: 443
   uuid: e888888c-e888-5883-8888-d888c888f88
   flow: xtls-rprx-vision
   udp: true
   tls: true
   client-fingerprint: chrome
   servername: xx.yy.zz
   skip-cert-verify: false
   reality-opts:
     short-id: fc8888af88f88888
     public-key: R8u8Q0Kmy5YVhQppbbOIPhK3TSFbvgtemZlVu8KcpG8
   network: tcp
```
![image](https://github.com/user-attachments/assets/c074f1b3-f70c-4617-94b7-74cd92bdf0cd)
