### ISSUE TITLE
[BUG] 无法彻底关闭『外部控制』

### ISSUE THREAD

**Issue by MFWT** [clash-verge-rev/clash-verge-rev#1795]
### 问题描述 / Describe the bug

Clash Verge Rev（以下简称CVR）会强制给配置文件加入外部控制选项，且设置项目中仅可设置监听端口和访问密钥，无法**彻底关闭**外部访问功能

### 复现步骤 / To Reproduce

提供一个没有开启外部控制功能的配置文件：
```yaml
mode: rule
mixed-port: 7890
allow-lan: true
log-level: warning
ipv6: true
# external-controller: 127.0.0.1:9090
# secret: "some_secret_keeeeeeeeeeeeeeeeeys"

# 以下为节点信息

```

导入并选中使用，在CVR的『设置』——『当前配置』中查看当前配置文件，可以看到已经被强制覆盖为默认设置的127.0.0.1:9097

```yaml
mode: rule
mixed-port: 7890
allow-lan: true
log-level: warning
ipv6: true
external-controller: 127.0.0.1:9097
secret: sdjghsdhgdagdaligiughiusgiusgiusnglkjewsaneajnf
````

访问127.0.0.1:9097（并提供设置的密钥），可以正常使用

由于默认设置并没有配置访问密钥，任何一个网站均可以通过访问这个接口的方式获取用户的所有节点，当前连接状况等敏感信息

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 10 22H2

### 日志 / Log

无
