### ISSUE TITLE
[BUG] clash 尝试通过公网网卡访问局域网中的地址

### ISSUE THREAD

**Issue by AprilGrimoire** [clash-verge-rev/clash-verge-rev#1818]
### 问题描述 / Describe the bug

clash尝试通过适配器`wlp4s0`访问`192.168.100.241`，在external controller的config中可以看到`interface-name	"wlp4s0"`。

### 复现步骤 / To Reproduce

使用本地的config.yaml：
```
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info

proxies:
  - name: "socks"
    type: socks5
    server: 192.168.100.241
    port: 1080

proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - "socks"

rules:
  - MATCH,Proxy
```

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Gentoo Linux x86_64, 6.10.9-gentoo, GNOME 45.5 (x11)

### 日志 / Log

```
{"type":"warning","payload":"[TCP] dial Proxy (match Match/) 198.18.0.1:38334 --\u003e connectivity-check.ubuntu.com:80 error: 192.168.100.241:1080 connect error: dial tcp 192.168.100.241:1080: i/o timeout"}
{"type":"warning","payload":"[TCP] dial Proxy (match Match/) 198.18.0.1:48334 --\u003e vpn.pku.edu.cn:443 error: 192.168.100.241:1080 connect error: dial tcp 192.168.100.241:1080: i/o timeout"}
{"type":"warning","payload":"[TCP] dial Proxy (match Match/) 198.18.0.1:36090 --\u003e google.ru:443 error: 192.168.100.241:1080 connect error: dial tcp 192.168.100.241:1080: i/o timeout"}
{"type":"warning","payload":"[TCP] dial Proxy (match Match/) 198.18.0.1:57820 --\u003e 149.154.175.100:443 error: 192.168.100.241:1080 connect error: dial tcp 192.168.100.241:1080: i/o timeout"}
{"type":"warning","payload":"[TCP] dial Proxy (match Match/) 198.18.0.1:49298 --\u003e 149.154.175.100:80 error: 192.168.100.241:1080 connect error: dial tcp 192.168.100.241:1080: i/o timeout"}
{"type":"warning","payload":"[TCP] dial Proxy (match Match/) 198.18.0.1:36292 --\u003e connectivity-check.ubuntu.com:80 error: 192.168.100.241:1080 connect error: dial tcp 192.168.100.241:1080: i/o timeout"}
```
