### ISSUE TITLE
[BUG] 配置加认证绕过地址，不生效

### ISSUE THREAD

**Issue by yixiuge301** [clash-verge-rev/clash-verge-rev#1831]
### 问题描述 / Describe the bug

配置添加 skip-auth-prefixes 字段，还是要求认证。
![image](https://github.com/user-attachments/assets/e5d8dddf-f574-4f59-996d-c530c8f614d1)

试了跑内核，没问题，是不是 clash-verge-rev 还不支持呢

看到有个旧 issue，但锁了
https://github.com/clash-verge-rev/clash-verge-rev/issues/46

### 复现步骤 / To Reproduce

就在配置里加
```yaml
authentication:
- proxy:clash
skip-auth-prefixes:
- 127.0.0.1/8
- ::1/128
```

### 操作系统 / OS

Windows 10 Pro 22H2

### clash-verge-rev 版本
clash-verge-rev 是 1.7.7，内核试过最新的和 1.7.7 配套的
![image](https://github.com/user-attachments/assets/ede0d11b-eee6-46df-a0cd-bc48e3b69c63)

### 日志 / Log

无
