### ISSUE TITLE
[BUG]  RuleSet规则集优先级永远低于自定义规则

### ISSUE THREAD

**Issue by mrycguo** [clash-verge-rev/clash-verge-rev#1855]
### 问题描述 / Describe the bug

访问域名gemini.google.com，预期为匹配gemini的RuleSet，但是匹配不成功。

clash verge rev 日志
```
主机: gemini.google.com:443
下载量: 146 KB
上传量: 32.5 KB
下载速度: 0 B/s
上传速度: 0 B/s
链路: PROXY / Aliyun SAS
规则: AND(((ProcessName,chrome.exe) && (InType,SOCKS)))
进程: chrome.exe(C:\Program Files\Google\Chrome\Application\chrome.exe)
连接时间: 几秒前
源地址: 127.0.0.1:13320
目标地址: 142.250.196.206
类型: Socks5(tcp)
```

配置规则如下
```
rule-providers:  
  gemini:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Gemini/Gemini.yaml
    path: ./providers/rules/gemini.yaml
    interval: 86400

  rules:
  # GEMINI 规则
- RULE-SET,gemini,USA

  # 浏览器规则
- AND,((PROCESS-NAME,chrome.exe),(IN-TYPE,tun)),DIRECT    # chrome浏览器默认直连
- AND,((PROCESS-NAME,chrome.exe),(IN-TYPE,socks)),PROXY   # chrome浏览器socks走代理
```

### 复现步骤 / To Reproduce

1、按照问题描述中配置规则集；
2、访问域名gemini.google.com；
3、查看clash verge日志

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

10

### 日志 / Log

10-14 22:12:38INFO
[TCP] 127.0.0.1:13320(chrome.exe) --> gemini.google.com:443 match AND(((ProcessName,chrome.exe) && (InType,SOCKS))) using PROXY[Aliyun SAS]
