### ISSUE TITLE
扩展配置如何扩展订阅的rules

### ISSUE THREAD

**Issue by GeTOUO** [clash-verge-rev/clash-verge-rev#1871]
### 功能描述 / Feature description

请问如何配置在订阅的规则里面添加一个高优先级的规则？
比如针对 xxx.work.cn 的流量我期望通过127.0.0.1的1080端口代理，但不影响其他流量。怎么扩展配置呢？

### 使用场景 / Use case

流量转发

**Comment by GeTOUO** [comment]
我在全局的扩展中新增了以下内容（我是1.7.7版本）：
```
prepend-proxies:
 - {"name": "vpn", "type": "socks5", "server": "127.0.0.1", "port": 1080}

prepend-rules: [
  "DOMAIN,git.work.cn,vpn"
]
```
但是没有生效,在订阅中匹配了 CN后缀的规则

**Comment by Tychristine** [comment]
@GeTOUO 要使用订阅的Rules，可以自编写一个config.yaml，详情见内核文档；
规则写法
```yaml
  SteamCN: 
    type: http (http或file)
    behavior: classical
    format: yaml
    url: "规则链接/steamcn.yaml"
    path: ./rule/steamcn.yaml(本地存储路径)
    interval: 43200 (自动更新时间单位'秒')
```

使用
```yaml
- RULE-SET,SteamCN,DIRECT
```

至于你说的`example.cn`分流，可以单独做一个策略组精准控制
可参考我的模板 https://blog.tyasaka.xyz/beta/clash_template.yaml
