### ISSUE TITLE
[BUG] V2.0.0-rc开启tun关闭系统代理时无法打开国内网站

### ISSUE THREAD

**Issue by wyrain** [clash-verge-rev/clash-verge-rev#1880]
### 问题描述 / Describe the bug

- Win11专业版系统
- Verge版本v2.0.0-rc.1
- 规则集没问题
- 开启Tun关闭系统代理，无法打开国内网址，如：bilibili.com；可以打开国外网址
- 开启Tun同时开启系统代理没问题，关闭Tun开启系统代理没问题
- Tun的三种stack模式试了，都是一样的有问题
- 网络适配器里有Mihomo
- 查看日志发现出问题时，根本没有记录到国内域名如bilibili.com的记录

### 复现步骤 / To Reproduce

见问题描述

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 专业版

### 日志 / Log

见问题描述

**Comment by wyrain** [comment]
演示Gif
![241019 112533](https://github.com/user-attachments/assets/5033c281-db74-4767-9bca-3ed90fe2d046)

**Comment by wonfen** [comment]
看日志有dns解析失败的记录，检查配置文件问题。

**Comment by wyrain** [comment]
> 看日志有dns解析失败的记录，检查配置文件问题。

那个是我没开IPV6的警告，还不是核心问题。

**Comment by wyrain** [comment]
关掉Tun设置里的自动设置全部路由，可以解决我的问题。可是这样的Tun是不是就没有意义了。

**Comment by wyrain** [comment]
换了规则，解决问题了
原来拥抱的ACL4SSR规则有问题：
```yml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
```

换了个地方生成订阅，新的规则没问题:
```yml
mixed-port: 7890
allow-lan: false
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
clash-for-android:
  append-system-dns: false
hosts:
  mtalk.google.com: 108.177.125.188
dns:
  enable: true
  listen: 127.0.0.1:5335
  default-nameserver: [180.184.1.1, 119.29.29.29, 223.5.5.5]
  ipv6: true
  use-hosts: true
  fake-ip-filter: ["*.n.n.srv.nintendo.net", +.stun.playstation.net, xbox.*.*.microsoft.com, "*.msftncsi.com", "*.msftconnecttest.com", WORKGROUP, "*.lan", stun.*.*.*, stun.*.*, time.windows.com, time.nist.gov, time.apple.com, time.asia.apple.com, "*.ntp.org.cn", "*.openwrt.pool.ntp.org", time1.cloud.tencent.com, time.ustc.edu.cn, pool.ntp.org, ntp.ubuntu.com, "*.*.xboxlive.com", speedtest.cros.wr.pvp.net]
  nameserver: [tls://223.5.5.5:853, https://223.6.6.6/dns-query, https://120.53.53.53/dns-query]
  nameserver-policy: {+.tmall.com: 223.5.5.5, +.taobao.com: 223.5.5.5, +.alicdn.com: 223.5.5.5, +.aliyun.com: 223.5.5.5, +.alipay.com: 223.5.5.5, +.alibaba.com: 223.5.5.5, +.qq.com: 119.29.29.29, +.tencent.com: 119.29.29.29, +.weixin.com: 119.29.29.29, +.qpic.cn: 119.29.29.29, +.jd.com: 119.29.29.29, +.bilibili.com: 119.29.29.29, +.hdslb.com: 119.29.29.29, +.163.com: 119.29.29.29, +.126.com: 119.29.29.29, +.126.net: 119.29.29.29, +.127.net: 119.29.29.29, +.netease.com: 119.29.29.29, +.baidu.com: 223.5.5.5, +.bdstatic.com: 223.5.5.5, +.bilivideo.+: 119.29.29.29, +.iqiyi.com: 119.29.29.29, +.douyinvod.com: 180.184.1.1, +.douyin.com: 180.184.1.1, +.douyincdn.com: 180.184.1.1, +.douyinpic.com: 180.184.1.1, +.feishu.cn: 180.184.1.1}
  fallback: [https://101.101.101.101/dns-query, https://public.dns.iij.jp/dns-query, https://208.67.220.220/dns-query]
  fallback-filter: {geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32, 223.75.236.241/32, 182.43.124.6/32, 106.74.25.198/32], domain: [+.bianyuan.xyz, +.happynothings031.xyz, +.jsdelivr.net, +.proton.me]}
```
