### ISSUE TITLE
[BUG] 为什么clash-verge-rev还限制配置绕过认证？

### ISSUE THREAD

**Issue by yixiuge301** [clash-verge-rev/clash-verge-rev#1892]
### 问题描述 / Describe the bug

配置了绕过认证，但是不生效

同样的配置文件，直接跑内核是正常的

https://github.com/clash-verge-rev/clash-verge-rev/issues/1831

### 软件版本 / Verge Version

Clash.Verge_2.0.0-rc.2_x64

### 复现步骤 / To Reproduce

配置文件添加认证和绕过地址

```yaml
authentication:
- proxy:clash
skip-auth-prefixes:
- 127.0.0.1/8
- ::1/128
```

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

10

### 日志 / Log

无
