### ISSUE TITLE
[BUG] 向日葵无法正常连接

### ISSUE THREAD

**Issue by jianxuanbing** [clash-verge-rev/clash-verge-rev#1917]
### 问题描述 / Describe the bug

向日葵连接失效
![image](https://github.com/user-attachments/assets/fba1bdac-0f84-43e0-b4fc-6e223332f8a2)
使用1.x版本能正常连接，使用2.x则没法远程连接

### 软件版本 / Verge Version

v2.0.0-rc.2

### 复现步骤 / To Reproduce

使用2.x版本，连接失败

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win10

### 日志 / Log

```
10-23 11:14:01warning
[TCP] dial DIRECT (match RuleSet/direct) 198.18.0.1:64590(SunloginClient.exe) --> 886914301-1890435128ls5111612f.rc03.oray.com:443 error: dns resolve failed: all DNS requests failed, first error: server failure: SERVFAIL
10-23 11:14:02warning
[TCP] dial DIRECT (match RuleSet/direct) 198.18.0.1:64590(SunloginClient.exe) --> 886914301-1890435128ls5111612f.rc03.oray.com:443 error: dns resolve failed: all DNS requests failed, first error: server failure: SERVFAIL
10-23 11:14:02warning
[TCP] dial DIRECT (match RuleSet/direct) 198.18.0.1:64590(SunloginClient.exe) --> 886914301-1890435128ls5111612f.rc03.oray.com:443 error: dns resolve failed: all DNS requests failed, first error: server failure: SERVFAIL
10-23 11:14:03info
[TCP] 198.18.0.1:53307(SunloginClient.exe) --> api-adv.sunlogin.oray.com:443 match RuleSet(direct) using DIRECT
10-23 11:14:03warning
[TCP] dial DIRECT (match RuleSet/direct) 198.18.0.1:53311(SunloginClient.exe) --> 886914301-1890435128ls5111612f.rc03.oray.com:443 error: dns resolve failed: all DNS requests failed, first error: server failure: SERVFAIL
10-23 11:14:03warning
[TCP] dial DIRECT (match RuleSet/direct) 198.18.0.1:53311(SunloginClient.exe) --> 886914301-1890435128ls5111612f.rc03.oray.com:443 error: dns resolve failed: all DNS requests failed, first error: server failure: SERVFAIL
10-23 11:14:03warning
[TCP] dial DIRECT (match RuleSet/direct) 198.18.0.1:53311(SunloginClient.exe) --> 886914301-1890435128ls5111612f.rc03.oray.com:443 error: dns resolve failed: all DNS requests failed, first error: server failure: SERVFAIL
10-23 11:14:04warning
[TCP] dial DIRECT (match RuleSet/direct) 198.18.0.1:53311(SunloginClient.exe) --> 886914301-1890435128ls5111612f.rc03.oray.com:443 error: dns resolve failed: all DNS requests failed, first error: server failure: SERVFAIL
```

**Comment by wonfen** [comment]
用了tun模式？

**Comment by sagasm** [comment]
可以试试用这个脚本:
https://www.clashverge.dev/guide/script.html#1
可以解决很多dns疑难问题

**Comment by jianxuanbing** [comment]
> 用了tun模式？
> 
> 试试在网卡设置中添加一个223.5.5.5的DNS： 设置方法: https://www.alidns.com/knowledge?type=SETTING_DOCS#user_windows

没有开启tun模式，而且发现，新版本的好多域名都被拦截掉了。
![image](https://github.com/user-attachments/assets/0b648469-27da-4172-9ce7-1454c2c236b0)

**Comment by jianxuanbing** [comment]
> > > 用了tun模式？
> > > 试试在网卡设置中添加一个223.5.5.5的DNS： 设置方法: https://www.alidns.com/knowledge?type=SETTING_DOCS#user_windows
> > 
> > 
> > 没有开启tun模式，而且发现，新版本的好多域名都被拦截掉了。 ![image](https://private-user-images.githubusercontent.com/7100363/379119789-0b648469-27da-4172-9ce7-1454c2c236b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTEyMzcsIm5iZiI6MTcyOTY5MDkzNywicGF0aCI6Ii83MTAwMzYzLzM3OTExOTc4OS0wYjY0ODQ2OS0yN2RhLTQxNzItOWNlNy0xNDU0YzJjMjM2YjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMTM0MjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDgxNzIwODc2ZmM5NDg2N2IxNWE1ZGE4ZmFhYzllYjE3ZjY4Y2JhNmMyY2IzMDhmMTNjMGJjNDM2MmM5ZjBhYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.V7njPFY-sgU3k68RG8K5musyGiy0TC2BFmIlMmO4cIU)
> 
> 添加dns测试了吗？

添加了以下的正常了，但是日志里面经常出现`i/o timeout`
```
default-nameserver:
    - 114.114.114.114
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - 110.43.41.122                       # 广州电信/联通/移动 防污染DNS
    - 114.114.114.114
    - 223.5.5.5
    - 119.29.29.29
  fallback:
    - tls://8.8.4.4:853 # 谷歌服务 DNS
    - tls://1.1.1.1:853 # Cloudflare DNS
  proxy-server-nameserver:
    # 国内DNS服务器
    - https://dns.alidns.com/dns-query  # 阿里云公共DNS
    - https://doh.pub/dns-query         # 腾讯DNSPod
    - https://doh.360.cn/dns-query      # 360安全DNS
    # 国外DNS服务器
    - https://1.1.1.1/dns-query         # Cloudflare(主) DNS
    - https://1.0.0.1/dns-query         # Cloudflare(备) DNS
    - https://208.67.222.222/dns-query  # OpenDNS(主) DNS
    - https://208.67.220.220/dns-query  # OpenDNS(备) DNS
    - https://194.242.2.2/dns-query     # Mullvad(主) DNS
    - https://194.242.2.3/dns-query     # Mullvad(备) DNS
```

![image](https://github.com/user-attachments/assets/8b0ec38c-10d7-4573-96ee-acf0298aa8a9)
![image](https://github.com/user-attachments/assets/38a341c6-729b-47f9-97d3-c0e4ef416510)
