### ISSUE TITLE
[BUG] DNS扩展脚本部分没法完全使用扩展脚本的配置

### ISSUE THREAD

**Issue by yyhhyyyyyy** [clash-verge-rev/clash-verge-rev#2125]
### 问题描述 / Describe the bug

扩展脚本中dns部分指明 ipv6: false, "fake-ip-range": "28.0.0.1/8", 
但是不生效  而是以   ipv6: true  , "fake-ip-range": "198.18.0.1/16",  生效  

有尝试在代码中找到对应配置
`src-tauri/src/enhance/tun.rs` `use_tun`函数部分
当开启tunnel的时候  只能按照  `if enable` 的值进行填充
但是我检索 `198.18.0.1/16` 时 在 仓库中 没找到对应部分  而且按照  `if enable`的逻辑 也应该使用的是 `10.96.0.0/16`才对 不知道`198.18.0.1/16`是怎么出现的

### 软件版本 / Verge Version

2.0.1

### 复现步骤 / To Reproduce

扩展脚本：
```js
function main (params) {
    if (!params.proxies) return params;
    overwriteDns (params);
    return params;
}

// 覆写DNS
function overwriteDns (params) {
    const dnsList = [
        "https://223.5.5.5/dns-query",
        "https://doh.pub/dns-query",
    ];

    const proxyDnsList = [
        "https://223.5.5.5/dns-query",
        "https://doh.pub/dns-query",
    ];

    const dnsOptions = {
        enable: true,
        ipv6: false,
        "prefer-h3": true,
        "respect-rules": true,
        "enhanced-mode": "fake-ip",
        "fake-ip-range": "28.0.0.1/8",
        nameserver: dnsList,
        "proxy-server-nameserver": proxyDnsList,
    };
    params.dns = { ...dnsOptions };
}
```

将以上扩展脚本贴入即可

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

最后点击当前配置后的 dns部分 如下：
```yaml
dns:
  enable: true
  ipv6: true
  prefer-h3: true
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - https://223.5.5.5/dns-query
  - https://doh.pub/dns-query
  proxy-server-nameserver:
  - https://223.5.5.5/dns-query
  - https://doh.pub/dns-query
```
