### ISSUE TITLE
[BUG] V2.0.1 使用全局扩展配置merge不生效

### ISSUE THREAD

**Issue by Ronchy2000** [clash-verge-rev/clash-verge-rev#2209]
### 问题描述 / Describe the bug

我的需求是在某些网站使用直连，配置时出现问题。
我的全局扩展配置为：
```

# Profile Enhancement Merge Template for Clash Verge

append-rules: [
  "DOMAIN-SUFFIX,bilibili.com/,DIRECT",
  "DOMAIN-SUFFIX,cn.bing.com/,DIRECT",
  "DOMAIN-SUFFIX,sicnuwiki.com/,DIRECT",
  "DOMAIN-SUFFIX,www.sicnuwiki.com/,DIRECT",
  "DOMAIN-SUFFIX,cloud.tencent.com/,DIRECT",
  # 文献库
  "DOMAIN-SUFFIX,dl.acm.org/,DIRECT",
  "DOMAIN-SUFFIX,ieeexplore.ieee.org/,DIRECT",
  "DOMAIN-SUFFIX,sciencedirect.com/,DIRECT",
  "DOMAIN-SUFFIX,aaai.org/,DIRECT",
  "DOMAIN-SUFFIX,onlinelibrary.wiley.com/,DIRECT",
  "DOMAIN-SUFFIX,id.elsevier.com/,DIRECT",

  #steam
  "DOMAIN-SUFFIX,geosite:steam@cn,DIRECT",
  "DOMAIN-SUFFIX,domain:steamserver.net,DIRECT"
]

prepend-proxies: []
prepend-proxy-groups: []
append-proxies: []
append-proxy-groups: []

profile:
  store-selected: true

dns:
  use-system-hosts: false

# rules:
#   # 直连
#   - DOMAIN-SUFFIX,bilibili.com/,DIRECT
#   - "DOMAIN-SUFFIX,cn.bing.com/,DIRECT"
#   - "DOMAIN-SUFFIX,sicnuwiki.com/,DIRECT"
#   - "DOMAIN-SUFFIX,cloud.tencent.com/,DIRECT"
#   # 文献库
#   - "DOMAIN-SUFFIX,dl.acm.org/,DIRECT"
#   - "DOMAIN-SUFFIX,ieeexplore.ieee.org/,DIRECT"
#   - "DOMAIN-SUFFIX,sciencedirect.com/,DIRECT"
#   - "DOMAIN-SUFFIX,aaai.org/,DIRECT"
#   - "DOMAIN-SUFFIX,onlinelibrary.wiley.com/,DIRECT"
#   - "DOMAIN-SUFFIX,id.elsevier.com/,DIRECT"
#   #steam
#   - "DOMAIN-SUFFIX,geosite:steam@cn,DIRECT"
#   - "DOMAIN-SUFFIX,domain:steamserver.net,DIRECT"
```
发现rules: 会覆盖掉机场提供的规则。遂使用append-rules(or prepend-rules)。

我点击`查看运行时订阅`文件，其中：

```
mode: rule
mixed-port: 7897
allow-lan: false
log-level: info
external-controller: 127.0.0.1:9097
secret: ''
unified-delay: true
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://doh.dns.sb/dns-query
  - https://dns.cloudflare.com/dns-query
  - https://dns.twnic.tw/dns-query
  - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
  use-system-hosts: false
bind-address: '*'
append-proxy-groups: []
tun:
  stack: gvisor
  device: Mihomo
  auto-route: true
  strict-route: false
  auto-detect-interface: true
  dns-hijack:
  - any:53
  mtu: 1500
  enable: false
prepend-proxy-groups: []
external-controller-cors:
  allow-private-network: true
  allow-origins:
  - '*'
append-proxies: []
prepend-proxies: []
append-rules:
- DOMAIN-SUFFIX,bilibili.com/,DIRECT
- DOMAIN-SUFFIX,cn.bing.com/,DIRECT
- DOMAIN-SUFFIX,sicnuwiki.com/,DIRECT
- DOMAIN-SUFFIX,www.sicnuwiki.com/,DIRECT
- DOMAIN-SUFFIX,cloud.tencent.com/,DIRECT
- DOMAIN-SUFFIX,dl.acm.org/,DIRECT
- DOMAIN-SUFFIX,ieeexplore.ieee.org/,DIRECT
- DOMAIN-SUFFIX,sciencedirect.com/,DIRECT
- DOMAIN-SUFFIX,aaai.org/,DIRECT
- DOMAIN-SUFFIX,onlinelibrary.wiley.com/,DIRECT
- DOMAIN-SUFFIX,id.elsevier.com/,DIRECT
- DOMAIN-SUFFIX,geosite:steam@cn,DIRECT
- DOMAIN-SUFFIX,domain:steamserver.net,DIRECT
profile:
  store-selected: true
proxies:
- name: '[ss]剩余流量：996.58 GB'
  type: ss
  server: jsgjc.yy9866.com
  port: 45569
................此处省略................
rules:
- IP-CIDR,146.103.53.37/32,DIRECT,no-resolve
- IP-CIDR,146.103.53.36/32,DIRECT,no-resolve
- IP-CIDR,146.103.53.24/32,DIRECT,no-resolve
- IP-CIDR,82.163.16.158/32,DIRECT,no-resolve
- IP-CIDR,82.163.16.17/32,DIRECT,no-resolve
- IP-CIDR,213.218.254.184/32,DIRECT,no-resolve
- IP-CIDR,82.163.16.208/32,DIRECT,no-resolve
- IP-CIDR,82.153.65.230/32,DIRECT,no-resolve
- IP-CIDR,193.246.161.233/32,DIRECT,no-resolve
- IP-CIDR,82.163.16.63/32,DIRECT,no-resolve
- IP-CIDR,154.204.183.207/32,DIRECT,no-resolve
- IP-CIDR,89.213.184.230/32,DIRECT,no-resolve
- IP-CIDR,31.192.234.92/32,DIRECT,no-resolve
- IP-CIDR,141.11.46.27/32,DIRECT,no-resolve
- IP-CIDR,141.11.43.50/32,DIRECT,no-resolve
- IP-CIDR,50.114.55.13/32,DIRECT,no-resolve
- IP-CIDR,31.192.234.22/32,DIRECT,no-resolve
- IP-CIDR,82.152.90.187/32,DIRECT,no-resolve
- IP-CIDR,82.152.90.16/32,DIRECT,no-resolve
- IP-CIDR,83.147.15.167/32,DIRECT,no-resolve
- IP-CIDR,83.147.15.235/32,DIRECT,no-resolve
- IP-CIDR,37.128.252.147/32,DIRECT,no-resolve
```

问题是没有追加到rules里面啊，现在我自己定义的全局扩展配置，不生效。希望得到解答，谢谢！

### 软件版本 / Verge Version

V2.0.1

### 复现步骤 / To Reproduce

1. 全局扩展配置：
```

# Profile Enhancement Merge Template for Clash Verge

append-rules: [
  "DOMAIN-SUFFIX,bilibili.com/,DIRECT",
  "DOMAIN-SUFFIX,cn.bing.com/,DIRECT",
  "DOMAIN-SUFFIX,sicnuwiki.com/,DIRECT",
  "DOMAIN-SUFFIX,www.sicnuwiki.com/,DIRECT",
  "DOMAIN-SUFFIX,cloud.tencent.com/,DIRECT",
  # 文献库
  "DOMAIN-SUFFIX,dl.acm.org/,DIRECT",
  "DOMAIN-SUFFIX,ieeexplore.ieee.org/,DIRECT",
  "DOMAIN-SUFFIX,sciencedirect.com/,DIRECT",
  "DOMAIN-SUFFIX,aaai.org/,DIRECT",
  "DOMAIN-SUFFIX,onlinelibrary.wiley.com/,DIRECT",
  "DOMAIN-SUFFIX,id.elsevier.com/,DIRECT",

  #steam
  "DOMAIN-SUFFIX,geosite:steam@cn,DIRECT",
  "DOMAIN-SUFFIX,domain:steamserver.net,DIRECT"
]

prepend-proxies: []

prepend-proxy-groups: []


append-proxies: []

append-proxy-groups: []


profile:
  store-selected: true

dns:
  use-system-hosts: false


# rules:
#   # 直连
#   - DOMAIN-SUFFIX,bilibili.com/,DIRECT
#   - "DOMAIN-SUFFIX,cn.bing.com/,DIRECT"
#   - "DOMAIN-SUFFIX,sicnuwiki.com/,DIRECT"
#   - "DOMAIN-SUFFIX,cloud.tencent.com/,DIRECT"
#   # 文献库
#   - "DOMAIN-SUFFIX,dl.acm.org/,DIRECT"
#   - "DOMAIN-SUFFIX,ieeexplore.ieee.org/,DIRECT"
#   - "DOMAIN-SUFFIX,sciencedirect.com/,DIRECT"
#   - "DOMAIN-SUFFIX,aaai.org/,DIRECT"
#   - "DOMAIN-SUFFIX,onlinelibrary.wiley.com/,DIRECT"
#   - "DOMAIN-SUFFIX,id.elsevier.com/,DIRECT"
#   #steam
#   - "DOMAIN-SUFFIX,geosite:steam@cn,DIRECT"
#   - "DOMAIN-SUFFIX,domain:steamserver.net,DIRECT"
```

2. 点击左上角，**重新激活订阅**
3. **查看运行时订阅**
4. 左边栏，点击**规则**一栏，未看到规则更新，例如搜索不到我在上述添加的`cn.bing.com`

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows10 pro  version 22H2

### 日志 / Log

请看上面描述，应该比较清晰了。
