### ISSUE TITLE
[BUG] dialer-proxy链式代理不生效，网络可以连通，但ip是前置代理的。

### ISSUE THREAD

**Issue by aaqq0pp** [clash-verge-rev/clash-verge-rev#2302]
### 问题描述 / Describe the bug

按照 [https://wiki.metacubex.one/config/proxies/dialer-proxy/](https://wiki.metacubex.one/config/proxies/dialer-proxy/)中的方法配置了dialer-proxy，但是完全没有生效。可以连通，但是ip是前置代理的。

### 软件版本 / Verge Version

verge 版本 2.0.2
内核版本 Mihoyo Alpha

### 复现步骤 / To Reproduce

配置文件如下
```
port: 8880
socks-port: 8881
allow-lan: false
mode: rule
log-level: info
dns:
  enable: true
  ipv6: true
  respect-rules: true
  enhanced-mode: fake-ip
  nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  nameserver-policy:
    geosite:cn,private:
      - https://120.53.53.53/dns-query
      - https://223.5.5.5/dns-query
    geosite:geolocation-!cn:
      - https://dns.cloudflare.com/dns-query
      - https://dns.google/dns-query
proxies:
  - ss
    dialer-proxy: 链式代理
    type: ss
    server: domain1.com
    port: 10088
    cipher: aes-256-gcm
    password: mypassword
 
  - name: Chain
    type: vmess
    server: 0.0.0.0
    port: 11000
    uuid: myuuid
    alterId: 0
    cipher: auto
    tls: false
    servername: ""
    network: tcp
proxy-groups:
  - type: select
    name: 节点选择
    proxies:
...
  - type: select
    name: 链式代理
    proxies:
      - Chain

rules:
```

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

windows 11

### 日志 / Log

没有报错。日志正常连接，只是后置代理没有生效。
