### ISSUE TITLE
[BUG] 开启TUN模式后，无法将 dns 的 enhanced-mode 设置

### ISSUE THREAD

**Issue by Leskur** [clash-verge-rev/clash-verge-rev#2305]
### 问题描述 / Describe the bug

开启 TUN 模式后，无法将 `dns` 的 `enhanced-mode` 设置为 `redir-host` 

全局拓展/订阅拓展配置均无效。

### 软件版本 / Verge Version

v2.0.2

### 复现步骤 / To Reproduce

在全局拓展/订阅拓展配置均无效，配置：

```
dns:
  enhanced-mode: redir-host
```
配置后重启应用，再查看当前配置：

```
dns:
  use-system-hosts: false
  enhanced-mode: fake-ip
  enable: true
  ipv6: true
  fake-ip-range: 198.18.0.1/16
```
没有正常覆盖  `enhanced-mode`

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11

### 日志 / Log

无
