### ISSUE TITLE
[BUG] 同样的网址同样的配置，在系统代理和 TUN 模式下匹配到的规则不同

### ISSUE THREAD

**Issue by ArsenicX** [clash-verge-rev/clash-verge-rev#2308]
### 问题描述 / Describe the bug

我的配置有如下一条：
  - geosite, openai, OpenAI

在系统代理下，访问 https://chatgpt.com/ 会被命中然后走OpenAI分流；<br>
但是改成TUN模式就无法命中，会直接走MATCH

### 软件版本 / Verge Version

2.0.1

### 复现步骤 / To Reproduce

⁡ 

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Version 14.6.1 (23G93)

### 配置
```yaml
mode: rule
mixed-port: 7897
allow-lan: false
log-level: info
external-controller: 127.0.0.1:9097
secret: ""

geodata-mode: true
geox-url:
  geoip: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat
  geosite: https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat

dns:
  enable: true
  ipv6: false
  prefer-h3: true
  enhanced-mode: fake-ip
  nameserver:
    - tls://1.1.1.1:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4
    - tls://208.67.222.222
    - tls://dns.google:853
  nameserver-policy:
    ruleset:Lan:
      - tls://223.5.5.5:853
      - tls://223.6.6.6:853
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
    ruleset:Spotify:
      - tls://223.5.5.5:853
      - tls://223.6.6.6:853
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
    ruleset:ChinaMax_Classical:
      - tls://223.5.5.5:853
      - tls://223.6.6.6:853
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query

proxies:

proxy-providers:

proxy-groups:

rule-providers:


rules:
  - RULE-SET, OpenAI, OpenAI
  - geosite, openai, OpenAI
  - MATCH, PROXY

```

### TUN下：
- 日志：
> 12-06 14:08:53DEBUG
> [Rule] use default rules
> 12-06 14:08:53INFO
> [TCP] 198.18.0.1:51442(Google Chrome Helper) --> 172.64.155.209:443 match Match using PROXY[新加坡 03 | 专线]

- 连接：
> 172.64.155.209:443  PROXY / 新加坡 03 | 专线 Match Google Chrome Helper 1 分钟前

### 系统代理下：
- 日志：
> 12-06 14:14:51DEBUG
> Auth success from 127.0.0.1:51924 ->
> 12-06 14:14:51DEBUG
> Auth success from 127.0.0.1:51923 ->
> 12-06 14:14:51DEBUG
> [Rule] use default rules
> 12-06 14:14:51DEBUG
> [Rule] use default rules
> 12-06 14:14:51DEBUG
> [DNS] cache hit chatgpt.com --> [172.64.155.209 104.18.32.47] A, expire at 2024-12-06 14:15:00
> 12-06 14:14:51DEBUG
> [DNS] cache hit cdn.oaistatic.com --> [172.64.146.98 104.18.41.158] A, expire at 2024-12-06 14:17:20
> 12-06 14:14:51DEBUG
> [DNS] chatgpt.com --> 104.18.32.47
> 12-06 14:14:51DEBUG
> [DNS] cdn.oaistatic.com --> 172.64.146.98
> 12-06 14:14:51INFO
> [TCP] 127.0.0.1:51924(Google Chrome Helper) --> cdn.oaistatic.com:443 match RuleSet(OpenAI) using OpenAI[gcp]
> 12-06 14:14:51INFO
> [TCP] 127.0.0.1:51923(Google Chrome Helper) --> chatgpt.com:443 match RuleSet(OpenAI) using OpenAI[gcp]
> 12-06 14:14:51DEBUG
> Auth success from 127.0.0.1:51927 ->
> 12-06 14:14:51DEBUG
> [Rule] use default rules
> 12-06 14:14:51DEBUG
> [DNS] cache hit ab.chatgpt.com --> [172.64.155.209 104.18.32.47] A, expire at 2024-12-06 14:14:28
> 

- 连接：
> ab.chatgpt.com:443  OpenAI / gcp RuleSet(OpenAI) Google Chrome Helper 几秒前
> chatgpt.com:443 OpenAI / gcp RuleSet(OpenAI) Google Chrome Helper 几秒前
