### ISSUE TITLE
[BUG] dns 配置的  enhanced-mode 无法修改

### ISSUE THREAD

**Issue by Silvigarabis** [clash-verge-rev/clash-verge-rev#2319]
### 问题描述 / Describe the bug

我现在想要在 `dns` 配置中将  `enhanced-mode` 修改为 `redir-host`，然而无论是修改原始配置文件还是在扩展配置中添加相关配置都不起作用，在最终配置中 `dns.enhanced-mode` 始终为 `fake-ip`

### 软件版本 / Verge Version

已使用以下版本进行测试：v2.0.2、v2.0.3-alpha@b42d13f (2024-12-07 19:50) 

### 复现步骤 / To Reproduce

- 创建一份配置并合入以下配置：
```yaml
dns:
  enable: true
  ipv6: true
  default-nameserver:
  - 223.5.5.5
  - 223.6.6.6
  enhanced-mode: redir-host
  use-system-hosts: true
  nameserver:
  - 223.5.5.5
  - 223.6.6.6
  fallback:
  - 1.1.1.1
  fallback-filter:
    geoip: true
    geoip-code: CN
```
- 在Verge设置里开启IPv6
- 确认配置文件没有问题，在Verge中查看当前配置，中的 dns 部分，结果为：
```yaml
dns:
  enable: true
  ipv6: true
  default-nameserver:
  - 223.5.5.5
  - 223.6.6.6
  enhanced-mode: fake-ip
  use-system-hosts: true
  nameserver:
  - 223.5.5.5
  - 223.6.6.6
  fallback:
  - 1.1.1.1
  fallback-filter:
    geoip: true
    geoip-code: CN
  fake-ip-range: 198.18.0.1/16
```
- 在 cmd 中使用 `nslookup` 对域名进行解析，结果返回错误IP
```
C:\>nslookup baidu.com
服务器:  UnKnown
Address:  fdfe:dcba:9876::2

名称:    baidu.com
Address:  198.18.0.12


C:\>nslookup google.com
服务器:  UnKnown
Address:  fdfe:dcba:9876::2

名称:    google.com
Address:  198.18.0.50


C:\>nslookup ipv6.baidu.com
服务器:  UnKnown
Address:  fdfe:dcba:9876::2

名称:    ipv6.baidu.com
Address:  198.18.0.14


C:\>nslookup ipv6.testipv6.cn
服务器:  UnKnown
Address:  fdfe:dcba:9876::2

名称:    ipv6.testipv6.cn
Address:  198.18.0.16
```

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

WIndows 10 专业版

### 日志 / Log

（暂时没有在日志目录里找到有关的日志，如有需要，可要求我上传完整日志）
