### ISSUE TITLE
[BUG] `dns.enhanced-mode` 在开启 tun 模式时被固定为 `fake-ip`

### ISSUE THREAD

**Issue by Silvigarabis** [clash-verge-rev/clash-verge-rev#2325]
### 问题描述 / Describe the bug

我现在想要在 dns 配置中将 enhanced-mode 修改为 redir-host，同时启用 tun 模式。然而无论是修改原始配置文件，还是在扩展配置中添加相关配置都不起作用，在最终配置中 `dns.enhanced-mode` 始终为 `fake-ip`。

### 软件版本 / Verge Version

v2.0.3-alpha@b42d13f (2024-12-07 19:50)

### 复现步骤 / To Reproduce

1. 使用以下配置：
```yaml
mode: global
dns:
  enable: true
  default-nameserver:
  - 223.5.5.5
  - 223.6.6.6
  enhanced-mode: redir-host
  nameserver:
  - 223.5.5.5
  - 223.6.6.6
  fallback:
  - 1.1.1.1
  fallback-filter:
    geoip: true
    geoip-code: CN
rules:
  - MATCH,DIRECT
```
2. 使用上述配置时，分别查看在Verge设置中启用与禁用tun模式时的“当前配置”，发现tun模式开启时`dns.enhanced-mode`始终为`fake-ip`，未开启时则与原始配置中的设定一致
- tun模式开启时的当前配置
```yaml
mode: rule
mixed-port: 2080
allow-lan: true
log-level: info
ipv6: true
external-controller: 127.0.0.1:9097
secret: ''
unified-delay: true
dns:
  enable: true
  default-nameserver:
  - 223.5.5.5
  - 223.6.6.6
  enhanced-mode: fake-ip
  nameserver:
  - 223.5.5.5
  - 223.6.6.6
  fallback:
  - 1.1.1.1
  fallback-filter:
    geoip: true
    geoip-code: CN
  ipv6: true
  fake-ip-range: 172.29.0.1/16
external-controller-cors:
  allow-private-network: true
  allow-origins:
  - '*'
profile:
  store-selected: true
tun:
  auto-detect-interface: true
  auto-route: true
  device: Mihomo
  dns-hijack:
  - any:53
  mtu: 1500
  stack: mixed
  strict-route: true
  enable: true
proxies: []
proxy-groups: []
rules:
- MATCH,DIRECT
```
- tun模式关闭时的当前配置
```yaml
mode: rule
mixed-port: 2080
allow-lan: true
log-level: info
ipv6: true
external-controller: 127.0.0.1:9097
secret: ''
unified-delay: true
external-controller-cors:
  allow-private-network: true
  allow-origins:
  - '*'
dns:
  enable: true
  default-nameserver:
  - 223.5.5.5
  - 223.6.6.6
  enhanced-mode: redir-host
  nameserver:
  - 223.5.5.5
  - 223.6.6.6
  fallback:
  - 1.1.1.1
  fallback-filter:
    geoip: true
    geoip-code: CN
  ipv6: true
  fake-ip-range: 172.29.0.1/16
tun:
  auto-detect-interface: true
  auto-route: true
  device: Mihomo
  dns-hijack:
  - any:53
  mtu: 1500
  stack: mixed
  strict-route: true
  enable: false
profile:
  store-selected: true
proxies: []
proxy-groups: []
rules:
- MATCH,DIRECT
```
3. 在当前配置中的`dns.enhanced-mode`为`fake-ip`时，在 cmd 中使用 nslookup 对域名进行解析，结果返回错误IP（或者说返回非真实结果），反之返回真实结果
- 返回的虚假结果示例
```
C:\>nslookup ipv6.baidu.com
服务器:  UnKnown
Address:  fdfe:dcba:9876::2

名称:    ipv6.baidu.com
Address:  172.29.0.15


C:\>nslookup bing.com
服务器:  UnKnown
Address:  fdfe:dcba:9876::2

名称:    bing.com
Address:  172.29.0.20
```
- 返回的真实结果示例
```
C:\>nslookup ipv6.baidu.com
服务器:  UnKnown
Address:  192.168.6.23

非权威应答:
名称:    www.a.shifen.com
Addresses:  2409:8c54:870:67:0:ff:b0c2:ad75
          2409:8c54:870:34e:0:ff:b024:1916
          183.240.98.161
          183.240.98.198
Aliases:  ipv6.baidu.com


C:\>nslookup bing.com
服务器:  UnKnown
Address:  192.168.6.23

非权威应答:
名称:    bing.com
Addresses:  2620:1ec:c11::200
          13.107.21.200
          204.79.197.200
```

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

WIndows 10 22H2 (Windows 10 专业版)

### 日志 / Log

（暂时没有在日志目录里找到有关的日志，如有需要，可要求我上传完整日志）

**Comment by Sharm** [comment]
Confirmed. It was broken since 2.x.x version, 1.7.7 was okay with redir-host.

**Comment by frankYoY** [comment]
2.0之后，这部分内容会被强制覆写，就是这样设计的，并非bug

**Comment by Silvigarabis** [comment]
> 2.0之后，这部分内容会被强制覆写，就是这样设计的，并非bug

对于这个设计，我有两个问题：
- 这是为了让Verge生成的配置有更加固定的表现吗？
- 如果是的话，Verge是否会在之后在设置UI中添加切换该配置的选项？

**Comment by Silvigarabis** [comment]
> But you could use `fake-ip-filter-mode: whitelist` as a workaroud

Thank you! It's working just like `redir-host` mode again!

**Comment by Tychristine** [comment]
@Silvigarabis 
Tun配置是一个关键的配置，配置不好它就不能正常工作。
`CVR` 如此设计为了避免小白用户：不会配置，乱配置等等产生的一系列问题。
> 使用Clash的大部分用户都是小白用户，就只会下载订阅打开系统代理的    

如此说法，毫不过分

**Comment by Hugo7650** [comment]
> 只会下载订阅打开系统代理的

你都说了小白只会这样 又说避免小白乱配置 这不是前后矛盾么

退一步说界面里不能直接改 那为什么用扩展配置也不让改

**Comment by Tychristine** [comment]
@Hugo7650 并不矛盾，小白玩家会用服务商提供的，但服务商也写不好。我在群里见过很多连抄配置都抄不明白的。
CVR这样处理又有什么不妥呢，tun下使用fake-ip有不错的性能。又能避免其它程序解析不到主机导致的无限重发请求崩溃自身的问题。
GUI工具不就是为了达成易用，实用，开箱即用clash这些目的吗
有特殊需求的可以自行fork仓库去编译.

**Comment by Silvigarabis** [comment]
目前来看，这个问题不是“错误编写”导致的，而是“有意而为”。
也许这个issue就到这里了。其他的问题，我认为可以在讨论区中再作探讨？

**Comment by Anz-03** [comment]
主要是有些网站只能内网访问，你改了 dns 就不能内网 DNS 解析了

**Comment by Tychristine** [comment]
@Anz-03 可以的，自己看常见问题里面

**Comment by Anz-03** [comment]
> @Anz-03 可以的，自己看常见问题里面

刚刚看了一下，你们这个是根据域名来的。可是我这里的问题是，内网和外网访问同一个网址，界面不一样，而且我两个都要用。可不可以不要修改我的 dns，每次都要手动改回来。

**Comment by Silvigarabis** [comment]
附加如下配置应该可以解决上述问题
```yaml
dns:
  fake-ip-filter:
    - myhome.super.ltd
  fake-ip-filter-mode: blacklist
```
其中`dns.fake-ip-filter`中的项目需要自己修改

**Comment by sam-jetthaisoft** [comment]
我只是想要開tun 然後 dns 走我的 adguard home.....

**Comment by Hades-001** [comment]
碰到同样的问题了，2.0以后的版本都这样，退回1.7.7了。

**Comment by akdriver** [comment]
Same issue！

**Comment by Silvigarabis** [comment]
那我就总结一下：

如果你只是特定域名需要在 tun 模式下能获得真实的解析结果，可以将参照以下配置，对你的配置进行拓展：
If you only need to obtain real resolution results for a specific domain name in tun mode, you can refer to the following configuration to expand your configuration:
```yaml
dns:
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - some.domain.tld
    - "*.thisdomain.com"
    # and more here
```

如果需要还能获得与原先`dns.enhanced-mode = redir-host`一致的效果，可以试着附加这样的配置：
If you need to get the same effect as the original `dns.enhanced-mode = redir-host`, you can try to add the following configuration:
```yaml
dns:
  fake-ip-filter-mode: whitelist
  fake-ip-filter: []
```

以上配置仅供参考，作为一种可选的解决方案。或者，回退到1.x版本。
The above configuration is for reference only and is an optional solution. Alternatively, you can roll back to version 1.x.
