### ISSUE TITLE
[BUG] 无法在TUN模式下忽略(绕过)不想通过VPN的网站, TUN模式下没有代理绕过设置

### ISSUE THREAD

**Issue by Barmaid1076** [clash-verge-rev/clash-verge-rev#2330]
### 问题描述 / Describe the bug

无法在TUN模式下忽略(绕过)不想通过VPN的网站, TUN模式下没有系统代理下差不多的代理绕过设置

![image](https://github.com/user-attachments/assets/4582e7bd-e11b-4aa8-8b66-5112dab440d9)

### 软件版本 / Verge Version

Latest

### 复现步骤 / To Reproduce

w

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 10

### 日志 / Log

a

**Comment by Tychristine** [comment]
https://wiki.metacubex.one/config/rules/

**Comment by Barmaid1076** [comment]
尝试了在config.yaml之中添加以下内容, 仍然无法在tun模式下访问 test.com

```yaml
tun:
  auto-detect-interface: true
  auto-route: true
  device: Mihomo
  dns-hijack:
  - any:53
  mtu: 1500
  stack: gvisor
  strict-route: false
  bypass:
  - test.com
```

以及

```
rules:
  - DOMAIN,test.com,DIRECT
  - DOMAIN-SUFFIX,test.com,DIRECT
  - DOMAIN,test.com,PASS
```
 
三者中的其中一个
