### ISSUE TITLE
[BUG] mac电脑上相同的代理配置， edge可以访问目标网络，但是safari和其他软件无法访问

### ISSUE THREAD

**Issue by xcstatus** [clash-verge-rev/clash-verge-rev#2349]
### 问题描述 / Describe the bug

想要将192.168.88.0/24 路由到192.168.1.233， 同时192.168.1.233通过netbird(wireguard软件)进行代理，所以在233出栈代理中指定了interface-name为netbird对应的接口名称。

通过一下配置， 在mac电脑上通过edge浏览器可以正常访问192.168.88.0/24， 但是safari浏览器和其他软件无法正常访问192.168.88.0/24.

当代理组netbird-dialer 选择netbird-direct时 edge可以访问目标网段， 选择DIRECT无法访问目标网段。通过这种方式确认了edge确实是走了clash verge的代理。

```
proxies:
- type: socks5
  name:  233
  server: 192.168.1.233
  port: 1081
  dialer-proxy: netbird-dialer
- name: netbird-direct
  type: direct
  udp: true
  interface-name: utun100
  ip-version: ipv4
 proxy-groups:
  - name: 'netbird-dialer'
    type: 'select'
    proxies:
      - 'netbird-direct'
      - 'DIRECT'
```
### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

节点中指定interface-name， edge和safari浏览器分别请求目标网段

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.1.1

### 日志 / Log

使用safari浏览器访问时，内核日志中输出超时. 但是edge浏览器访问时，内核日志中没有任何相关信息输入，成功信息也没有。

time="2024-12-10T22:56:07.867584+08:00" level=warning msg="[TCP] dial 233 (match IPCIDR/192.168.88.0/24) 198.18.0.1:53930 --> 192.168.88.23:80 error: connect failed: dial tcp 192.168.88.23:80: i/o timeout"
time="2024-12-10T22:56:07.867765+08:00" level=warning msg="[TCP] dial 233 (match IPCIDR/192.168.88.0/24) 198.18.0.1:53935 --> 192.168.88.23:80 error: connect failed: dial tcp 192.168.88.23:80: i/o timeout"
time="2024-12-10T22:56:07.88223+08:00" level=debug msg="[Rule] use default rules"
time="2024-12-10T22:56:07.883513+08:00" level=debug msg="[Rule] use default rules"
time="2024-12-10T22:56:12.883467+08:00" level=warning msg="[TCP] dial 233 (match IPCIDR/192.168.88.0/24) 198.18.0.1:53969 --> 192.168.88.23:80 error: connect failed: dial tcp 192.168.88.23:80: i/o timeout"
time="2024-12-10T22:56:12.8836+08:00" level=warning msg="[TCP] dial 233 (match IPCIDR/192.168.88.0/24) 198.18.0.1:53970 --> 192.168.88.23:80 error: connect failed: dial tcp 192.168.88.23:80: i/o timeout"
time="2024-12-10T22:56:12.894802+08:00" level=debug msg="[Rule] use default rules"
time="2024-12-10T22:56:12.996464+08:00" level=debug msg="[Rule] use default rules"
time="2024-12-10T22:56:12.998878+08:00" level=debug msg="[Rule] use default rules"
time="2024-12-10T22:56:17.89978+08:00" level=warning msg="[TCP] dial 233 (match IPCIDR/192.168.88.0/24) 198.18.0.1:53991 --> 192.168.88.23:80 error: connect failed: dial tcp 192.168.88.23:80: i/o timeout"
time="2024-12-10T22:56:17.915926+08:00" level=debug msg="[Rule] use default rules"
time="2024-12-10T22:56:17.997004+08:00" level=warning msg="[TCP] dial 233 (match IPCIDR/192.168.88.0/24) 198.18.0.1:53997 --> 192.168.88.23:80 error: connect failed: dial tcp 192.168.88.23:80: i/o timeout"
time="2024-12-10T22:56:17.999343+08:00" level=warning msg="[TCP] dial 233 (match IPCIDR/192.168.88.0/24) 198.18.0.1:53998 --> 192.168.88.23:80 error: connect failed: dial tcp 192.168.88.23:80: i/o timeout"
