### ISSUE TITLE
[BUG] WireGuard 配置好, url-test 通过, 但无法连接

### ISSUE THREAD

**Issue by RoJoHub** [clash-verge-rev/clash-verge-rev#2364]
##  问题描述
大家好, 我使用 Clash Verge  根据WireGuard 文件配置了 yaml

然而我遇到了 Clash 显示 连接成功, 但是实际使用不成
-  ping 192.168.50.1 失败
-  ping 10.6.0.0/32 成功  (好像是假的?)
- Chrome 访问 192.168.50.1 失败

### 软件版本 / Verge Version

- 内核版本: v1.19 Mihimo
- Verge 版本 v2.0.2
![image](https://github.com/user-attachments/assets/fa9a89f6-3c7d-4c02-8ddb-a97f3aa5469f)

## WireGuard 配置文件
```
[Interface]
PrivateKey = xb
Address = 10.6.0.2/32
DNS = 10.6.0.1

[Peer]
PublicKey = xa
AllowedIPs = 10.6.0.0/24, 192.168.50.0/24
Endpoint = xxx.asuscomm.cn:51820
PersistentKeepalive = 25

```

---

## 转换后使用的 yaml 文件
```
proxies:
  - {name: 家庭路由WireGuard线路, server: xxx.asuscomm.cn, port: 51820, type: wireguard, ip: 10.6.0.2, private-key: xb, public-key: xa, dns-server: 10.6.0.1, mtu: 1420, udp: true, persistent-keepalive: 25}
proxy-groups:
  - name: 家庭路由节点
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 家庭路由WireGuard线路
  - name: 家庭局域网
    type: select
    proxies:
      - 家庭路由节点
rules:
  - IP-CIDR,192.168.50.0/24,家庭局域网
  - IP-CIDR,10.6.0.0/24,家庭局域网
  - GEOIP,CN,DIRECT
  - MATCH,DIRECT
```
![image](https://github.com/user-attachments/assets/c58511b9-40c7-4a77-a45d-9cf3fc70fa00)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

macOS/15.1.1 (24B91)

### 日志 / Log

[2024-12-12-1507.log](https://github.com/user-attachments/files/18107021/2024-12-12-1507.log)

**Comment by RoJoHub** [comment]
尝试以下配置也是无法访问
```
proxies:
- name: "家庭路由WireGuard线路"
  type: wireguard
  ip: 10.6.0.2
  private-key: xb
  peers:
    - server: xxx.asuscomm.cn
      port: 51820
      public-key: xa
      allowed-ips: ['0.0.0.0/0']     # 分流由clash处理
  udp: true
  remote-dns-resolve: true    # 按需设置，不用直接删除
  dns: [10.6.0.1]             # 按需设置，不用直接删除
proxy-groups:
  - name: 家庭路由节点
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 家庭路由WireGuard线路
  - name: 家庭局域网
    type: select
    proxies:
      - 家庭路由节点
rules:
  - IP-CIDR,192.168.50.0/24,家庭局域网
  - IP-CIDR,10.6.0.0/24,家庭局域网
  - GEOIP,CN,DIRECT
  - MATCH,DIRECT
```
