### ISSUE TITLE
[BUG] DNS解析错误，i/o超时

### ISSUE THREAD

**Issue by how1ewu** [clash-verge-rev/clash-verge-rev#241]
### Describe the bug

出现了大量的dns解析错误，特别是直连和国内节点，境外节点倒是没什么问题。日志一般为：error: dns resolve failed: lookupXXX: i/o timeout，例如：
```yaml
 [TCP] dial 🗺️ 全球直连 (match DomainSuffix/qq.com) 127.0.0.1:59854(SogouInput) --> ios.rqd.qq.com:443 error: dns resolve failed: lookup ios.rqd.qq.com: i/o timeout
```
我的配置文件如下：
```yaml
port: 7890
socks-port: 7891
mixed-port: 7892
redir-port: 7893
tproxy-port: 7894
allow-lan: false
bind-address: "*"
ipv6: true
external-controller: 127.0.0.1:9090
mode: rule
log-level: info
dns:
  enabled: true
  ipv6: true
  default-nameserver:
    - 223.5.5.5
    - 8.8.8.8
    - 119.29.29.29
    - 180.184.1.1
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 180.184.1.1
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.8.8
    - https://1.1.1.1/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite: 
      - gfw
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"
      - "+.githubusercontent.com"
      - "+.googlevideo.com"
      - "+.msftconnecttest.com"
      - "+.msftncsi.com"
```

### To Reproduce

访问直连网络例如baidu.com

### Platform

MacOS

### System Version

macOS 14.2.1

### Software Version

1.4.8
