### ISSUE TITLE
[BUG] 忽略这些主机和域的代理设置 dns部分没生效

### ISSUE THREAD

**Issue by oscarthecat** [clash-verge-rev/clash-verge-rev#2442]
### 问题描述 / Describe the bug

首先，非常感谢clash verge的开发大佬们，我周围大量同事都换到clash verge了

我这里也有一个dns相关的问题，比如在公司内部有
域名： *.xyz.co
私有dns： 10.10.23.249
公司内部的所有私有域名肯定只能从公司私有dns解析出来

我用的是2.0.2 的clashverge，macos15.2，arm芯片。

在 网络中 忽略这些主机和域的代理设置 已经增加了 .xyz.co
127.0.0.1,(省略中间默认值),.xyz.co
但是发现实际请求的时候，*.xyz.co 并不会用私有的dns，从clash verge的日志来看直接上报dns解析失败。

我可以在什么地方配置吗？chatgpt说可以配置dns，但是我发现好像所有配置都是从线上拉下来的。有什么好的办法吗？或者我什么地方理解错了或者配置错了吗？感谢大佬！

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

在macos 网络，代理中进行配置特定域名不走代理

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.2

### 日志 / Log

(待补充

**Comment by Tychristine** [comment]
```yaml
dns: 
  enable: true
  nameserver-policy: 
    '+.xyz.co':'10.10.23.249'
```
