### ISSUE TITLE
[BUG] 引入rule-providers报错，failed to put configs with status "400"

### ISSUE THREAD

**Issue by wind0ta** [clash-verge-rev/clash-verge-rev#2500]
### 问题描述 / Describe the bug

加入以下规则就会报错，应该如何调试。。。
完整配置文件附在后面。
rules: 
  - RULE-SET,gfw,PROXY

### 软件版本 / Verge Version

2.0.2

### 复现步骤 / To Reproduce

# Profile Template for Clash Verge

proxies:
  - name: "Hysteria2-Proxy"
    type: hysteria2
    server: xx.xx.xx.xx
    ports: 20000-50000
    password: xxxxxxxx
    up: "30 Mbps"
    down: "30 Mbps"
    sni: example.com
    skip-cert-verify: false
    alpn:
      - h3
    hop-interval: 30

proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - "Hysteria2-Proxy"
      - DIRECT
      - REJECT

rule-providers:
  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

rules: 
  - RULE-SET,gfw,PROXY
  - MATCH,DIRECT

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

failed to put configs with status "400"

**Comment by Tychristine** [comment]
配置有语法错误

### 正确示例
```yaml
rule-providers:
  gfw:
    type: http
    behavior: domain
    format: yaml
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./rule/gfw.txt
    interval: 43200
```
