### ISSUE TITLE
[BUG] 配置中存在global代理组时会导致代理组被重新排序

### ISSUE THREAD

**Issue by AdySnowflake** [clash-verge-rev/clash-verge-rev#2566]
### 问题描述 / Describe the bug

配置文件中存在global代理组时：
![image](https://github.com/user-attachments/assets/d392ce3b-9696-4a8f-a8ff-ce860fd5ddd7)
软件内显示的代理组按照名称顺序被重新排列：
![image](https://github.com/user-attachments/assets/e0139de7-86e0-4341-aa89-17c4ca6920ba)
换用mihomo party则无此问题，因此推测是cvr而非内核问题。

### 软件版本 / Verge Version

v2.0.3

### 复现步骤 / To Reproduce

有如下配置：
``` yaml
proxy-groups:  
  - name: dgroup位置1
    type: select
    proxies:
      - DIRECT
  
  - name: egroup位置2
    type: select
    proxies:
      - DIRECT

  - name: agroup位置3
    type: select
    proxies:
      - DIRECT
  
  - name: bgroup位置4
    type: select
    proxies:
      - DIRECT
  
  - name: cgroup位置5
    type: select
    proxies:
      - DIRECT
```
此时代理组顺序正常，符合配置文件的顺序：
![image](https://github.com/user-attachments/assets/c36d56f2-9da9-4b23-85b1-b8e6a1a115a8)
添加global代理组后：
``` yaml
proxy-groups:
  - name: GLOBAL
    type: select
    proxies:
      - DIRECT
  
  - name: dgroup位置1
    type: select
    proxies:
      - DIRECT
  
  - name: egroup位置2
    type: select
    proxies:
      - DIRECT

  - name: agroup位置3
    type: select
    proxies:
      - DIRECT
  
  - name: bgroup位置4
    type: select
    proxies:
      - DIRECT
  
  - name: cgroup位置5
    type: select
    proxies:
      - DIRECT
```
软件内显示的代理组顺序发生了改变，似乎是按照名称顺序进行了重排序：
![image](https://github.com/user-attachments/assets/9f011817-9a8a-4f7e-8164-997f667037d5)

global代理组插入proxygroup的顺序不影响复现结果，无论是插入到第一个还是放到最后一个。
按照mihomo内核文档 (https://wiki.metacubex.one/config/proxy-groups/built-in/#global) 描述的，可以在配置文件中自定义global代理组，因此这个操作应该是合法的。
换用mihomo party则无此问题，因此推测是cvr而非内核问题。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11 24H2

### 日志 / Log

无
