### ISSUE TITLE
[BUG] TUN模式下DNS非常非常慢

### ISSUE THREAD

**Issue by liyafe1997** [clash-verge-rev/clash-verge-rev#2642]
### 问题描述 / Describe the bug

开启了TUN以后，DNS非常非常慢，大概每个域名需要数秒才能解析成功，就算是DNS走代理也不会这么慢。
```yaml
dns:
  use-system-hosts: false
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 172.29.0.1/16
profile:
  store-selected: true
tun:
  auto-detect-interface: true
  auto-route: true
  device: Mihomo
  dns-hijack:
  - any:53
  mtu: 1500
  stack: mixed
  strict-route: true
  enable: true
```

### 软件版本 / Verge Version

V2.0.3

### 复现步骤 / To Reproduce

开启TUN

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Win11 23H2 22631.4830

### 日志 / Log

看了下日志，无有意义线索
