### ISSUE TITLE
[BUG] 代理页面空白，订阅丢失

### ISSUE THREAD

**Issue by YiiGuxing** [clash-verge-rev/clash-verge-rev#2677]
### 问题描述 / Describe the bug

每使用一段时间后就会出现问题：
1. 代理页面空白
2. 订阅丢失
3. 删除配置目录后恢复

<img width="679" alt="Image" src="https://github.com/user-attachments/assets/95e97c88-778f-4daf-a70b-d46029925193" />

### 软件版本 / Verge Version

2.0.3

### 复现步骤 / To Reproduce

每使用一段时间后就会出现问题。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

`logs\service` 下的日志：
```
time="2025-02-11T09:01:01.271485400+08:00" level=fatal msg="Parse config error: yaml: line 34: could not find expected ':'"
```

## 出现问题的配置文件

`clash-verge.yaml`
```
# Generated by Clash Verge

mode: rule
mixed-port: 7897
allow-lan: false
log-level: info
external-controller: 127.0.0.1:9097
secret: ''
unified-delay: true
external-controller-cors:
  allow-private-network: true
  allow-origins:
  - '*'
dns:
  use-system-hosts: false
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  fake-ip-range: 172.29.0.1/16
profile:
  store-selected: true
tun:
  enable: false
  stack: mixed
  auto-route: true
  strict-route: false
  auto-detect-interface: true
  dns-hijack:
  - any:53
proxies: []
proxy-groups: []
rules: []

https://dns.google/dns-query               #======问题出现在此处============
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
    - 127.0.0.1/32
    domain:

#...
```

`clash-verge-check.yaml`
```
# Generated by Clash Verge

mode: rule
mixed-port: 7897
allow-lan: false
log-level: debug
external-controller: 127.0.0.1:9097
secret: ''
unified-delay: true
profile:
  store-selected: true
tun:
  enable: false
  stack: mixed
  auto-route: true
  strict-route: false
  auto-detect-interface: true
  dns-hijack:
  - any:53
external-controller-cors:
  allow-private-network: true
  allow-origins:
  - '*'
dns:
  use-system-hosts: false
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  fake-ip-range: 172.29.0.1/16
proxies: []
proxy-groups: []
rules: []
loudflare-dns.com/dns-query                        #======问题出现在此处============
  - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
    - 127.0.0.1/32
    domain:
```
