### ISSUE TITLE
通过 proxy-providers 导入的订阅中的 hysteria2 节点默认被过滤

### ISSUE THREAD

**Issue by chuwza** [clash-verge-rev/clash-verge-rev#2706]
大佬好，我有一个机场，含有hysteria2节点，单独订阅这个机场，hysteria2节点会显示。

但是问题来了，我实际使用是多个机场，自己写配置文件。多个机场使用`proxy-providers:`订阅，然后在`proxy-groups`代理组中使用`use`来聚合使用。
```
  机场1: 
    type: http
    path: ./proxy/1.yaml
    url: "隐去"
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600

  - name: "Global"
    type: select
    use:
      - 机场1
      - 机场2 
```
然后hysteria2节点就被默认过滤掉了，这是怎么回事？

<img width="259" alt="Image" src="https://github.com/user-attachments/assets/9a64bbf5-c36a-4b19-9edf-8a4e2b418b94" />

我看讨论里有人提到过这个问题 #2204 

有人知道怎么解决吗？

**Comment by Tychristine** [comment]
```yaml
mixed-port: 7890
redir-port: 7891
tproxy-port: 1536
allow-lan: true
mode: rule
global-ua: clash-verge/v2.0.4
```

https://www.clashverge.dev/faq/other.html#proxy-providers-hy2
