### ISSUE TITLE
[BUG] 自定义主题添加背景图片后，软件边框有白边

### ISSUE THREAD

**Issue by AdySnowflake** [clash-verge-rev/clash-verge-rev#2768]
### 问题描述 / Describe the bug

自定义主题注入CSS后，软件边框有白边。v2.0.3正常

![Image](https://github.com/user-attachments/assets/33233b76-9aae-4ff2-8f3f-2ed148b1b198)

### 软件版本 / Verge Version

2.1.0

### 复现步骤 / To Reproduce

注入CSS
```css
.css-b0lzb7{
    background-image: url('https://example.png') !important;
}
```
打开软件主界面，可以看到白边。

![Image](https://github.com/user-attachments/assets/46206a8d-b06c-4eed-a66c-5870c3756373)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11 24H2

### 日志 / Log

无
