### ISSUE TITLE
[BUG] v2.1.2版本的TUN模式下，dns设置为纯redir-host会断网！

### ISSUE THREAD

**Issue by SavooyT** [clash-verge-rev/clash-verge-rev#2852]
### 问题描述 / Describe the bug

开启`TUN`模式（无论是在`gvisor`还是`system`还是`mixed`情形下），在`profile`中，`dns`模块里，设置`enhanced-model: redir-host`，就会直接断网。

如果把`enhanced-mode: redir-host`直接注释掉或者删掉就能恢复上网。

`fake-ip`模式无此问题，可正常上网。

**ps：非常容易复现！（无论是否为alpha版本的内核）**

### 软件版本 / Verge Version

客户端：Clash Verge Rev v2.1.2 （**在之前2.0.3版本未出现此问题**）

内核：alpha-05e8f13 Mihomo

### 复现步骤 / To Reproduce

`profile`完整配置（**已去除隐私信息**）：

```
mode: rule
profile:
  store-selected: true
tcp-concurrent: true
find-process-mode: strict
experimental:
  quic-go-disable-gso: false
  quic-go-disable-ecn: false

dns:
  enabled: true
  use-system-hosts: false
  prefer-h3: true 
  #--------------------↓↓↓出问题的地方↓↓↓--------------------#
  enhanced-mode: redir-host 
  # 一旦这里的 enhanced-mode 直接设置为 redir-host 模式，就无法上网了，fake-ip 模式不影响。
  # 但是哪怕把这里的 enhanced-mode: redir-host 直接注释掉或者删掉都能恢复上网。
  #--------------------↑↑↑出问题的地方↑↑↑--------------------#
  nameserver:
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query

proxies: # 自建节点
  - {name: 🇸🇬（WAP）Singapore🔗, server: 666.666.666.666, port: 23333, type: ss, cipher: aes-128-gcm, password: 23333, udp: true, dialer-proxy: 🇭🇰 Hong Kong G1}

# 自动测速通用配置（引用模式，下面有类似写法，不再赘述）
URLTEST: &URLTEST
  type: url-test
  url: 'http://www.apple.com/library/test/success.html'
  interval: 600
  tolerance: 5
# 代理组
proxy-groups:
  - name: 🇸🇬（WAP）Singapore
    type: select
    proxies:
      - 🇸🇬（WAP）Singapore🔗
  - name: 🇭🇰 Hong Kong G2
    <<: *URLTEST
    use:
      - CLOUD_HK_2
  - name: 🇭🇰 Hong Kong G1
    <<: *URLTEST
    use:
      - CLOUD_HK_1
  - name: 🇸🇬 Singapore
    <<: *URLTEST
    use: 
      - CLOUD_SG
  - name: 🇯🇵 Japan
    <<: *URLTEST
    use:
      - CLOUD_JP
  - name: 🇺🇸 United States
    <<: *URLTEST
    use:
      - CLOUD_US
  - name: 🇹🇼 Taiwan
    <<: *URLTEST
    use:
      - CLOUD_TW
  - name: 🇬🇧 United Kingdom
    <<: *URLTEST
    use:
      - CLOUD_UK
  - name: 🇩🇪 Germany
    <<: *URLTEST
    use:
      - CLOUD_DE   

CLOUD: &CLOUD 
  type: http
  url: "https://myCloudLink.com"
  interval: 3600
  proxy: DIRECT 
  health-check:
    enable: true
    interval: 600 
    url: https://cp.cloudflare.com   
# 机场远程配置
proxy-providers:
  CLOUD_HK_1: 
    <<: *CLOUD 
    filter: 🇭🇰 Hong Kong 0[1-5]\b
  CLOUD_HK_2: 
    <<: *CLOUD   
    filter: 🇭🇰 Hong Kong 0[6-9]|10\b
  CLOUD_SG: 
    <<: *CLOUD 
    filter: 🇸🇬 Singapore
  CLOUD_JP: 
    <<: *CLOUD 
    filter: 🇯🇵 Japan  
  CLOUD_US: 
    <<: *CLOUD 
    filter: 🇺🇸 United States    
  CLOUD_TW:
    <<: *CLOUD 
    filter: Taiwan | 🇹🇼   
  CLOUD_UK: 
    <<: *CLOUD 
    filter: 🇬🇧 United Kingdom
  CLOUD_DE: 
    <<: *CLOUD 
    filter: 🇩🇪 Germany

# 远程规则集
rule-providers: 
  ...
# 路由规则
rules: 
  ...
```

BUG的阐述已经在【**问题描述 / Describe the bug**】一节说得很清楚了，因此这里不再重复赘述。

除此之外，我还发现一个比较神奇的事情，如果我在`dns`里面设置了`enhanced-mode: redir-host`，那么如下图一和图二所示，配置会变成`redir-host`（图2第34行）：

![Image](https://github.com/user-attachments/assets/11c1996d-272c-444c-9e88-f8996e945871)
![Image](https://github.com/user-attachments/assets/abc976cf-72f1-488c-bfa9-eb70f5484c4a)

但是如果我在如果我在`dns`里面注释或者删除掉`enhanced-mode: redir-host`，那么再沿用刚刚提到的路径打开配置，`dns`中的相关区域会变成`fake-ip`，如下图三和图四所示：

![Image](https://github.com/user-attachments/assets/308906bc-be0a-43d2-bd0f-1a1374e9535f)
![Image](https://github.com/user-attachments/assets/e1679cd6-6eb9-4fdf-8ff2-0f6af210aa6a)

也就是说，实际上如果不设置`enhanced-mode`，那么`Clash Verge Rev v2.1.2`在`TUN`模式下实际会遵从`fake-ip`模式，而非`Mihomo`中所提到的[默认redir-host](https://wiki.metacubex.one/config/dns/#listen)【详情可见下图五】

![Image](https://github.com/user-attachments/assets/b24e902a-50f2-412b-8359-bc8fc8be81f3)

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11 beta 22635.5015

### 系统标签 / OS Labels

- [x] windows
- [ ] macos
- [ ] linux

### 日志 / Log

[Log.txt](https://github.com/user-attachments/files/19043164/Log.txt)
