### ISSUE TITLE
[BUG] Rules for "Tun(udp)" are not working

### ISSUE THREAD

**Issue by iliya-pro** [clash-verge-rev/clash-verge-rev#2873]
### 问题描述 / Describe the bug

I have the following settings in Global Extend Config:

```
profile:
  store-selected: true

dns:
  use-system-hosts: false

rules:
  - GEOIP,ru,DIRECT
  - GEOIP,telegram,DIRECT
  - GEOSITE,telegram,DIRECT
  - GEOSITE,apple,DIRECT
  - GEOSITE,apple-ads,DIRECT
  - GEOSITE,apple-dev,DIRECT
  - GEOSITE,apple-pki,DIRECT
  - GEOSITE,apple-update,DIRECT
  - GEOSITE,twitch,DIRECT
  - NETWORK,udp,🔥 Auto(Best ping)  # added to fix an issue, but didn't work
  - MATCH,🔥 Auto(Best ping)
```

![Image](https://github.com/user-attachments/assets/6666d3d8-de74-4926-ade2-96cd86b68f2a)

But every time I see "Tun(udp)" type in Connections table, there is no rule selected, and there is DIRECT connection used.

![Image](https://github.com/user-attachments/assets/61871d09-b5f8-4ebe-a361-c9db6af4b190)

Trying to fix this, I've added:

```
- NETWORK,udp,🔥 Auto(Best ping)
```

but this didn't help at all. Looks like it's completely ignored.

Sometimes, extremely rarely, a correct rule is used for some UDP connections, but it's like winning a lottery. Almost all UDP connections goes to DIRECT, and I can't change this behavior whatsoever.

<img width="1391" alt="Image" src="https://github.com/user-attachments/assets/922d71f0-8dc9-4cbc-b0ff-bf2e6b1e5b49" />

I don't know if this is my mistake or a bug, but it's quite annoying. For example, all connections to YouTube for some reason goes through "Tun(udp)" (see the screenshot above), so I can't tunnel them correctly, since they always uses DIRECT connection.

Is there any way to fix this?

### 软件版本 / Verge Version

2.1.1, 2.1.2

### 复现步骤 / To Reproduce

Setup Global Extend Config:

```
profile:
  store-selected: true

dns:
  use-system-hosts: false

rules:
  - GEOIP,ru,DIRECT
  - GEOIP,telegram,DIRECT
  - GEOSITE,telegram,DIRECT
  - GEOSITE,apple,DIRECT
  - GEOSITE,apple-ads,DIRECT
  - GEOSITE,apple-dev,DIRECT
  - GEOSITE,apple-pki,DIRECT
  - GEOSITE,apple-update,DIRECT
  - GEOSITE,twitch,DIRECT
  - NETWORK,udp,🔥 Auto(Best ping)
  - MATCH,🔥 Auto(Best ping)
```

There is DIRECT used for "Tun(udp)" connections, which is incorrect.

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

macOS Ventura 13.7.4 (22H420)

### 系统标签 / OS Labels

- [ ] windows
- [x] macos
- [ ] linux

### 日志 / Log

[2025-03-03-1622.log](https://github.com/user-attachments/files/19053880/2025-03-03-1622.log)
