### ISSUE TITLE
[BUG] 直连模式无法使用

### ISSUE THREAD

**Issue by Malcolm-Allen** [clash-verge-rev/clash-verge-rev#2892]
### 问题描述 / Describe the bug

无法使用直连连接，无论是direct规则还是打开直连模式，但打开全局模式时可正常使用

### 软件版本 / Verge Version

软件版本2.0.3

### 复现步骤 / To Reproduce

无法使用直连连接，无论是direct规则还是打开直连模式

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 10 Version 22H2

### 系统标签 / OS Labels

- [x] windows
- [ ] macos
- [ ] linux

### 日志 / Log

03-04 20:59:27warning
[TCP] dial Bilibili (match DomainSuffix/bilibili.com) 127.0.0.1:9314(chrome.exe) --> www.bilibili.com:443 error: connect failed: dial tcp 104.244.46.165:443: i/o timeout connect failed: dial tcp [2a03:2880:f102:183:face:b00c:0:25de]:443: i/o timeout

**Comment by rapmq0** [comment]
我跟你一样，所有DIRECT的网站都打不开了

**Comment by verg1l0** [comment]
Same

**Comment by Tythee** [comment]
一样

**Comment by Dudengtai** [comment]
2.1.2一样，所有直连的规则都无法正常打开

**Comment by JiangYingjin** [comment]
2.1.2一样，所有直连的规则都无法正常打开

**Comment by DIluo1549** [comment]
尝试将dns改成falsh

**Comment by ccccccmd** [comment]
> 尝试将dns改成falsh

Bro，在哪块操作？

**Comment by DIluo1549** [comment]
> > 尝试将dns改成falsh
> 
> Bro，在哪块操作？

打开你的配置文件找到dns这块,在上面区域
enable后面的true改成falsh

**Comment by Tychristine** [comment]
@Malcolm-Allen 
# 检查iPv6设置，没有IPv6就不要打开

**Comment by GoBigorGoHome** [comment]
关闭 ipv6 后问题仍然存在。

**Comment by pengyonggh** [comment]
> > > 尝试将dns改成falsh
> > 
> > 
> > Bro，在哪块操作？
> 
> 打开你的配置文件找到dns这块,在上面区域 enable后面的true改成falsh

这个办法可以解决。
想请问下我的软件很久没更新了，为啥会出现这种问题，是代理订阅的问题嘛？

**Comment by Tychristine** [comment]
@GoBigorGoHome 
# 请补充一下日志，以便于排查问题

**Comment by maszhaowei** [comment]
[2025-03-05-1410.log](https://github.com/user-attachments/files/19083321/2025-03-05-1410.log)
service日志，一样的问题

**Comment by median-dxz** [comment]
@DIluo1549 

你确定是`falsh`而不是`false`吗，这应该只是一个boolean量，我不确定他们用的yml解析库会把falsh解析成什么，如果是你意外拼写错误了，最好说明一下

**Comment by fengyaocheng** [comment]
确实是false,不要改成falsh......

**Comment by GoBigorGoHome** [comment]
> [@GoBigorGoHome](https://github.com/GoBigorGoHome)
> 
> # 请补充一下日志，以便于排查问题

@Tychristine  [日志.log](https://github.com/user-attachments/files/19085213/default.log)

**Comment by Malcolm-Allen** [comment]
> 尝试将dns改成false

感谢！请问如果想使用混合配置而不是复制一份配置文件的话该怎么搞呢？真心求教！

**Comment by Malcolm-Allen** [comment]
> [@Malcolm-Allen](https://github.com/Malcolm-Allen)
> 
> # 检查iPv6设置，没有IPv6就不要打开

有IPV6，但没有打开

**Comment by Tychristine** [comment]
@Malcolm-Allen 
但你发的日志中显示的是ipv6地址
而且你这个日志是让b站走代理但没有连通？

**Comment by xingjianlin** [comment]
same, 自带的direct可以直连，比如baidu bilibili 这种 但是自己编辑规则里加上的direct网站无法访问

**Comment by Malcolm-Allen** [comment]
> [@Malcolm-Allen](https://github.com/Malcolm-Allen) 但你发的日志中显示的是ipv6地址 而且你这个日志是让b站走代理但没有连通？

应该是是v4没通才走v6？我把配置文件里的dns那项改成false以后再用dnsjumper改完本机dns，现在只有v4了
另外求问怎么用混合配置解决这个问题啊？我把改成false以后那段原样输进混合配置里没用

**Comment by stankyoztc** [comment]
ipv6下 开启dns后会把直连规则解析成AAAA但又实际不能用

于是关掉软件内设置的ipv6选项 然后自动更新后 是可以使用的

但是 一旦重启软件 再次使用,直连的网站则会无法解析到ip 见文件   
就手写规则rules里的这个规则 - DOMAIN-SUFFIX,appstorrent.ru,DIRECT 而言

[未命名.txt](https://github.com/user-attachments/files/19089151/default.txt)


去除所有dns设置 只保留
```
dns:
  use-system-hosts: false
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
```
就一切正常

**Comment by stankyoztc** [comment]
> > ipv6下 开启dns后会把直连规则解析成AAAA但又实际不能用
> > 于是关掉软件内设置的ipv6选项 然后自动更新后 是可以使用的
> > 但是 一旦重启软件 再次使用,直连的网站则会无法解析到ip 见文件 就手写规则rules里的这个规则 - DOMAIN-SUFFIX,appstorrent.ru,DIRECT 而言
> > [未命名.txt](https://github.com/user-attachments/files/19089151/default.txt)
> > 去除所有dns设置 只保留
> > ```
> > dns:
> >   use-system-hosts: false
> >   enable: true
> >   ipv6: false
> >   enhanced-mode: fake-ip
> >   fake-ip-range: 198.18.0.1/16
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 就一切正常
> 
> 求问直接复制这些到混合配置里就能直接用原始配置文件了吗？

各个地区dns或者设备可能都有不同 我是mac端自搓规则 按道理说粘贴到 拓展覆写配置 里是会覆盖原dns整个设置 您可以到 设置-verge高级设置-当前配置里看具体效果(我的规则是按这个手搓的 [规则](https://gist.github.com/liuran001/5ca84f7def53c70b554d3f765ff86a33) 用到geoip了 (也算当分流了:笑。 )

**Comment by q736178471** [comment]
同样问题，更新最新版本后，所有直连连接无法打开

**Comment by stankyoztc** [comment]
> > > > ipv6下 开启dns后会把直连规则解析成AAAA但又实际不能用
> > > > 于是关掉软件内设置的ipv6选项 然后自动更新后 是可以使用的
> > > > 但是 一旦重启软件 再次使用,直连的网站则会无法解析到ip 见文件 就手写规则rules里的这个规则 - DOMAIN-SUFFIX,appstorrent.ru,DIRECT 而言
> > > > [未命名.txt](https://github.com/user-attachments/files/19089151/default.txt)
> > > > 去除所有dns设置 只保留
> > > > ```
> > > > dns:
> > > >   use-system-hosts: false
> > > >   enable: true
> > > >   ipv6: false
> > > >   enhanced-mode: fake-ip
> > > >   fake-ip-range: 198.18.0.1/16
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 就一切正常
> > > 
> > > 
> > > 求问直接复制这些到混合配置里就能直接用原始配置文件了吗？
> > 
> > 
> > 各个地区dns或者设备可能都有不同 我是mac端自搓规则 按道理说粘贴到 拓展覆写配置 里是会覆盖原dns整个设置 您可以到 设置-verge高级设置-当前配置里看具体效果(我的规则是按这个手搓的 [规则](https://gist.github.com/liuran001/5ca84f7def53c70b554d3f765ff86a33) 用到geoip了 (也算当分流了:笑。 ) 当然记得在clash设置 把ipv6的UI开关关掉
> 
> 感谢！ 另外求问伪装ip这个特性有可能过不去cloudflare的验证吗？我这有几个网站卡了

更新 确实 今天我也遇到这个问题 只要是rule里指定direct的用dns全超时无法解析,虽然指定直连但依旧用外国dns解析不出东西..于是我手动复原了 并指定了国内dns就都解决了
dns恢复成出问题前的并加上  nameserver-policy 指定dns 
```
  nameserver-policy:
    #域名:国内dns     
    '+.xxx.yyy': '223.5.5.5'
   #结束 底下原来是啥还是啥

............

```

**Comment by wesselyang** [comment]
这两天也发现DIRECT在TUN模式下显示测延迟失败的情况。
然后看了下日志，报错WARN的部分都是跟DoH有关系，于是把配置当中dns部分的DoH都移除了后（nameserver把https开头的都删掉，不使用加密dns），直连部分又生效了。
感觉最近的最近国内的DoH像是有大动作，DoT我没用所以没测试。

**Comment by wolthon** [comment]
同样的问题，关闭ipv6也不行，不管是直连模式，还是Direct放行规则都连不了

**Comment by stankyoztc** [comment]
DNS里加上这个,此贴完结

```
  direct-nameserver:
    - system
  direct-nameserver-follow-policy: false
```

贴出我的配置 由 [这里的示例](https://gist.github.com/liuran001/5ca84f7def53c70b554d3f765ff86a33)和[这个](https://wiki.metacubex.one/config/dns/#direct-nameserver) 改得

```
dns:
  enable: true
  listen: :1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
#    - '[2402:4e00::]'
#    - '[2400:3200::1]'
  nameserver:
    - 'tls://8.8.4.4#dns'
    - 'tls://1.0.0.1#dns'
#    - 'tls://[2001:4860:4860::8844]#dns'
#    - 'tls://[2606:4700:4700::1001]#dns'
  proxy-server-nameserver:
    - https://doh.pub/dns-query

  direct-nameserver:
    - system
  direct-nameserver-follow-policy: false

  nameserver-policy:
    "geosite:cn,private":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
    "geosite:!cn,!private": 
      - "tls://dns.google"
      - "tls://cloudflare-dns.com"
```

**Comment by Malcolm-Allen** [comment]
> > > > > ipv6下 开启dns后会把直连规则解析成AAAA但又实际不能用
> > > > > 于是关掉软件内设置的ipv6选项 然后自动更新后 是可以使用的
> > > > > 但是 一旦重启软件 再次使用,直连的网站则会无法解析到ip 见文件 就手写规则rules里的这个规则 - DOMAIN-SUFFIX,appstorrent.ru,DIRECT 而言
> > > > > [未命名.txt](https://github.com/user-attachments/files/19089151/default.txt)
> > > > > 去除所有dns设置 只保留
> > > > > ```
> > > > > dns:
> > > > >   use-system-hosts: false
> > > > >   enable: true
> > > > >   ipv6: false
> > > > >   enhanced-mode: fake-ip
> > > > >   fake-ip-range: 198.18.0.1/16
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 就一切正常
> > > > 
> > > > 
> > > > 求问直接复制这些到混合配置里就能直接用原始配置文件了吗？
> > > 
> > > 
> > > 各个地区dns或者设备可能都有不同 我是mac端自搓规则 按道理说粘贴到 拓展覆写配置 里是会覆盖原dns整个设置 您可以到 设置-verge高级设置-当前配置里看具体效果(我的规则是按这个手搓的 [规则](https://gist.github.com/liuran001/5ca84f7def53c70b554d3f765ff86a33) 用到geoip了 (也算当分流了:笑。 ) 当然记得在clash设置 把ipv6的UI开关关掉
> > 
> > 
> > 感谢！ 另外求问伪装ip这个特性有可能过不去cloudflare的验证吗？我这有几个网站卡了
> 
> 更新 确实 今天我也遇到这个问题 只要是rule里指定direct的用dns全超时无法解析,虽然指定直连但依旧用外国dns解析不出东西..于是我手动复原了 并指定了国内dns就都解决了 dns恢复成出问题前的并加上 nameserver-policy 指定dns
> 
> ```
>   nameserver-policy:
>     #域名:国内dns     
>     '+.xxx.yyy': '223.5.5.5'
>    #结束 底下原来是啥还是啥
> 
> ............
> ```
> 
> 更新 绝了 一天又失效了 开始cf验证循环了。是不是看不见的大手在搞事啊
> 
> 再次更新 : 什么都没改 今天又都好了 不卡cf验证了

老哥，这段代码没看懂怎么改

我这把伪装ip相关去掉了，但还是卡循环验证，唉

**Comment by stankyoztc** [comment]
> > > > > > ipv6下 开启dns后会把直连规则解析成AAAA但又实际不能用
> > > > > > 于是关掉软件内设置的ipv6选项 然后自动更新后 是可以使用的
> > > > > > 但是 一旦重启软件 再次使用,直连的网站则会无法解析到ip 见文件 就手写规则rules里的这个规则 - DOMAIN-SUFFIX,appstorrent.ru,DIRECT 而言
> > > > > > [未命名.txt](https://github.com/user-attachments/files/19089151/default.txt)
> > > > > > 去除所有dns设置 只保留
> > > > > > ```
> > > > > > dns:
> > > > > >   use-system-hosts: false
> > > > > >   enable: true
> > > > > >   ipv6: false
> > > > > >   enhanced-mode: fake-ip
> > > > > >   fake-ip-range: 198.18.0.1/16
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > 就一切正常
> > > > > 
> > > > > 
> > > > > 求问直接复制这些到混合配置里就能直接用原始配置文件了吗？
> > > > 
> > > > 
> > > > 各个地区dns或者设备可能都有不同 我是mac端自搓规则 按道理说粘贴到 拓展覆写配置 里是会覆盖原dns整个设置 您可以到 设置-verge高级设置-当前配置里看具体效果(我的规则是按这个手搓的 [规则](https://gist.github.com/liuran001/5ca84f7def53c70b554d3f765ff86a33) 用到geoip了 (也算当分流了:笑。 ) 当然记得在clash设置 把ipv6的UI开关关掉
> > > 
> > > 
> > > 感谢！ 另外求问伪装ip这个特性有可能过不去cloudflare的验证吗？我这有几个网站卡了
> > 
> > 
> > 更新 确实 今天我也遇到这个问题 只要是rule里指定direct的用dns全超时无法解析,虽然指定直连但依旧用外国dns解析不出东西..于是我手动复原了 并指定了国内dns就都解决了 dns恢复成出问题前的并加上 nameserver-policy 指定dns
> > ```
> >   nameserver-policy:
> >     #域名:国内dns     
> >     '+.xxx.yyy': '223.5.5.5'
> >    #结束 底下原来是啥还是啥
> > 
> > ............
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 更新 绝了 一天又失效了 开始cf验证循环了。是不是看不见的大手在搞事啊
> > 再次更新 : 什么都没改 今天又都好了 不卡cf验证了
> 
> 老哥，这段代码没看懂怎么改
> 
> 我这把伪装ip相关去掉了，但还是卡循环验证，唉


我用的是这个 加上了direct-nameserver 指定了direct规则的域名 走的路由器dns  

```
#用于direct出口域名解析的 DNS 服务器，如果不填则遵循nameserver-policy、nameserver和fallback的配置。我用了路由器的 你随意
  direct-nameserver:
    - system
#是否遵循nameserver-policy，默认为不遵守，仅当direct-nameserver不为空时生效 false时nameserver-policy失效
  direct-nameserver-follow-policy: false
```

```
dns:
  enable: true
  listen: :1053
#DNS的 ipv6 支持 记得上面和下面rules里都还有ipv6相关配置
  ipv6: false
  proxy: dns
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
    
  #默认 DNS, 纯ipv4用于解析 其他DNS服务器的域名
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
#    - '[2402:4e00::]'
#    - '[2400:3200::1]'

#nameserver-policy指定域名查询的解析服务器，可使用 geosite, 优先于 nameserver/fallback 查询。 启用direct-nameserver则失效
#  nameserver-policy:
#中国地址的网站和私人网址走 国内dns解析
#    "geosite:cn,private":
#      - https://doh.pub/dns-query
#      - https://dns.alidns.com/dns-query
#    "geosite:!cn,!private": 
#      - "tls://dns.google"
#      - "tls://cloudflare-dns.com"
      
#默认的域名解析服务器 dns后面的“#xxx” 指定了走名为xxx的策略组出口 你用不到可以删除指定的策略组 不知道就看 虚空终端doc
  nameserver:
    - 'tls://8.8.4.4#dns'
    - 'tls://1.0.0.1#dns'
#用ipv6记得打开
#    - 'tls://[2001:4860:4860::8844]#dns'
#    - 'tls://[2606:4700:4700::1001]#dns'

#代理节点域名解析服务器，仅用于解析代理节点的域名，如果不填则遵循nameserver-policy、nameserver和fallback的配置
  proxy-server-nameserver:
    - https://doh.pub/dns-query
    
#用于direct出口域名解析的 DNS 服务器，如果不填则遵循nameserver-policy、nameserver和fallback的配置。我用了路由器的 你随意
  direct-nameserver:
    - system
#是否遵循nameserver-policy，默认为不遵守，仅当direct-nameserver不为空时生效 false时nameserver-policy失效
  direct-nameserver-follow-policy: false
```
