### ISSUE TITLE
[BUG] 开启 Clash Verge 时（无论是否开启代理或直连模式）无法访问 apple.com 及苹果相关网站

### ISSUE THREAD

**Issue by SparkChiu** [clash-verge-rev/clash-verge-rev#2910]
### 问题描述 / Describe the bug

日常正常使用，突然发现无法访问 apple.com.cn ，尝试 apple.com 也玩法访问，表现为浏览器网页无法打开。
在 Clash Verge 仪表盘界面中的「测试」项里，Apple 测试：Timeout

尝试在 Clash Verge 上关闭系统代理、设置为直连模式、添加规则等方式，都无效。
直到关闭 Clash Verge 后恢复正常访问。

另：更换其他代理 APP ，用同一个梯子，可以正常访问。

### 软件版本 / Verge Version

Clash.Verge_2.1.2_aarch64

### 复现步骤 / To Reproduce

启动 Clash Verge，开启系统代理，访问 apple.com

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

macOS Sequoia 15.3.1

### 系统标签 / OS Labels

- [ ] windows
- [x] macos
- [ ] linux

### 日志 / Log

[log.zip](https://github.com/user-attachments/files/19081508/log.zip)

**Comment by rapmq0** [comment]
我也是

**Comment by Dudengtai** [comment]
2.1.2访问微软，spotify等规则设置直连的都有此类问题。
微软服务 (match DomainSuffix/microsoft.com) 198.18.0.1:10731(MoUsoCoreWorker.exe) --> settings-win.data.microsoft.com:443 error: dns resolve failed: couldn't find ip
dns无法正常解析

**Comment by DIluo1549** [comment]
配置文件中的dns选项改成falsh试下,我的好了,感觉是dns的问题不要用软件的dns

**Comment by JiangYingjin** [comment]
> 配置文件中的dns选项改成falsh试下,我的好了,感觉是dns的问题不要用软件的dns

将 DNS 禁用后直连模式恢复正常！

**Comment by Dudengtai** [comment]
我修改成false，依然存在这个问题
dns:
  enable: false
  ipv6: true
  listen: 127.0.0.1:5334
  default-nameserver:
  - 180.184.1.1
  - 119.29.29.29
  - 223.5.5.5

**Comment by Dudengtai** [comment]
> 配置文件中的dns选项改成falsh试下,我的好了,感觉是dns的问题不要用软件的dns

我修改成false，依然存在这个问题
dns:
enable: false
ipv6: true
listen: 127.0.0.1:5334
default-nameserver:

180.184.1.1
119.29.29.29
223.5.5.5

**Comment by Dudengtai** [comment]
> 配置文件中的dns选项改成falsh试下,我的好了,感觉是dns的问题不要用软件的dns

已经解决了 ，刚才配置没有生效

**Comment by SparkChiu** [comment]
> > 配置文件中的dns选项改成falsh试下,我的好了,感觉是dns的问题不要用软件的dns
> 
> 已经解决了 ，刚才配置没有生效

要怎么操作生效？我也是配置了，但是查看运行时配置还是 true

**Comment by Dudengtai** [comment]
> > > 配置文件中的dns选项改成falsh试下,我的好了,感觉是dns的问题不要用软件的dns
> > 
> > 
> > 已经解决了 ，刚才配置没有生效
> 
> 要怎么操作生效？我也是配置了，但是查看运行时配置还是 true

在你的订阅文件上右键-编辑文件，然后修改为false，他就会自动重新加载配置了

**Comment by TAOGZ** [comment]
直接在配置文件中改成false，重新启动后又会恢复成true，怎么解决？

**Comment by DIluo1549** [comment]
> 直接在配置文件中改成false，重新启动后又会恢复成true，怎么解决？

你应该用的是订阅链接,导致每次打开都会更新然后恢复,可以把自动更新关了,但是有可能机场主会更新导致你的订阅失效

**Comment by stankyoztc** [comment]
更新之后发现即使是写了rules 域名 direct的规则,它却在tun模式时根本无法解析 .排查错误换写dns也不能解决,索性直接把dns整个删掉了 .

我心想反正
```
  - GEOSITE,CN,国内
  - GEOIP,CN,国内
```
有了,剩下直接交给节点算了
dns好多时候越写越是负优化....如果有大佬欢迎分享dns配置
底下是试过的dns配置
```
dns:
enable: true
prefer-h3: true
listen: :1053
enhanced-mode: fake-ip
fake-ip-range: 28.0.0.1/8
fake-ip-filter:
- "*"
- "+.lan"
- "+.local"
nameserver:
- https://101.101.101.101/dns-query
- https://1.1.1.1/dns-query
nameserver-policy:
"geosite:cn,private":
- https://223.5.5.5/dns-query#h3=true
- https://223.6.6.6/dns-query#h3=true
```

```
dns:
  enable: true
  listen: :1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
    - '[2402:4e00::]'
    - '[2400:3200::1]'
  nameserver:
    - 'tls://8.8.4.4#dns'
    - 'tls://1.0.0.1#dns'
    - 'tls://[2001:4860:4860::8844]#dns'
    - 'tls://[2606:4700:4700::1001]#dns'
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
    "geosite:!cn,!private": 
      - "tls://dns.google"
      - "tls://cloudflare-dns.com"
```
