### ISSUE TITLE
[BUG] 连接请求显示为 ip，不是域名

### ISSUE THREAD

**Issue by alisre** [clash-verge-rev/clash-verge-rev#2918]
### 问题描述 / Describe the bug

如图所示，先打开 clash-verge-rev tun 模式下访问google 正常

<img width="875" alt="Image" src="https://github.com/user-attachments/assets/4006f640-5b97-4291-bc79-035e3bcae7bb" />
开启公司 MotionPro VPN 后，无法访问 google ，如下图
<img width="850" alt="Image" src="https://github.com/user-attachments/assets/07b23075-0e49-40c8-9e04-941c124ca512" />

### 软件版本 / Verge Version

2.0.3

### 复现步骤 / To Reproduce

我的配置
```
mixed-port: 7890
unified-delay: false
geodata-mode: true
tcp-concurrent: false
find-process-mode: strict
global-client-fingerprint: chrome

allow-lan: true
mode: rule
log-level: info
ipv6: true

external-controller: 127.0.0.1:9090

geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: false
  sniff:
    TLS:
      ports: [443]
    HTTP:
      ports: [80]
      override-destination: true

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - 'any:53'
    - "tcp://any:53"
  auto-route: true
  auto-detect-interface: true
  route-exclude-address:
    - 192.168.0.0/16

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '*'
    - '+.lan'
    - 'localhost.ptlogin2.qq.com'
    - localhost.sec.qq.com'
    - 'localhost.work.weixin.qq.com'
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query#h3=true
  nameserver-policy:
    "geosite:cn,private":
      - 223.5.5.5
      - 114.114.114.114
      - https://dns.alidns.com/dns-query#h3=true
```

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

16

### 系统标签 / OS Labels

- [ ] windows
- [x] macos
- [ ] linux

### 日志 / Log

无
