### ISSUE TITLE
tailscale MagicDNS 无效

### ISSUE THREAD

**Issue by bzsome** [clash-verge-rev/clash-verge-rev#2952]
客户端操作系统：win11 24H2
clash verge版本：2.1.2
tailscale版本：1.80.2

MagicDNS = tailscale自定义的dns

clash配置如下：
(100.100.1.1 为私网自建dns服务，配置了域名解析)
```yaml
profile:
  store-selected: true

dns:
  use-system-hosts: true
  enable: true
  default-nameserver: [100.100.100.100, 100.100.1.1]
  nameserver: ["100.100.100.100", "100.100.1.1"]
```
## 问题描述
未打开clash前，tailscale自定义的MagicDNS，可以正常使用域名访问
但是在打开clash后，其MagicDNS无法使用(即无法使用域名访问)，但是可以私用私网iP访问
（代理模式和tun模式相同结果）
请问怎样配置才能使tailscale的dns可以正常使用？

## clash和MagicDNS兼容性测试
关闭clash，tailscale客户端开启tailscale的dns后，ping 域名**有**解析结果，浏览器使用域名访问正常，使用私网ip访问正常
打开clash，tailscale客户端开启tailscale的dns后，ping 域名**有**解析结果，浏览器使用域名无法访问，使用私网ip访问正常
打开clash，tailscale客户端关闭tailscale的dns后，ping 域名**无**解析结果，浏览器使用域名无法访问，使用私网ip访问正常

## 本地host修改测试
打开clash，配置use-system-hosts: true，本地电脑修改host文件域名为私网ip，ping 域名**有**解析结果，浏览器访问正常

**Comment by Tychristine** [comment]
# 请问你是如何配置 nameserver-policy的？

**Comment by wonfen** [comment]
无反馈，关闭

**Comment by FluxForceDynamics** [comment]
配置use-system-hosts: true; win11 测试通过, 2025-07-17 (星期四)

**Comment by ZhiboWong** [comment]
> 配置use-system-hosts: true; win11 测试通过, 2025-07-17 (星期四)

修改并重启了clash也不生效
修改部分内容如下
```yaml
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
unified-delay: true
sniffer:
  sniff:
    TLS: {ports: [443], override-destination: true}
    HTTP: {ports: [443], override-destination: true}
  enable: true
  parse-pure-ip: false
  force-dns-mapping: true
  override-destination: true
ipv6: false
clash-for-android:
  append-system-dns: false
profile:
  tracing: true
experimental:
  sniff-tls-sni: true
dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:1053
  use-hosts: true
  fake-ip-range: 198.18.0.1/15
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - stun.*.*
    - stun.*.*.*
    - swscan.apple.com
    - mesu.apple.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - localhost.ptlogin2.qq.com
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - +.wotgame.cn
    - +.wggames.cn
    - +.wowsgame.cn
    - +.wargaming.net
    - "*.*.*.srv.nintendo.net"
    - "*.*.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.ipv6.microsoft.com"
    - teredo.*.*.*
    - teredo.*.*
    - speedtest.cros.wr.pvp.net
    - +.jjvip8.com
    - www.douyu.com
    - activityapi.huya.com
    - activityapi.huya.com.w.cdngslb.com
    - www.bilibili.com
    - api.bilibili.com
    - a.w.bilicdn1.com
    - +.163cdn-ai.com
  enhanced-mode: fake-ip
  use-system-hosts: true
```
