### ISSUE TITLE
[BUG] vless类型无法使用

### ISSUE THREAD

**Issue by sunhotblaze** [clash-verge-rev/clash-verge-rev#2953]
### 问题描述 / Describe the bug

我更新后2.1.2使用vless节点无法使用，回退之前版本也不行
使用v2rayN工具节点正常使用

### 软件版本 / Verge Version

2.1.2

### 复现步骤 / To Reproduce

测速error，节点无法代理

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

26100.3194

### 系统标签 / OS Labels

- [x] windows
- [ ] macos
- [ ] linux

### 日志 / Log

error: usa.visa.com:443 connect error: dns resolve failed: couldn't find ip"

**Comment by Tychristine** [comment]
把下面这一段配置复制到你的**全局扩展配置**，再重启内核

```yaml
dns:
  enable: true
  prefer-h3: true
  use-system-hosts: true
  listen: 0.0.0.0:5053
  ipv6: true
  respect-rules: false
  enhanced-mode: fake-ip
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.0/16
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "connect.rom.miui.com"
    - "+.miwifi.com"
    - "+.ntp.org"
    # QQ
    - "localhost.ptlogin2.qq.com"
    - "localhost.sec.qq.com"
    # WeChat
    - "localhost.work.weixin.qq.com"
    - "+.weixin.qq.com"
    - "+.wechat.com"
    # Windows
    - "time.windows.com"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "+.wpsmail.net"
    - "+.henzanapp.com"
    - "+.pconline.com.cn"
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - 8.8.8.8
    - 175.50.10.10
  direct-nameserver:
    - system
 ```

**Comment by Tychristine** [comment]
`usa.visa.com:443` 报错是这个域名解析不到IP，你换个能解析的DNS吧
(我也不知道为什么这个配置你用不了)

**Comment by shuaibiyige123** [comment]
我也是这个问题，请问解决了吗？

**Comment by jianjunlu** [comment]
我也遇到了这个问题，使用 v2rayN 正常，
使用 clash-verge-rev 则报错：connect error: failed to use vision, maybe "security" is not "tls" or "utls"

系统是Mac os 12.7.6，
clash-verge-rev：2.1.2，
clash-verge-rev 里的vless配置：
 - name: xray
    type: vless
    server: ip
    port: 1234
    uuid: aaa-bbb-cc
    network: tcp
    udp: true
    flow: xtls-rprx-vision
    servername: aws.amazon.com
    reality-opts:
      public-key: key
    client-fingerprint: chrome

**Comment by Tychristine** [comment]
@jianjunlu 
你配置写错了，建议按照官方的[格式](https://wiki.metacubex.one/config/proxies/vless/#vless)写

```yaml
  - name: "Proxy-VLESS"
    type: "vless"
    server: "IPaddress"
    port: 443
    uuid: "12345-123-123-1234-123456"
    tls: true
    tfo: true
    udp: true
    servername: "example.com"
    flow: "xtls-rprx-vision"
    client-fingerprint: "chrome"
    skip-cert-verify: true
    reality-opts:
      public-key: "xxbb"
      short-id: "123456"
    network: "tcp"
```
