### ISSUE TITLE
[BUG] 会卡fusion360,退出Clash Verge Rev后才会回复正常

### ISSUE THREAD

**Issue by wuldas** [clash-verge-rev/clash-verge-rev#2993]
### 问题描述 / Describe the bug

和fusion360同时存在让fusion360明显的卡顿,退出clash-verge-rev后恢复正常

### 软件版本 / Verge Version

版本是Windows 2.1.2

### 复现步骤 / To Reproduce

和fusion360同时存在

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 64位

### 系统标签 / OS Labels

- [x] windows
- [ ] macos
- [ ] linux

### 日志 / Log

无

**Comment by wonfen** [comment]
大概率DNS的问题，下载最新版试试

https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/alpha

**Comment by wuldas** [comment]
> 大概率DNS的问题，下载最新版试试
> 
> https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/alpha

装了最新的还是一样,换成v2rayN就没问题;用clash-verge-rev fusion360会出现证书错误,v2rayN不会

**Comment by wonfen** [comment]
> > 大概率DNS的问题，下载最新版试试
> > https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/alpha
> 
> 装了最新的还是一样,换成v2rayN就没问题;用clash-verge-rev fusion360会出现证书错误,v2rayN不会

证书错误说明是DNS污染，配置文件发上来看看

**Comment by wuldas** [comment]
> > > 大概率DNS的问题，下载最新版试试
> > > https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/alpha
> > 
> > 
> > 装了最新的还是一样,换成v2rayN就没问题;用clash-verge-rev fusion360会出现证书错误,v2rayN不会
> 
> 证书错误说明是DNS污染，配置文件发上来看看

```yaml
# clash-verge.yaml
# Generated by Clash Verge

mode: rule
mixed-port: 7897
allow-lan: false
log-level: info
external-controller: 127.0.0.1:9097
secret: ''
unified-delay: true
dns:
  default-nameserver:
  - 119.29.29.29
  - 223.5.5.5
  enable: true
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - https://doh.pub/dns-query
  - https://223.6.6.6/dns-query
  use-hosts: true
  use-system-hosts: false
external-controller-cors:
  allow-private-network: true
  allow-origins:
  - '*'
profile:
  store-selected: true
tun:
  enable: false
  stack: mixed
  auto-route: true
  strict-route: false
  auto-detect-interface: true
  dns-hijack:
  - any:53
```

```yaml
# Clash Verge DNS Config

enable: true
listen: :53
enhanced-mode: fake-ip
fake-ip-range: 198.18.0.1/16
fake-ip-filter-mode: blacklist
prefer-h3: false
respect-rules: false
use-hosts: false
use-system-hosts: false
fake-ip-filter:
- '*.lan'
- '*.local'
- '*.arpa'
- time.*.com
- ntp.*.com
- time.*.com
- +.market.xiaomi.com
- localhost.ptlogin2.qq.com
- '*.msftncsi.com'
- www.msftconnecttest.com
default-nameserver:
- 223.6.6.6
- 8.8.8.8
nameserver:
- 8.8.8.8
- https://doh.pub/dns-query
- https://dns.alidns.com/dns-query
fallback:
- https://dns.alidns.com/dns-query
- https://dns.google/dns-query
- https://cloudflare-dns.com/dns-query
nameserver-policy: {}
proxy-server-nameserver:
- https://doh.pub/dns-query
- https://dns.alidns.com/dns-query
direct-nameserver: []
direct-nameserver-follow-policy: false
fallback-filter:
  geoip: true
  geoip-code: CN
  ipcidr:
  - 240.0.0.0/4
  - 0.0.0.0/32
  domain:
  - +.google.com
  - +.facebook.com
  - +.youtube.com
```
