### ISSUE TITLE
[BUG] 对于h3/quic的请求应用reject后，发起请求不会被关闭

### ISSUE THREAD

**Issue by dev4u** [clash-verge-rev/clash-verge-rev#3013]
### 问题描述 / Describe the bug

添加了一条规则，以便禁用所有的非大陆目的地h3/quic请求：
`AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOSITE,CN))),(NOT,((GEOIP,CN))),REJECT`

TUN配置：
```yaml
tun:
  mtu: 9000
  stack: system
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  gso: true
  gso-max-size: 65536
  udp-timeout: 120
  device: mihomo
  dns-hijack:
  - any:53
  strict-route: true
  enable: true
```

在[连接]页面中仍能看到2小时前的连接。
```text
主机: :443
下载量: 0 B
上传量: 0 B
下载速度: 0 B/s
上传速度: 0 B/s
链路: REJECT
规则: AND(((AND,((DstPort,443) && (Network,udp))) && (NOT,(!(GeoSite,CN))) && (NOT,(!(GeoIP,cn)))))
进程:
连接时间: 2 小时前
源地址: :0
目标地址: 104.16.248.249
目标端口: 443
类型: Inner(udp)
```

### 软件版本 / Verge Version

verge版本：v2.1.3-bb078560
核心版本：alpha-e3d4ec2 Mihomo

### 复现步骤 / To Reproduce

设置分流规则后发起请求

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

12.7.6 Monterey

### 系统标签 / OS Labels

- [ ] windows
- [x] macos
- [ ] linux

### 日志 / Log

不适用，如果有需要可以后补。
