### ISSUE TITLE
[BUG] 仅 IPv6 网站存在访问延迟

### ISSUE THREAD

**Issue by Rirmach** [clash-verge-rev/clash-verge-rev#3097]
### 问题描述 / Describe the bug

当访问纯 IPv6 网站时，IPv6 的地址已经被解析出，但代理程序仍然会等待 5 秒钟后才连接。并且似乎只发生在使用系统代理的情况下。该问题在同样的配置、仅使用 Clash 内核的时候不会出现。
出站配置为 IPv6 优先：

```yaml
proxies:
  - name: "Custom_Direct"
    type: direct
    udp: true
    ip-version: ipv6-prefer
```
由于部分局域网内应用仅在局域网内解析，因此不能在 Clash 中配置公共 DNS 服务器

### 软件版本 / Verge Version

v2.2.0

### 复现步骤 / To Reproduce

1. DNS 配置部分留空（或上游设置为 system），关闭 DNS 覆写，关闭 TUN，关闭系统代理
2. 重启 Clash 内核
3. 访问一个只能解析出 IPv6 的域名（设置代理的浏览器和 curl --proxy 均可复现）
4. 在日志中看到 AAAA 记录已经获得
5. 等待大约 5 秒钟
6. 返回结果
### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

![Image](https://github.com/user-attachments/assets/cec5a9fd-7259-4f53-8dad-e05c31816a78)
