### ISSUE TITLE
[BUG] RULE-SET 内部规则与精确规则的优先级不一致问题

### ISSUE THREAD

**Issue by epodak** [clash-verge-rev/clash-verge-rev#3194]
### 问题描述 / Describe the bug

发现规则优先级处理存在不一致行为：

1. **精确规则优先**：当使用 `DOMAIN/DOMAIN-SUFFIX` 明确定义时（如 `"DOMAIN-SUFFIX,claude.ai,🧠 AI 服务"`），确实能优先匹配
2. **规则集(RULE-SET)问题**：当相同的域名通过 `RULE-SET` 引入时（如 `"RULE-SET,claude_rule,🧠 AI 服务"` 包含 claude.ai），会被后面的通用规则（如 tld-not-cn）覆盖

### 软件版本 / Verge Version

- 软件版本：[v1.19.3 Mihomo]
- 核心版本：[2.2.2]

### 复现步骤 / To Reproduce

**最小重现配置**：
```yaml
rules:
  - "DOMAIN-SUFFIX,claude.ai,AI"  # 能正常工作
  - "RULE-SET,claude_rule,AI"        # 会被后面的 tld-not-cn 覆盖
  - "RULE-SET,tld-not-cn,PROXY"      # 包含 .com 等通用规则

rule-providers:
  claude_rule:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Claude/Claude.yaml"
    path: ./ruleset/claude_rule.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
```

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

11

### 日志 / Log

null
