### ISSUE TITLE
[BUG] 使用Geosite category-ai-!cn导致配置文件无法使用

### ISSUE THREAD

**Issue by HaoTian22** [clash-verge-rev/clash-verge-rev#3244]
### 问题描述 / Describe the bug

![Image](https://github.com/user-attachments/assets/fb08e040-a79c-4b6f-9372-c9be8864d3d9)
加入- GEOSITE,category-ai-!cn后报错无法使用

### 软件版本 / Verge Version

2.2.2

### 复现步骤 / To Reproduce

在rules里加入- GEOSITE,category-ai-!cn,AI
重启

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 24H2

### 日志(勿上传日志文件，请粘贴日志内容) / Log (Do not upload the log file, paste the log content directly)

ERROR - failed to parse config to yaml file

**Comment by HaoTian22** [comment]
已搜过目录下geosite.dat确认有这个条目

**Comment by Tychristine** [comment]
#3180

**Comment by HaoTian22** [comment]
看了下，本质上其实是test流程的问题，是/test目录不会自动更新？
毕竟在config的根目录下几个文件都是会定时更新的，到了test流程里用旧的不太合理

**Comment by Zeral-Zhang** [comment]
> 看了下，本质上其实是test流程的问题，是/test目录的geodata不会自动更新？ 我把/geosite.dat复制到/test/geosite.dat就正常了 毕竟在config的根目录下几个文件都是会定时更新的，到了test流程里用旧的不太合理

AppData目录下和其子目录 test下都没有更新，只更新test也不能用

**Comment by wonfen** [comment]
找到原因就好办了，下个版本修一下

**Comment by Azusa-mikan** [comment]
你好
```
ai-chat-no-cn:
    type: http
    interval: 600
    behavior: domain
    format: mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs"
```
可以先这样顶一下
