### ISSUE TITLE
能否增加一个分组功能

### ISSUE THREAD

**Issue by gxx2778** [clash-verge-rev/clash-verge-rev#326]
### Is your feature request related to a problem? Please describe.

很多用户都有多个订阅，但是有时候大家需要在某一固定区域的节点进行切换，所以是不是可以增加一个分组功能，把不同订阅的节点按用户自定义的规则进行分组。

### Describe the solution you'd like

比如我有5个订阅，我需要经常用到美国的节点，我就可以设置一个这美国节点的分组，这个分组中节点就是这5个订阅中的美国节点。而且还有必要在这分组中加上自动切换最优节点的功能，能自动切换这分组下延迟最低的节点。

### Describe alternatives you've considered

暂无

**Comment by shitouuuuu** [comment]
其实已经有的例如：
```
proxy-groups:
- name: 🇺🇸US节点
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: '300'
  filter: (US|LA|美国|美|洛)
  use:
  - 机场1
  - 机场2

proxy-providers:
  机场1:
    type: http
    url: 
    interval: 23200
    path: ./provider/proxy-providers/jichang1.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  机场2:
    type: http
    url: 
    interval: 23200
    path: ./provider/proxy-providers/jichang2.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

```
