### ISSUE TITLE
[BUG] 夸克网盘无法访问

### ISSUE THREAD

**Issue by brucmao** [clash-verge-rev/clash-verge-rev#3322]
### 问题描述 / Describe the bug

![Image](https://github.com/user-attachments/assets/eb91e290-7ff9-423b-9f07-4565c959e7a5)

使用系统代理模式，夸克网盘无法访问,无法打开 https://pan.quark.cn
相关配置如下
```
tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

dns:
  enable: true
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "+.market.xiaomi.com"
  nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  nameserver-policy:
    "rule-set:cn_domain,private_domain":
      - https://120.53.53.53/dns-query
      - https://223.5.5.5/dns-query
    "rule-set:geolocation-!cn":
      - "https://dns.cloudflare.com/dns-query"
      - "https://dns.google/dns-query"

rules:
  - RULE-SET,private_ip,direct,no-resolve
  - RULE-SET,cn_domain,Domestic

rule-providers:
  cn_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.list"
```

### 软件版本 / Verge Version

Version 2.2.3 (20250409.054607)

### 复现步骤 / To Reproduce

退出clash verge 就正常，打开clash verge 只用系统代理，无法访问夸克网盘，浏览器使用系统代理，

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

macOS Sequoia  Version 15.4

### 日志(勿上传日志文件，请粘贴日志内容) / Log (Do not upload the log file, paste the log content directly)

time="2025-04-11T13:19:00.003372000+08:00" level=debug msg="Auth success from 127.0.0.1:59272 -> "
time="2025-04-11T13:19:00.003523000+08:00" level=debug msg="[Rule] use default rules"
time="2025-04-11T13:19:00.003447000+08:00" level=debug msg="Auth success from 127.0.0.1:59273 -> "
time="2025-04-11T13:19:00.003642000+08:00" level=debug msg="[Rule] use default rules"
time="2025-04-11T13:19:00.003708000+08:00" level=debug msg="[DNS] resolve pan.quark.cn A from https://doh.pub:443/dns-query"
time="2025-04-11T13:19:00.003811000+08:00" level=debug msg="[DNS] resolve pan.quark.cn A from udp://8.8.8.8:53"
time="2025-04-11T13:19:00.003735000+08:00" level=debug msg="[DNS] resolve g.alicdn.com A from https://dns.alidns.com:443/dns-query"
time="2025-04-11T13:19:00.003742000+08:00" level=debug msg="[DNS] resolve g.alicdn.com A from udp://8.8.8.8:53"
time="2025-04-11T13:19:00.003750000+08:00" level=debug msg="[DNS] resolve g.alicdn.com A from https://doh.pub:443/dns-query"
time="2025-04-11T13:19:00.003753000+08:00" level=debug msg="[DNS] resolve pan.quark.cn A from https://dns.alidns.com:443/dns-query"
time="2025-04-11T13:19:00.064672000+08:00" level=debug msg="[DNS] pan.quark.cn --> [66.220.148.145] A from udp://8.8.8.8:53"
time="2025-04-11T13:19:00.064931000+08:00" level=debug msg="[DNS] resolve pan.quark.cn A from https://cloudflare-dns.com:443/dns-query"
time="2025-04-11T13:19:00.065186000+08:00" level=debug msg="[DNS] cache hit cloudflare-dns.com --> [104.16.248.249 104.16.249.249] A, expire at 2025-04-11 13:17:52"
time="2025-04-11T13:19:00.065321000+08:00" level=debug msg="[DNS] resolve cloudflare-dns.com A from udp://8.8.8.8:53"
time="2025-04-11T13:19:00.065207000+08:00" level=debug msg="[DNS] resolve pan.quark.cn A from https://dns.alidns.com:443/dns-query"
time="2025-04-11T13:19:00.065677000+08:00" level=debug msg="[DNS] resolve cloudflare-dns.com A from udp://223.6.6.6:53"
time="2025-04-11T13:19:00.065222000+08:00" level=debug msg="[DNS] resolve pan.quark.cn A from https://dns.google:443/dns-query"
time="2025-04-11T13:19:00.065865000+08:00" level=debug msg="[DNS] cache hit dns.google --> [8.8.4.4 8.8.8.8] A, expire at 2025-04-11 13:26:37"
time="2025-04-11T13:19:00.116291000+08:00" level=debug msg="[DNS] g.alicdn.com --> [49.119.124.248 49.119.124.249] A from https://dns.alidns.com:443/dns-query"
time="2025-04-11T13:19:00.137016000+08:00" level=debug msg="[DNS] cloudflare-dns.com --> [104.16.248.249 104.16.249.249] A from udp://223.6.6.6:53"
time="2025-04-11T13:19:00.142714000+08:00" level=debug msg="[DNS] pan.quark.cn --> [66.220.148.145] A from https://dns.alidns.com:443/dns-query"
time="2025-04-11T13:19:00.153912000+08:00" level=info msg="[TCP] 127.0.0.1:59273 --> g.alicdn.com:443 match RuleSet(cn_domain) using Domestic[direct]"
time="2025-04-11T13:19:05.005692000+08:00" level=warning msg="[TCP] dial Domestic (match RuleSet/cn_domain) 127.0.0.1:59272 --> pan.quark.cn:443 error: dial tcp 66.220.148.145:443: i/o timeout"
time="2025-04-11T13:19:05.007626000+08:00" level=debug msg="Auth success from 127.0.0.1:59281 -> "
time="2025-04-11T13:19:05.007831000+08:00" level=debug msg="[Rule] use default rules"
time="2025-04-11T13:19:05.007977000+08:00" level=debug msg="[DNS] cache hit pan.quark.cn --> [66.220.148.145] A, expire at 2025-04-11 13:19:05"
time="2025-04-11T13:19:05.008625000+08:00" level=debug msg="[DNS] resolve pan.quark.cn A from https://dns.alidns.com:443/dns-query"
time="2025-04-11T13:19:05.008947000+08:00" level=debug msg="[DNS] resolve pan.quark.cn A from https://doh.pub:443/dns-query"
time="2025-04-11T13:19:05.009292000+08:00" level=debug msg="[DNS] resolve pan.quark.cn A from udp://8.8.8.8:53"
time="2025-04-11T13:19:05.043872000+08:00" level=debug msg="[DNS] pan.quark.cn --> [66.220.148.145] A from udp://8.8.8.8:53"
time="2025-04-11T13:19:05.044359000+08:00" level=debug msg="[DNS] resolve pan.quark.cn A from https://cloudflare-dns.com:443/dns-query"
time="2025-04-11T13:19:05.044812000+08:00" level=debug msg="[DNS] resolve pan.quark.cn A from https://dns.google:443/dns-query"
time="2025-04-11T13:19:05.044978000+08:00" level=debug msg="[DNS] resolve pan.quark.cn A from https://dns.alidns.com:443/dns-query"
time="2025-04-11T13:19:05.120098000+08:00" level=debug msg="[DNS] pan.quark.cn --> [199.59.148.9] A from https://dns.alidns.com:443/dns-query"
time="2025-04-11T13:19:06.620242000+08:00" level=debug msg="Auth success from 127.0.0.1:59283 -> "
