### ISSUE TITLE
[求助] 如何用Merge设置DNS？

### ISSUE THREAD

**Issue by mai1202** [clash-verge-rev/clash-verge-rev#336]
比如说我想令国内IP走223.5.5.5，境外走Cloudflare的DoH应该怎么配置？

**Comment by xinhai-ai** [comment]
```
dns:
  use-hosts: true
  enable: true
  prefer-h3: true
  listen: 127.0.0.1:53
  ipv6: true
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  enhanced-mode: redir-host
  nameserver-policy:
    '+.internal.crop.com': '10.0.0.1'
  nameserver:
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
  fallback:
    - https://1.1.1.1/dns-query
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query

  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
```
 
这个是我的配置，国内走`223.5.5.5`和`1.12.12.12`的doh，国外走`1.1.1.1`的doh
同时要将系统dns设置为`127.0.0.1`
