### ISSUE TITLE
[BUG] dns字段配置无效

### ISSUE THREAD

**Issue by Zylsjsp** [clash-verge-rev/clash-verge-rev#343]
### Describe the bug

在config.yaml中添加了dns字段的fake-ip-filter列表 在verge中查看内核配置相应字段被成功整合 但是实际并不生效

### To Reproduce

1. config.yaml中添加
```yaml
dns: 
  fake-ip-filter:
  - '*tracker*'
```
2. 重启verge自动生成clash-verge.yaml 可以观察到yaml中配置正确
3. 使用dig查询tracker.byr.pt 指定dns服务器为8.8.8.8（被clash劫持） 得到结果仍是198.18.x.x的fakeip

### Platform

Linux

### System Version

Arch Linux

### Software Version

1.4.11

### Additional Information

qbittorrent在fakeip模式下容易出现爆内存 推测可能是libtorrent的dns缓存和fakeip存在不兼容的问题 希望可以通过配置fakeip filter将tracker从fakeip中过滤掉

**Comment by wonfen** [comment]
在“设置”下的“当前配置”查看是否有dns的配置被载入，如果有，就说明被正确载入了，检查其他地方的问题。
如果没有，就检查你配置文件的写法。

**Comment by Zylsjsp** [comment]
当前配置的dns配置显示是正确的 例如：
```yaml
dns:
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*tracker*'
  nameserver:
  - 114.114.114.114
  - 223.5.5.5
  - 8.8.8.8
  fallback: []
```
但是dig返回的仍然是198.18.x.x段的fakeip 请问下一步从哪些地方排查呢
