### ISSUE TITLE
[Feature] 更新GeoData时希望能够更新geoip.dat和geosite.dat

### ISSUE THREAD

**Issue by emptylight370** [clash-verge-rev/clash-verge-rev#3471]
### 功能描述 / Feature description

在更新GeoData的时候下载新的`geoip.dat`和`geosite.dat`进行替换。

### 使用场景 / Use case

在更新GeoData的时候只会更新`Country.mmdb`数据库，`geoip.dat`和`geosite.dat`不会更新，需要手动下载新文件替换。

### 适用系统 / Target OS

- [x] windows
- [ ] macos
- [ ] linux

**Comment by emptylight370** [comment]
> 提供你的 geox-url 配置

没找到这个配置，也没找到可以配置的地方

**Comment by xuanyuan0408** [comment]
> > 提供你的 geox-url 配置
> 
> 没找到这个配置，也没找到可以配置的地方

- **那就是没有配置的问题！请参考下面的例子 加入到 你yaml配置文件** 

```
#自定义 geodata url
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"

geo-auto-update: false # 是否自动更新 geodata
geo-update-interval: 24 # 更新间隔，单位：小时
```
