### ISSUE TITLE
[Feature]建议增加meta的自定 GEO 下载地址

### ISSUE THREAD

**Issue by letterk** [clash-verge-rev/clash-verge-rev#37]
既然现在只剩下虚空终端, 希望能支持`geox-url`功能
```
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
```
每次启动clash verge, 从内核资源目录`Clash Verge\resources\`复制到`.config\clash-verge`应用目录, 这个操作逻辑实在是诡异
