### ISSUE TITLE
[BUG] failed to connect to http://127.0.0.1:59692/

### ISSUE THREAD

**Issue by taosimple** [clash-verge-rev/clash-verge-rev#3905]
### 问题描述 / Describe the bug

开启全局模式后，在 Android Studio run flutter 会抛出如下异常：
> Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk
Installing build/app/outputs/flutter-apk/app-debug.apk...
I/flutter ( 2123): [IMPORTANT:flutter/shell/platform/android/android_context_gl_impeller.cc(94)] Using the Impeller rendering backend (OpenGLES).
Error connecting to the service protocol: failed to connect to http://127.0.0.1:59692/dIn7zj3I0RY=/ HttpException: Connection closed before full header was received, uri = http://127.0.0.1:59692/dIn7zj3I0RY=/ws
the Dart compiler exited unexpectedly.

- 切换到规则模式能正常运行
- 全局模式+命令行：flutter run 也能正常运行

这看起来是个疑难杂症，但是还是想问问有什么办法在全局模式下正常运行，总是切换有点麻烦。
- 以前没有遇到过这个问题，好像是升级 2.3.1 后遇到到，刚刚又升级到了2.3.2 还是没解决
- 尝试过在 clash-verge.yaml 加：`- IP-CIDR,127.0.0.1/8,DIRECT,no-resolve` 但是无效
- 试过关闭 Android Studio 的 proxy 也没效果

### 软件版本 / Verge Version

Version 2.3.2 (2.3.2)

### 复现步骤 / To Reproduce

在Android Studio 点运行

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.6.1 (23G93)

### 日志(勿上传日志文件，请粘贴日志内容) / Log (Do not upload the log file, paste the log content directly)

06-26 22:26:14INFO
[TCP] 127.0.0.1:63451 --> 127.0.0.1:63450 using GLOBAL

**Comment by Ahaohaohao** [comment]
### 全局 ≠ 规则 全局 全部走一个出口 规则是通过分流匹配（你分流是匹配上了） 

` IP-CIDR,127.0.0.1/8,DIRECT,no-resolve`

@taosimple 是有什么需求？要走全局？

**Comment by taosimple** [comment]
@Ahaohaohao 谢谢回复
是因为像 Claude, Gemini 这些工具不走全局用不了，能检测到在不支持国家。
用了全局就连接不到flutter本地服务器，即使用规则先跑起来再切换到全局也会断开又要重新 run。
奇怪的是在命令行里跑就没问题，以前也没碰到

**Comment by Tangerinell** [comment]
如果配置好规则 这些工具都是可以正常使用的。如果规则里只写match,proxy，又何尝不是另一种意义上的全局。我认为还是和你的rules有关系

**Comment by taosimple** [comment]
> 如果配置好规则 这些工具都是可以正常使用的。如果规则里只写match,proxy，又何尝不是另一种意义上的全局。我认为还是和你的rules有关系

@blackTangerine11 你的意思是开规则模式，通过修改rules来绕开 Claude, Gemini 这些工具检测是吗？

**Comment by Dragon1573** [comment]
我是在 CVR 里编辑代理组，将订阅提供的所有节点抽特定一部分形成专用的组。

```yaml
prepend: []
append:
  - type: 'load-balance'
    name: '特殊站点'
    interval: 500
    timeout: 5000
    max-failed-times: 5
    lazy: true
    proxies:
      # 这里面的组是凭经验抽的，会根据实测进一步调整里面的节点
      - '🇯🇵日本-01 T 1.0x'
      - '🇹🇼台湾-01 T 1.0x'
      - '🇸🇬新加坡-01 T 1.0x'
      - '🇰🇷韩国-01 T 1.0x'
      - '🇲🇾马来西亚-01 T 1.0x'
      - '🇻🇳越南-01 T 1.0x'
      - '🇵🇭菲律宾-01 T 1.0x'
      - '🇮🇩印尼-01 T 1.0x'
      - '🇹🇭泰国-01 T 1.0x'
      - '🇵🇰巴基斯坦-01 T 1.0x'
    # 我自己只用 Gemini ，其他平台不保证一样可用
    url: 'https://gemini.google.com/app'
    expected-status: 200
delete: []
```

再编辑规则，把 Gemini 指定用这个专用组。

```yaml
prepend:
  # Google Gemini
  - 'DOMAIN-KEYWORD,gemini,特殊站点'
  # Microsoft Copilot
  - 'DOMAIN-KEYWORD,copilot,特殊站点'
append: []
delete: []
```
