### ISSUE TITLE
[BUG] 内网域名无法解析

### ISSUE THREAD

**Issue by taotao365s** [clash-verge-rev/clash-verge-rev#3913]
### 问题描述 / Describe the bug

内网的域名无法解析
![Image](https://github.com/user-attachments/assets/c8c25efb-293d-4f5e-ad34-737e03fe4134)

### 软件版本 / Verge Version

2.3.2

### 复现步骤 / To Reproduce

配置内网域名，domain-suffix,xxx.org,direct,无法解析ip

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

15.5

### 日志(勿上传日志文件，请粘贴日志内容) / Log (Do not upload the log file, paste the log content directly)

-

**Comment by Tychristine** [comment]
把你的`hosts`以及 `dns.nameserver-policy`的配置提交上来

**Comment by Dragon1573** [comment]
请同步检查你 CVR 实例的当前订阅配置。

部分鸡场提供的配置订阅链接，其内容自带了一段 DNS 设置。在关闭 DNS 覆写的情况下，此默认 DNS 配置不含你内网 DNS 服务器。可以尝试开启 DNS 覆写，将你的内网 DNS 增加到「直链域名服务器」列表。

**Comment by Ahaohaohao** [comment]
内网需要使用内网DNS解析 你公共DNS解析不了 参考文档 https://www.clashverge.dev/faq/other.html#_5

**Comment by chongiscool** [comment]
你好，大佬们 @Ahaohaohao @Tychristine @Dragon1573 ，需要你们的帮助，配置一下午了，还是 dns解析失败，先谢谢了！
 
## 描述
我是上个月 用相同软件和版本，配置【直连规则的 和 nameserver-policy 】行的。现在win11系统被重装，就重新安装当前版本，但这次不行，上 google 和 bilibili 都可以，就公司内网不行，也许我忽略了一些因素。

## 版本
 v2.2.3

## 错误截图

<img width="862" height="437" alt="Image" src="https://github.com/user-attachments/assets/a69bbdf7-bb50-432e-908c-2d946d8e0f71" />

<img width="762" height="479" alt="Image" src="https://github.com/user-attachments/assets/13f932d5-23af-4502-9fef-d1df4070cb2f" />

## 使用截图
开启代理时，会关闭了 dns复写设置的。注意：dns复写，我没敢修改，都是默认的。

<img width="448" height="756" alt="Image" src="https://github.com/user-attachments/assets/892f5e01-1494-4975-ac35-dd9ff1ae3e77" />

<img width="597" height="701" alt="Image" src="https://github.com/user-attachments/assets/28bc88ee-62c1-484b-8929-5b1130e7b8c1" />

<img width="589" height="620" alt="Image" src="https://github.com/user-attachments/assets/ed8dda25-b85a-494e-8d3b-a5ed543a760b" />

<img width="593" height="621" alt="Image" src="https://github.com/user-attachments/assets/b6e697f1-b8e3-42bf-be38-531ef4321f39" />

## 我的 clash verge 配置文件的部分。
```yaml
port: 7893
socks-port: 7891
redir-port: 7892
mixed-port: 7890
allow-lan: false
bind-address: '*'
mode: rule
log-level: silent
ipv6: false
external-controller: '127.0.0.1:9090'
dns:
    enable: true
    listen: '127.0.0.1:53'
    ipv6: true
    default-nameserver: [223.5.5.5, 119.29.29.29]
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    fake-ip-filter: ['*.lan', '*.linksys.com', '*.linksyssmartwifi.com', swscan.apple.com, mesu.apple.com, '*.msftconnecttest.com', '*.msftncsi.com', 'time.*.com', 'time.*.gov', 'time.*.edu.cn', 'time.*.apple.com', 'time1.*.com', 'time2.*.com', 'time3.*.com', 'time4.*.com', 'time5.*.com', 'time6.*.com', 'time7.*.com', 'ntp.*.com', 'ntp.*.com', 'ntp1.*.com', 'ntp2.*.com', 'ntp3.*.com', 'ntp4.*.com', 'ntp5.*.com', 'ntp6.*.com', 'ntp7.*.com', '*.time.edu.cn', '*.ntp.org.cn', +.pool.ntp.org, time1.cloud.tencent.com, +.music.163.com, '*.126.net', musicapi.taihe.com, music.taihe.com, songsearch.kugou.com, trackercdn.kugou.com, '*.kuwo.cn', api-jooxtt.sanook.com, api.joox.com, joox.com, +.y.qq.com, +.music.tc.qq.com, aqqmusic.tc.qq.com, +.stream.qqmusic.qq.com, '*.xiami.com', +.music.migu.cn, +.srv.nintendo.net, +.stun.playstation.net, 'xbox.*.microsoft.com', +.xboxlive.com, localhost.ptlogin2.qq.com, proxy.golang.org, 'stun.*.*', 'stun.*.*.*', '*.mcdn.bilivideo.cn', +.fcbox.com]
    nameserver: ['tls://223.5.5.5:853', 'tls://1.12.12.12:853', 'https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    nameserver-policy:
        '+.mycompany.com': '10.204.243.1'
    fallback-filter: { geoip: false, ipcidr: [240.0.0.0/4, 0.0.0.0/32, 127.0.0.1/32] }

rules:
    - 'DOMAIN-SUFFIX,mycompany.com,DIRECT'
    - 'DOMAIN-KEYWORD,mycompany,DIRECT'
```

**Comment by chongiscool** [comment]
## 补充描述
上个月 我成功配置时，还写了事后笔记，也许当时还配置了其他地方，我忘记了。比如：fake ip 过滤 公司的域名。但这次我没动它，直接安装【我的笔记】就失败了，也不敢随便乱设置了。

## 笔记如下

<img width="748" height="491" alt="Image" src="https://github.com/user-attachments/assets/7bd15b89-4976-42be-a9e2-05c2c5e6ee05" />

**Comment by Dragon1573** [comment]
可以参考一下？

<details><summary>我的 DNS 覆写配置</summary><p>

⚠️ 需要注意，CVR 的配置文件貌似不支持注释，记得把注释删掉。

```yaml
dns:
  enable: true
  listen: ':53'
  enhanced-mode: 'fake-ip'
  fake-ip-range: '198.18.0.1/16'
  fake-ip-filter-mode: 'blacklist'
  prefer-h3: true
  respect-rules: true
  use-hosts: true
  use-system-hosts: true
  ipv6: true
  fake-ip-filter:
    - '*.lan'
    - '*.local'
    - '*.arpa'
    - 'time.*.com'
    - 'ntp.*.com'
    - 'time.*.com'
    - '+.market.xiaomi.com'
    - 'localhost.ptlogin2.qq.com'
    - '*.msftncsi.com'
    - 'www.msftconnecttest.com'
  default-nameserver:
    # 公司内网 DNS 服务器
    - '10.1.18.1'
    - 'system'
    - '223.6.6.6'
    - '8.8.8.8'
    - '2400:3200::1'
    - '2001:4860:4860::8888'
  nameserver:
    - 'system'
    - '8.8.8.8'
    - 'https://doh.pub/dns-query'
    - 'https://dns.alidns.com/dns-query'
  direct-nameserver-follow-policy: true
  fallback-filter:
    geoip: true
    geoip-code: 'CN'
    ipcidr:
      - '240.0.0.0/4'
      - '0.0.0.0/32'
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
  nameserver-policy:
    # 这个域名调成本机＋公司内网 DNS 来解析
    +.local:
      - 'localhost'
      - '10.1.18.1'
  proxy-server-nameserver:
    - 'https://doh.pub/dns-query'
    - 'https://dns.alidns.com/dns-query'
    - 'tls://223.5.5.5'
  direct-nameserver:
    # 公司内网 DNS 服务器
    - '10.1.18.1'
    - 'system'
    - '223.6.6.6'
    - '8.8.8.8'
    - '2400:3200::1'
    - '2001:4860:4860::8888'
    - '8.8.8.8'
    - 'https://doh.pub/dns-query'
    - 'https://dns.alidns.com/dns-query'
hosts:
  alist.dragon1573.local: '10.35.1.173'
```

<img width="1000" height="808" alt="Image" src="https://github.com/user-attachments/assets/63384682-577d-49b8-b6d4-5d2d22e2890a" />

</p></details>
