### ISSUE TITLE
[BUG]有多个proxy-provider时 节点排序问题

### ISSUE THREAD

**Issue by wanzhique** [clash-verge-rev/clash-verge-rev#413]
### Describe the bug

有多个proxy-provider时 proxy-groups中的节点选择有时不按照proxy-provider的顺序排列

### To Reproduce

```
proxy-providers:
  p1:
    type: http
    url: "https://xxx"
    interval: 86400
  p2:
    type: http
    url: "https://xxx"
    interval: 86400
  p3:
    type: http
    url: "https://xxx"
    interval: 86400

proxy-groups:
  - name: 🚀 节点选择
    type: select
    include-all: true
    proxies:
      - DIRECT
```
有时会出现不按照p1 p2 p3的顺序排列节点
然后重新加载配置文件顺序就正常了

### Platform

Windows

### System Version

win10

### Software Version

1.5.1
