### ISSUE TITLE
[BUG]更新GeoData的时并没有一起更新Country.mmdb文件

### ISSUE THREAD

**Issue by lainbo** [clash-verge-rev/clash-verge-rev#422]
### Describe the bug

在定义了`geox-url`相关字段后, geoip和geosite数据可以被正常下载, 但是mmdb的数据没有下载

[参考文档](https://wiki.metacubex.one/config/general/?h=mmdb#geo_3)

### To Reproduce

1. 定义如下配置
```yml
geox-url:
  geoip: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat
  geosite: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
```
2. 点击设置-更新GeoData
3. 观察发现应用目录中的Country.mmdb文件没有被更新

### Platform

Windows

### System Version

Windows11

### Software Version

1.5.2
