### ISSUE TITLE
[BUG]error: dns resolve failed: couldn't find ip

### ISSUE THREAD

**Issue by boa-z** [clash-verge-rev/clash-verge-rev#467]
### Describe the bug

Just as title and log shows. And I can't connect some websites while YouTube and Google's connection are normal.

### To Reproduce

I'm sorry that I don't know.

### Platform

MacOS

### System Version

macOS 14.3

### Software Version

1.5.4

### Log

02-26 23:00:04WARNING
[TCP] dial DIRECT (match DomainSuffix/microsoft.com) 127.0.0.1:57136 --> self.events.data.microsoft.com:443 error: dns resolve failed: couldn't find ip
02-26 23:00:09WARNING
[TCP] dial DIRECT (match DomainSuffix/microsoft.com) 127.0.0.1:57175 --> self.events.data.microsoft.com:443 error: dns resolve failed: couldn't find ip

### Additional Information

enabled TUN and system proxys

DNS server in the system internet setting has been set to 8.8.8.8

**Comment by MrCloudyGod** [comment]
同样的问题，更新之后经常出现，所有节点全部error，左下角也没有任何上传下载速度，但是换代理软件是正常的

**Comment by jaoyina** [comment]
我今天第一次使用最新的1.54，也是这个问题，我还以为哪里设置错了。找了半天。

**Comment by MystiPanda** [comment]
是否使用tun模式？

**Comment by boa-z** [comment]
Yes, TUN is enabled.
Sent from my iPhone

On Feb 27, 2024, at 23:11, MystiPanda ***@***.***> wrote:

﻿

是否使用tun模式？

**Comment by ansoncloud8** [comment]
Corn has the same problem
这边也是同样的问题,访问本地其它vpn代码的内网域名时就会现在的问题

aa.com:443 error: dns resolve failed: couldn't find ip

**Comment by light0x00** [comment]
Same problem encountered.  When switch the proxies mode as "Direct",  then access Intranet  name,  the error will happen.

**Comment by xizhouli** [comment]
我也遇到了同样的问题

使用了 TUN 模式

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/153695562/8b4f5187-4fd1-4502-93ed-200120b91d76)

DNS 配置如下：

```yml
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - localhost.ptlogin2.qq.com
  - dns.msftncsi.com
  - www.msftncsi.com
  - www.msftconnecttest.com
  nameserver:
  - 223.5.5.5
  - 223.6.6.6
  fallback:
  - tls://223.5.5.5:853
  - https://223.5.5.5/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
```

**Comment by panwanke** [comment]
同样的问题，修改 nameserver 和 fallback 也无法正常获取国内网址的ip，国外网址可以正常访问

**Comment by freeNestor** [comment]
类似问题，也是tun模式下，apple.com和icloud.com域无法解析（跟cname有关？），但其他解析正常的。clash版本1.5.8
```
03-14 09:36:05WARNING
[TCP] dial Apple (match DomainSuffix/apple.com) 198.18.0.1:50420 --> weather-data.apple.com:443 error: dns resolve failed: couldn't find ip
03-14 09:36:26WARNING
[TCP] dial Apple (match DomainSuffix/apple.com) 198.18.0.1:50446 --> gdmf.apple.com:443 error: dns resolve failed: couldn't find ip
03-14 09:36:26WARNING
[TCP] dial Apple (match DomainSuffix/apple.com) 198.18.0.1:50445 --> gdmf.apple.com:443 error: dns resolve failed: couldn't find ip
03-14 09:36:31WARNING
[TCP] dial Apple (match DomainSuffix/apple.com) 198.18.0.1:50467 --> gdmf.apple.com:443 error: no ip address
03-14 09:36:31WARNING
[TCP] dial Apple (match DomainSuffix/apple.com) 198.18.0.1:50468 --> gdmf.apple.com:443 error: no ip address
03-14 09:36:36WARNING
[TCP] dial Apple (match DomainSuffix/apple.com) 198.18.0.1:50467 --> gdmf.apple.com:443 error: dns resolve failed: couldn't find ip
03-14 09:36:36WARNING
[TCP] dial Apple (match DomainSuffix/apple.com) 198.18.0.1:50468 --> gdmf.apple.com:443 error: dns resolve failed: couldn't find ip
03-14 09:36:41WARNING
[TCP] dial Apple (match DomainSuffix/apple.com) 198.18.0.1:50501 --> gdmf.apple.com:443 error: no ip address
03-14 09:36:41WARNING
[TCP] dial Apple (match DomainSuffix/apple.com) 198.18.0.1:50502 --> gdmf.apple.com:443 error: no ip address
03-14 09:37:55WARNING
[TCP] dial Apple (match DomainSuffix/icloud.com) 198.18.0.1:50946 --> mask.icloud.com:443 error: dns resolve failed: couldn't find ip
03-14 09:37:55WARNING
[TCP] dial Apple (match DomainSuffix/icloud.com) 198.18.0.1:50925 --> p42-caldav.icloud.com:443 error: dns resolve failed: couldn't find ip
```
关闭clash后解析，是可以解析的，先cname后A记录
<img width="748" alt="image" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/19606302/fa71edbf-e67a-4fd6-be38-7357f9b52088">

```
dns:
  enable: true
  default-nameserver:
  - 223.5.5.5
  - 223.6.6.6
  nameserver-policy:
    http-inputs-notion.splunkcloud.com,+.notion-static.com,+.notion.com,+.notion.new,+.notion.site,+.notion.so: tls://dns.jerryw.cn
    geosite:geolocation-!cn:
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
    geosite:cn:
    - 223.5.5.5
    - 223.6.6.6
  nameserver:
  - https://dns.google/dns-query
  - https://cloudflare-dns.com/dns-query
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fallback: []
```
