### ISSUE TITLE
[BUG] 节点延迟检测错误

### ISSUE THREAD

**Issue by CrayonSSR** [clash-verge-rev/clash-verge-rev#534]
### Describe the bug

**其中一个订阅源节点延迟检测全部显示为Error**

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/93774795/239b04ca-09d3-4f04-b103-2c6545fe87e6)

**但该源节点实际可以通过测试，也可以正常浏览网页/观看视频**

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/93774795/39a97af6-7405-450b-beb8-e767cff37535)

**而且在同类软件，clash for window中延迟检测也能正常通过**

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/93774795/c1a098b9-b394-4dd8-a522-4a8e94e8ebff)

### To Reproduce

1.打开软件

2.点击延迟检测

3.节点会在1s内出现检测结果Error

### Platform

Windows

### System Version

win10 2024.02

### Software Version

1.5.5

### Log

```log
[TCP] 127.0.0.1:55170 --> www.google.com:443 match Match using 全局选择[US_05]
03-10 00:47:53INFO
[TCP] 127.0.0.1:55172 --> www.github.com:443 match Match using 全局选择[US_05]
03-10 00:47:54INFO
[TCP] 127.0.0.1:55174 --> github.com:443 match Match using 全局选择[US_05]
03-10 00:48:46INFO
[TCP] 127.0.0.1:55344 --> github.com:443 match Match using 全局选择[US_05]
03-10 00:48:46INFO
[TCP] 127.0.0.1:55346 --> github.githubassets.com:443 match Match using 全局选择[US_05]
03-10 00:48:47INFO
[TCP] 127.0.0.1:55350 --> github.githubassets.com:443 match Match using 全局选择[US_05]
03-10 00:48:48INFO
[TCP] 127.0.0.1:55348 --> content-autofill.googleapis.com:443 match Match using 全局选择[US_05]
03-10 00:48:49INFO
[TCP] 127.0.0.1:55352 --> avatars.githubusercontent.com:443 match Match using 全局选择[US_05]
03-10 00:48:49INFO
[TCP] 127.0.0.1:55354 --> avatars.githubusercontent.com:443 match Match using 全局选择[US_05]
03-10 00:48:49INFO
[TCP] 127.0.0.1:55355 --> avatars.githubusercontent.com:443 match Match using 全局选择[US_05]
03-10 00:48:52INFO
[TCP] 127.0.0.1:55358 --> optimizationguide-pa.googleapis.com:443 match Match using 全局选择[US_05]
03-10 00:50:12INFO
[TCP] 127.0.0.1:55369 --> github.com:443 match Match using 全局选择[US_05]
```

### Additional Information

如下是配置文件参考，文件存放在本地的局域网内的一个http静态文件服务

其中v1的节点可以正常显示延迟，而v2全是error，这里实际省略了后面也能正常显示延迟的v3。

```yaml
  v1@vless:
    type: http
    url: "http://192.168.1.34:22652/clash/proxies@v1.yaml"
    path: ./Clash/proxies-v1@vless.yaml
    interval: 604800
    health-check:
      lazy: true
      enable: true
      interval: 1110
      url: http://www.google.com/generate_204

  v2@vless:
    type: http
    url: "http://192.168.1.34:22652/clash/proxies@v2.yaml"
    path: ./Clash/proxies-v2@vless.yaml
    interval: 604800
    health-check:
      lazy: true
      enable: true
      interval: 1110
      url: http://www.google.com/generate_204

proxy-groups:
  - name: 全局选择
    type: select
    proxies:
      - 选择节点
  - name: 选择节点
    type: select
    use:
      - v1@vless
      - v2@vless
```
