### ISSUE TITLE
[BUG] 直连模式的域名无法访问

### ISSUE THREAD

**Issue by sixgodfan** [clash-verge-rev/clash-verge-rev#559]
### Describe the bug

今日刚从clash-verge转到clash-verge-rev，clash全局代理加上SwitchyOmega，基本一样的配置设置（除了字段配置不知道在哪添加）。我发现SwitchyOmega直连的域名会无法访问，提示ERR_NAME_NOT_RESOLVED。是我设置问题还是软件本身就这样？
还有个问题就是clash-verge开启tun时鼠标移动至笔记本wifi图标那里会显示出meta，而clash-verge-rev 没有，都不确认是否正在以tun模式运行中

### To Reproduce

目前的最新版，安装/便携版都尝试过了。

### Platform

Windows

### System Version

win 11

### Software Version

1.5.6

**Comment by dongchengjie** [comment]
没用过SwitchyOmega，但是猜测你的目的是使用SwitchyOmega指向mixed端口，禁用使用系统代理防止影响到其他使用系统代理的应用。或者说抛弃Clash的规则转而使用SwitchyOmega配置路由。可能是你的SwitchyOmega规则错了或者clash配置dns出错了
移动到托盘图标小猫咪上，不是有显示"**Tun模式: off**"吗，另外TUN模式的猫咪颜色是绿色的

**Comment by dongchengjie** [comment]
> 谢谢回复。相同配置clash-verge下是没问题的。SwitchyOmega使用mixed的端口，全局代理，系统dns为198.18.0.2。SwitchyOmega改为直接链接 模式，就提示ERR_NAME_NOT_RESOLVED。按理来说即使是SwitchyOmega直连，dns也是经过clash的dns模块来解析

你把clash配置的dns改为false禁用试试，如果好了就说明是clash的dns有问题.
或者试试下面的DNS配置
```yaml
dns:
  enable: true
  ipv6: true
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
  use-hosts: true
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
  fallback-filter: 
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
```
