### ISSUE TITLE
[Feature] 能真正 Merge 的 Merge

### ISSUE THREAD

**Issue by xxxuuu** [clash-verge-rev/clash-verge-rev#648]
### Is your feature request related to a problem? Please describe.

Merge 模式目前看起来会覆盖掉原配置，并没有 "merge"，例如原配置为：
```yaml
host:
  A.com: 127.0.0.1
```

希望增加一条
```yaml
host:
  B.com: 127.0.0.1
```

期望结果：
```yaml
host:
  A.com: 127.0.0.1
  B.com: 127.0.0.1
```

但目前来看会直接覆盖掉整个 `host`

### Describe the solution you'd like

对于其它字段，应该能 'merge' 配置。如果觉得该方案可行，我可以提交一个 PR 来修改

### Describe alternatives you've considered

无
