### ISSUE TITLE
[BUG] mac 的Tun 模式堆栈Mixed未按照预期工作

### ISSUE THREAD

**Issue by screw-hand** [clash-verge-rev/clash-verge-rev#667]
### Describe the bug

使用Mixed的Tun模式堆栈，无法正确代理
bing可正常打开，google连接超时
连接界面中无任何输出信息

### To Reproduce

1. 关闭Tun模式
2. 将Tun 模式堆栈设置成Mixed
3. 重启启动Tun 模式，再次对clash内核授权

### Platform

MacOS

### System Version

13.2.1

### Software Version

1.5.9

### Log

# clash-verge.yaml

```yaml
# Generated by Clash Verge

mode: rule
mixed-port: 7788
socks-port: 7788
port: 7788
allow-lan: false
log-level: info
ipv6: false
secret: '1212'
external-controller: 127.0.0.1:9097
tun:
  stack: mixed
  device: Meta
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  strict-route: true
  mtu: 9000
  enable: true
dns:
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - 114.114.114.114
  - 223.5.5.5
  - 8.8.8.8
  fallback: []
```

# verge.yaml

```yaml
# Clash Verge Config

app_singleton_port: null
app_log_level: null
language: zh
theme_mode: system
tray_event: null
env_type: bash
start_page: /
startup_script: null
traffic_graph: true
enable_memory_usage: true
enable_group_icon: true
common_tray_icon: false
menu_icon: null
sysproxy_tray_icon: false
tun_tray_icon: false
enable_tun_mode: true
enable_auto_launch: true
enable_silent_start: true
enable_system_proxy: false
enable_proxy_guard: false
system_proxy_bypass: null
proxy_guard_duration: 30
theme_setting:
  primary_color: '#ba6427'
  secondary_color: '#f00'
  primary_text: '#ccc'
  secondary_text: null
  info_color: ''
  error_color: null
  warning_color: null
  success_color: null
  font_family: HarmonyOS Sans SC, HarmonyOS Sans
  css_injection: ''
web_ui_list: null
clash_core: clash-meta
hotkeys:
- open_or_close_dashboard,CTRL+ALT+D
auto_close_connection: true
auto_check_update: null
default_latency_test: null
default_latency_timeout: null
enable_builtin_enhanced: true
proxy_layout_column: null
test_list:
- uid: HLqNyEpbKu3fH8VwXupwd
  name: Apple
  icon: https://www.apple.com/favicon.ico
  url: https://www.apple.com
- uid: Qfp04UM-kUV_P0y7bpYFP
  name: GitHub
  icon: <svg width="98" height="96" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M48.854 0C21.839 0 0 22 0 49.217c0 21.756 13.993 40.172 33.405 46.69 2.427.49 3.316-1.059 3.316-2.362 0-1.141-.08-5.052-.08-9.127-13.59 2.934-16.42-5.867-16.42-5.867-2.184-5.704-5.42-7.17-5.42-7.17-4.448-3.015.324-3.015.324-3.015 4.934.326 7.523 5.052 7.523 5.052 4.367 7.496 11.404 5.378 14.235 4.074.404-3.178 1.699-5.378 3.074-6.6-10.839-1.141-22.243-5.378-22.243-24.283 0-5.378 1.94-9.778 5.014-13.2-.485-1.222-2.184-6.275.486-13.038 0 0 4.125-1.304 13.426 5.052a46.97 46.97 0 0 1 12.214-1.63c4.125 0 8.33.571 12.213 1.63 9.302-6.356 13.427-5.052 13.427-5.052 2.67 6.763.97 11.816.485 13.038 3.155 3.422 5.015 7.822 5.015 13.2 0 18.905-11.404 23.06-22.324 24.283 1.78 1.548 3.316 4.481 3.316 9.126 0 6.6-.08 11.897-.08 13.526 0 1.304.89 2.853 3.316 2.364 19.412-6.52 33.405-24.935 33.405-46.691C97.707 22 75.788 0 48.854 0z" fill="#000000"/></svg>
  url: https://www.github.com
- uid: -NJPc8qfnOQUqRUBDHxND
  name: Google
  icon: <svg enable-background="new 0 0 48 48" height="48" viewBox="0 0 48 48" width="48" xmlns="http://www.w3.org/2000/svg"><path d="m43.611 20.083h-1.611v-.083h-18v8h11.303c-1.649 4.657-6.08 8-11.303 8-6.627 0-12-5.373-12-12s5.373-12 12-12c3.059 0 5.842 1.154 7.961 3.039l5.657-5.657c-3.572-3.329-8.35-5.382-13.618-5.382-11.045 0-20 8.955-20 20s8.955 20 20 20 20-8.955 20-20c0-1.341-.138-2.65-.389-3.917z" fill="#ffc107"/><path d="m6.306 14.691 6.571 4.819c1.778-4.402 6.084-7.51 11.123-7.51 3.059 0 5.842 1.154 7.961 3.039l5.657-5.657c-3.572-3.329-8.35-5.382-13.618-5.382-7.682 0-14.344 4.337-17.694 10.691z" fill="#ff3d00"/><path d="m24 44c5.166 0 9.86-1.977 13.409-5.192l-6.19-5.238c-2.008 1.521-4.504 2.43-7.219 2.43-5.202 0-9.619-3.317-11.283-7.946l-6.522 5.025c3.31 6.477 10.032 10.921 17.805 10.921z" fill="#4caf50"/><path d="m43.611 20.083h-1.611v-.083h-18v8h11.303c-.792 2.237-2.231 4.166-4.087 5.571.001-.001.002-.001.003-.002l6.19 5.238c-.438.398 6.591-4.807 6.591-14.807 0-1.341-.138-2.65-.389-3.917z" fill="#1976d2"/></svg>
  url: https://www.google.com
- uid: Z7SFV3RKPN9UYbX48MPhM
  name: chatgpt
  icon: https://static.vecteezy.com/system/resources/previews/021/608/790/large_2x/chatgpt-logo-chat-gpt-icon-on-black-background-free-vector.jpg
  url: https://chat.openai.com
auto_log_clean: 3
window_size_position:
- 1217.0
- 879.0
- 134.0
- 56.0
window_is_maximized: false
enable_random_port: false
verge_mixed_port: 7788
verge_socks_port: 7788
verge_port: 7788
```

### Additional Information

非常感谢开发者团队的辛苦工作和贡献。如果需要，我很乐意提供更多信息，如日志文件，或协助进行问题的调试和排查。请随时告诉我如何参与，期待能为项目贡献一份力量。
