### ISSUE TITLE
[Feature] 在界面中直接编辑rule provider

### ISSUE THREAD

**Issue by MJRT** [clash-verge-rev/clash-verge-rev#698]
### 功能描述 / Feature description

类似clash for windows, 添加一个编辑按钮, 可以直接编辑rule provider, 保存并刷新. 现在想编辑的话只能手动找到文件进行编辑, 然后回到app刷新, 比较麻烦
当前的clash verge:
![311522256-baea7391-ef3a-4b55-afac-8036ebe62c67](https://github.com/clash-verge-rev/clash-verge-rev/assets/17826582/d03ae370-76d6-4c8a-9881-88f2a4e5de61)

cfw中的例子: 侧边栏点击"provider" -> 在对应的provider中点击"<>" 进行编辑
![311522259-dbad9cfb-ad66-46ed-a197-c84a60de7242](https://github.com/clash-verge-rev/clash-verge-rev/assets/17826582/48a29f22-46b7-49b4-9f48-14149d759ef8)

### 使用场景 / Use case

可以更方便的修改rule provider

**Comment by MystiPanda** [comment]
如果rule-set需要再次手动编辑那使用rule-set意义何在

**Comment by MJRT** [comment]
之前的讨论在[issue-567](https://github.com/clash-verge-rev/clash-verge-rev/issues/567), 总结下主要是讨论修改rule provider和其中的rule 会不会被订阅更新给覆盖,

结论是不会被覆盖, 本地的规则能和远程共存的, 这里给出我用了一年多cfw+verge的配置例子吧:

clash verge config: (新建一个merge config完成后enable)
```
prepend-rules:
  - RULE-SET,additional-us,🇺🇸 美国流量
  - RULE-SET,anti-ad,REJECT
prepend-rule-providers:
  anti-ad:
    behavior: "domain"
    type: http
    url: "https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-clash.yaml"
    format: yaml
    interval: 86400
    path: ./anti-ad.yaml
  additional-us:
    type: file
    behavior: classical
    path: "D://OneDrive//app//clash//additional-ruls//us.yaml"  
```
cfw: (为对应远程订阅链接设置parser, 且每个parser要与远程url匹配)
```
parsers:
  - url: https://xxxxx
    yaml:	
      mix-rule-providers:
        anti-ad:
          behavior: "domain"
          type: http
          url: "https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-clash.yaml"
          format: yaml
          interval: 86400
          path: ./anti-ad.yaml
        additional-us:
          type: file
          behavior: classical
          path: "D://OneDrive//app//clash//additional-ruls//us.yaml"          
      prepend-rules:
        - RULE-SET,additional-us,🇺🇸 美国 01 GIA CN2 IPv6
        - RULE-SET,anti-ad,REJECT
```

这样设置完成后每次订阅更新, 你的本地配置附加到路由规则里一起生效的
