### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by cloud-yu** [clash-verge-rev/clash-verge-rev#743]
### 功能描述 / Feature description

配置mix-port监听后支持不配置http 和 socks单独监听端口

### 使用场景 / Use case

开启mix-port后可以同时接受http和socks链接，设备代理流量都从mix-port端口进入，空余两个端口给其他应用使用

目前情况是可以将http或者socks的port配置为0，可以关闭其中一个，但是不能两个都配置为0，会提示端口重复。
希望设备可以支持在配置了mix-port监听后，另外两个端口可以不配置

**Comment by dongchengjie** [comment]
使用listeners可就可以了？按要求改成http、socks、mixed
```
listeners: 
- name: demo
  type: mixed
  port: 56789
  proxy: 流量出口
```
