### ISSUE TITLE
[Feature] 希望tun模式能自定义dns服务器，添加对doh和dot的支持

### ISSUE THREAD

**Issue by Fadouse** [clash-verge-rev/clash-verge-rev#767]
### 功能描述 / Feature description

希望tun模式能自定义dns服务器（覆盖配置文件中配置的dns），添加对doh和dot的支持

### 使用场景 / Use case

dns解析

**Comment by lucienshawls** [comment]
你可以使用Merge订阅文件来设置DNS以及覆盖Remote订阅中原本的DNS部分的内容。
例如，新建一个Merge订阅文件，填写：
```yaml
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
    - 1.1.1.1
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  # nameserver-policy:
  # fallback: 
  #   - https://doh.dns.sb/dns-query
  #   - https://dns.cloudflare.com/dns-query
  #   - https://dns.twnic.tw/dns-query
  #   - tls://8.8.4.4:853
  # fallback-filter: 
  #   geoip: true
  #   ipcidr: 
  #     - 240.0.0.0/4
  #     - 0.0.0.0/3
  default-nameserver: 
    - 223.5.5.5
    - 119.29.29.29
  fake-ip-filter:
    # - "+.*"
    - localhost
    - WORKGROUP
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "+.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "+.xboxlive.com"
    - "+.msftncsi.com"
    - "+.msftconnecttest.com"
```
