### ISSUE TITLE
[BUG] 更新订阅配置文件后网络的DNS配置会被自动清除

### ISSUE THREAD

**Issue by suyanjun1987** [clash-verge-rev/clash-verge-rev#774]
### 问题描述 / Describe the bug

由于需要采用固定IP，自行设置IP和DNS。Clash Verge 每次更新订阅配置文件时，会自动清除已填写的DNS网络配置 。每次更新完后，都需要自行重新填写DNS配置，才能够正常上网。

### 复现步骤 / To Reproduce

Mac OS 14，设置系统代理后，在没有使用TUN模式的情况下，手动或自动更新订阅配置文件后，在系统->设置->网络下的手动DNS设置会被自动清除。希望能够解决这一问题。

### 操作系统 / OS

MacOS

### 操作系统版本 / OS Version

14.3.1

### 日志 / Log

03-27 16:56:39INFO
Start initial configuration in progress
03-27 16:56:39INFO
Geodata Loader mode: memconservative
03-27 16:56:39INFO
Geosite Matcher implementation: succinct
03-27 16:56:39INFO
Initial configuration complete, total time: 2ms
03-27 16:56:39INFO
Sniffer is closed
03-27 16:56:39INFO
Start initial provider 爱奇艺等国内流媒体
03-27 16:56:39INFO
Start initial provider ChinaIP
03-27 16:56:39INFO
Start initial provider adbyby
03-27 16:56:39INFO
Start initial provider Unbreak
03-27 16:56:39INFO
Start initial provider Netflix等国外流媒体
03-27 16:56:39INFO
Start initial provider Global
03-27 16:56:39INFO
Start initial provider China
03-27 16:56:39INFO
Start initial provider Disney
03-27 16:56:39INFO
Start initial provider ChatGPT
03-27 16:56:39INFO
Start initial provider Youtube
03-27 16:56:39INFO
Start initial Compatible provider 🚧Proxy
03-27 16:56:39INFO
Start initial Compatible provider 🇨🇳国内网站或资源
03-27 16:56:39INFO
Start initial Compatible provider 🎥Disney+
03-27 16:56:39INFO
Start initial Compatible provider 📦ChatGPT
03-27 16:56:39INFO
Start initial Compatible provider 🎬Netflix等国外流媒体
03-27 16:56:39INFO
Start initial Compatible provider default
03-27 16:56:39INFO
Start initial Compatible provider 📺爱奇艺等国内流媒体
03-27 16:56:39INFO
Start initial Compatible provider 📹Youtube
03-27 16:56:39INFO
Start initial Compatible provider 🌵其它规则外

**Comment by LixinQian** [comment]
面临同样的问题，DNS被清掉后，网络就访问不了了，求解

**Comment by JokingAboutLife** [comment]
可以在Merge里配置DNS后启用

**Comment by suyanjun1987** [comment]
> 可以在Merge里配置DNS后启用

谢谢。通过配置Merge暂时先解决了。期待能从软件层面解决。

**Comment by s6yoho** [comment]
> > 可以在Merge里配置DNS后启用
> 
> 谢谢。通过配置Merge暂时先解决了。期待能从软件层面解决。

请问你说的这个merge怎么配置? 我也遇到清dns问题..很难受

**Comment by JokingAboutLife** [comment]
> > > 可以在Merge里配置DNS后启用
> > 
> > 
> > 谢谢。通过配置Merge暂时先解决了。期待能从软件层面解决。
> 
> 请问你说的这个merge怎么配置? 我也遇到清dns问题..很难受

新建Merge配置 --> 配置dns --> 启用Merge配置

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/46296997/bb8e1b4f-2e47-4ccb-904c-003eb8a40594)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/46296997/19f32c3d-f997-4275-b1ca-1026d161b838)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/46296997/344b5064-5f94-4d43-8ae0-2691af7c5903)

**Comment by s6yoho** [comment]
![Snipaste_2024-04-03_10-03-09](https://github.com/clash-verge-rev/clash-verge-rev/assets/59301783/ebfa5fc4-1807-43f0-b6a7-8ee47cc1e1dc)

![Snipaste_2024-04-03_10-03-21](https://github.com/clash-verge-rev/clash-verge-rev/assets/59301783/bf8dde63-51a4-42c8-9321-b4e99d8f044f)

```yaml

dns:
    enable: true
    listen: :1053
    ipv6: true
    default-nameserver: [180.76.76.76, 182.254.118.118, 223.5.5.5, 114.114.114.114]
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    fake-ip-filter: ['*.lan', 'stun.*.*.*', 'stun.*.*', time.windows.com, time.nist.gov, time.apple.com, time.asia.apple.com, '*.ntp.org.cn', '*.openwrt.pool.ntp.org', time1.cloud.tencent.com, time.ustc.edu.cn, pool.ntp.org, ntp.ubuntu.com, ntp.aliyun.com, ntp1.aliyun.com, ntp2.aliyun.com, ntp3.aliyun.com, ntp4.aliyun.com, ntp5.aliyun.com, ntp6.aliyun.com, ntp7.aliyun.com, time1.aliyun.com, time2.aliyun.com, time3.aliyun.com, time4.aliyun.com, time5.aliyun.com, time6.aliyun.com, time7.aliyun.com, '*.time.edu.cn', time1.apple.com, time2.apple.com, time3.apple.com, time4.apple.com, time5.apple.com, time6.apple.com, time7.apple.com, time1.google.com, time2.google.com, time3.google.com, time4.google.com, music.163.com, '*.music.163.com', '*.126.net', musicapi.taihe.com, music.taihe.com, songsearch.kugou.com, trackercdn.kugou.com, '*.kuwo.cn', api-jooxtt.sanook.com, api.joox.com, joox.com, y.qq.com, '*.y.qq.com', streamoc.music.tc.qq.com, mobileoc.music.tc.qq.com, isure.stream.qqmusic.qq.com, dl.stream.qqmusic.qq.com, aqqmusic.tc.qq.com, amobile.music.tc.qq.com, '*.xiami.com', '*.music.migu.cn', music.migu.cn, '*.msftconnecttest.com', '*.msftncsi.com', localhost.ptlogin2.qq.com, '*.*.*.srv.nintendo.net', '*.*.stun.playstation.net', 'xbox.*.*.microsoft.com', '*.ipv6.microsoft.com', '*.*.xboxlive.com', speedtest.cros.wr.pvp.net]
    nameserver: [223.6.6.6, 180.76.76.76, 'https://223.6.6.6/dns-query', 'https://dns.rubyfish.cn/dns-query', 'https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    fallback: [119.28.28.28, 114.114.115.115, 'https://dns.rubyfish.cn/dns-query', 'tls://8.8.4.4', 'tls://1.0.0.1:853', 'https://cloudflare-dns.com/dns-query', 'https://dns.google/dns-query']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32, 127.0.0.1/32], domain: [+.google.com, +.facebook.com, +.twitter.com, +.youtube.com, +.xn--ngstr-lra8j.com, +.google.cn, +.googleapis.cn, +.googleapis.com, +.gvt1.com] }

```

@JokingAboutLife 感谢热佬指导. 但是我这里还是会清dns.

我是copy的另一个文件的配置.是配置必须和你一样吗?或者因为我用的是mac系统?
