### ISSUE TITLE
[BUG] hy2类型节点 server填写ipv6地址时无效

### ISSUE THREAD

**Issue by ypxun** [clash-verge-rev/clash-verge-rev#798]
### 问题描述 / Describe the bug

之前搭的hysteria2协议，用的ipv4的地址被封了，打算换用ipv6的地址。将配置文件的proxies配置项下server的值修改为ipv6地址后（同时换了个端口，服务器端已放行），clash-verge-rev（使用tun）还是连不上。但在其他平台和代理工具上，比如iOS和iPadOS的loon，Android的cmfa，这个ipv6的hy2节点是可以正常使用的。

### 复现步骤 / To Reproduce

配置文件：
```
pr: &pr {type: select, proxies: [默认,hy2,全部节点,直连]}

p: &p {type: http, interval: 3600, health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 300}}

proxy-providers:
  provider1:
    <<: *p
    url: "link1"

ipv6: true
allow-lan: true
mixed-port: 7890
unified-delay: false
tcp-concurrent: true
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  listen: :1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver-policy:
    "rule-set:cn_domain,private":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
    "rule-set:geolocation-!cn":
      - "https://dns.cloudflare.com/dns-query#dns"
      - "https://dns.google/dns-query#dns"
      
proxies:
- name: "直连"
  type: direct
  udp: true

- name: "hy2"
  type: hysteria2
  server: ipv6地址
  port: 31001
  up: "30 Mbps"
  down: "1000 Mbps"
  password: pwd
  sni: https://bing.com
  skip-cert-verify: true

proxy-groups:
  - {name: 默认, type: select, proxies: [hy2, 全部节点, 直连]}
  - {name: dns, type: select, proxies: [hy2, 全部节点, 直连]}
  - {name: 全部节点, type: select , include-all-providers: true}
  - {name: Google, type: select, proxies: [默认, 直连]}
  - {name: Telegram, type: select, proxies: [默认, 直连]}
  - {name: Twitter, type: select, proxies: [默认, 直连]}
  - {name: Pixiv, type: select, proxies: [默认, 直连]}
  - {name: ehentai, type: select, proxies: [默认, 直连]}
  - {name: 哔哩哔哩, type: select, proxies: [直连, 默认]}
  - {name: 哔哩东南亚, type: select, proxies: [默认, 直连]}
  - {name: 巴哈姆特, type: select, proxies: [默认, 直连]}
  - {name: YouTube, type: select, proxies: [默认, 直连]}
  - {name: NETFLIX, type: select, proxies: [默认, 直连]}
  - {name: Steam, type: select, proxies: [默认, 直连]}
  - {name: TestFlight, type: select, proxies: [默认, 直连]}
  - {name: Apple ID, type: select, proxies: [默认, 直连]}
  - {name: App Store, type: select, proxies: [默认, 直连]}
  - {name: Spotify, type: select, proxies: [默认, 直连]}
  - {name: Github, type: select, proxies: [默认, 直连]}
  - {name: 国内, type: select, proxies: [直连, 默认]}
  - {name: 其他, type: select, proxies: [默认, 直连]}

rules:
  - GEOIP,lan,直连,no-resolve
  - RULE-SET,biliintl_domain,哔哩东南亚
  - RULE-SET,ehentai_domain,ehentai
  - RULE-SET,github_domain,Github
  - RULE-SET,twitter_domain,Twitter
  - RULE-SET,youtube_domain,YouTube
  - RULE-SET,google_domain,Google
  - RULE-SET,telegram_domain,Telegram
  - RULE-SET,netflix_domain,NETFLIX
  - RULE-SET,steam_domain,Steam
  - RULE-SET,TestFlight_domain,TestFlight
  - RULE-SET,iCloudChina_domain,国内
  - RULE-SET,ApplePushNotificationService_domain,国内
  - RULE-SET,AppleSoftwareUpdates_domain,国内
  - RULE-SET,AppleID_domain,Apple ID
  - RULE-SET,AppStore_domain,App Store
  - RULE-SET,bilibili_domain,哔哩哔哩
  - RULE-SET,bahamut_domain,巴哈姆特
  - RULE-SET,spotify_domain,Spotify
  - RULE-SET,pixiv_domain,Pixiv
  - RULE-SET,InternationalGameDownload_domain,默认
  - RULE-SET,ChineseGameDownload_domain,国内
  - RULE-SET,cn_domain,国内
  - RULE-SET,geolocation-!cn,其他

  - RULE-SET,google_ip,Google
  - RULE-SET,netflix_ip,NETFLIX
  - RULE-SET,telegram_ip,Telegram
  - RULE-SET,twitter_ip,Twitter
  - RULE-SET,cn_ip,国内
  - MATCH,其他

rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: yaml}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: yaml}
rule-providers:
  private:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.yaml"
  cn_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.yaml"
  biliintl_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/biliintl.yaml"
  ehentai_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ehentai.yaml"
  github_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.yaml"
  twitter_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.yaml"
  youtube_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.yaml"
  google_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.yaml"
  telegram_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.yaml"
  netflix_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.yaml"
  steam_domain:
    <<: *domain
    url: "https://gitlab.com/lodepuly/proxy_tool_resources/-/raw/master/rule/Clash/Steam/Steam.yaml"
  TestFlight_domain:
    <<: *domain
    url: "https://gitlab.com/lodepuly/proxy_tool_resources/-/raw/master/rule/Clash/TestFlight/TestFlight.yaml"
  iCloudChina_domain:
    <<: *domain
    url: "url: https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Clash/Rule/iCloudChina.yaml"
  ApplePushNotificationService_domain:
    <<: *domain
    url: "https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Clash/Rule/ApplePushNotificationService.yaml"
  AppleSoftwareUpdates_domain:
    <<: *domain
    url: "https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Clash/Rule/AppleSoftwareUpdates.yaml"
  AppleID_domain:
    <<: *domain
    url: "https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Clash/Rule/AppleID.yaml"
  AppStore_domain:
    <<: *domain
    url: "https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Clash/Rule/AppStore.yaml"
  bilibili_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bilibili.yaml"
  bahamut_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bahamut.yaml"
  spotify_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.yaml"
  pixiv_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/pixiv.yaml"
  InternationalGameDownload_domain:
    <<: *domain
    url: "https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Clash/Rule/InternationalDownloadCDN.yaml"
  ChineseGameDownload_domain:
    <<: *domain
    url: "https://gitlab.com/lodepuly/vpn_tool/-/raw/master/Tool/Clash/Rule/ChinaDownloadCDN.yaml"
  geolocation-!cn:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.yaml"

  cn_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.yaml"
  google_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.yaml"
  netflix_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.yaml"
  twitter_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/twitter.yaml"
  telegram_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.yaml"
```
报错日志1，此时hy2节点的心跳检测为error，选择此节点，任意墙外网址都报ip version类型错误。

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 22H2

### 日志 / Log

日志1:
```
03-29 23:12:15WARNING
[TCP] dial Github (match RuleSet/github_domain) 28.0.0.1:3744 --> alive.github.com:443 error: ip version error
03-29 23:12:16WARNING
[TCP] dial 其他 (match RuleSet/geolocation-!cn) 28.0.0.1:3745 --> self.events.data.microsoft.com:443 error: ip version error
03-29 23:12:19WARNING
[TCP] dial Telegram (match RuleSet/telegram_ip) 28.0.0.1:3746 --> 91.108.56.180:443 error: ip version error
03-29 23:12:19WARNING
[TCP] dial Telegram (match RuleSet/telegram_ip) 28.0.0.1:3747 --> 91.108.56.180:80 error: ip version error
```
