### ISSUE TITLE
[BUG]Tun模式导致Hyper-V虚拟机频繁断连。

### ISSUE THREAD

**Issue by asinitial** [clash-verge-rev/clash-verge-rev#80]
**Describe the bug**
开启Tun模式使用Hyper-V，虚拟交换机默认Default Switch（即虚拟机采用NAT方式联网），同时开启增强会话连接虚拟机，会导致虚拟机频繁断联（间隔大概1-2分钟），关闭Tun模式则正常。

**To Reproduce**
1. 安装 Clash-Verge 服务并以普通权限运行，开启Tun使用 stack: system。
2. 启动Hyper-V中的虚拟机，启用增强会话。
3. 等待1-2分钟。

**Expected behavior**
Tun与Hyper-V稳定运行

**Screenshots**
![屏幕截图 2023-12-06 110716](https://github.com/clash-verge-rev/clash-verge-rev/assets/9674332/b219d943-b264-4e90-af60-31ec75db26ca)

**Information**

- OS: Windows 10 22H2
- Clash Verge Version: 1.4.3
- Clash Core: v1.17.0 Meta

**Additional context**
Clash中未观察到异常日志，在事件查看器中每次断连期间观察到以下日志：
```
Status change (网络更改) sent to Nic 2E47FACA-7237-44F7-AEAC-3F9FB13D024F--4A274761-BEE0-4BA7-ABA8-F328137F137E (Friendly Name: 网络适配器) on port 50A701D8-058D-4D27-B5A3-904586051855 (Friendly Name: 动态以太网交换机端口) on switch C08CB7B8-9B3C-408E-8E30-5E16A3AEB444 (Friendly Name: Default Switch). NicStatus: 网络更改, Status: STATUS_SUCCESS
```

```
tun:
  enable: true
  stack: system
  dns-hijack:
  - any:53
  - tcp://any:53
  auto-detect-interface: true
  auto-route: true
```
