### ISSUE TITLE
[Feature] 自动代理，需要过滤掉某些代理节点

### ISSUE THREAD

**Issue by iseejustdoit** [clash-verge-rev/clash-verge-rev#801]
### 功能描述 / Feature description

问题1：界面上能不能提供过滤掉不想使用的代理节点，以免选择自动代理的时候会代理到不想指定的节点中，如果是指定节点，当节点不可用时，需要手工再去指定，很不方便。
问题2：有没有教程指导下怎么过滤掉不想使用的代理节点

### 使用场景 / Use case

代理到香港节点，使用不了chatgpt

**Comment by Wilson2003** [comment]
+1

**Comment by HenryLuoCN** [comment]
我也用不了chatGPT

**Comment by wonfen** [comment]
最新的alpha构建添加了urltest可以手动选择节点的功能，请测试。

**Comment by wbbo** [comment]
单独创建一个 groups

proxy-groups:
  - { name: PROXY, type: select, <<: *pr }
  - { name: AUTO, type: url-test, include-all: true }
  - { name: 🤖 OpenAi, type: url-test, include-all: true, filter: "(?i)^(?!.*(?:🇭🇰|港|hk|hongkong|🏷|t\\.me)).*" }
  
rules:
  # openai
  - DOMAIN-KEYWORD,openai,🤖 OpenAi
  - DOMAIN-SUFFIX,auth0.com,🤖 OpenAi
  - DOMAIN-SUFFIX,challenges.cloudflare.com,🤖 OpenAi
  - DOMAIN-SUFFIX,client-api.arkoselabs.com,🤖 OpenAi
  - DOMAIN-SUFFIX,events.statsigapi.net,🤖 OpenAi
  - DOMAIN-SUFFIX,featuregates.org,🤖 OpenAi
  - DOMAIN-SUFFIX,identrust.com,🤖 OpenAi
  - DOMAIN-SUFFIX,intercom.io,🤖 OpenAi
  - DOMAIN-SUFFIX,intercomcdn.com,🤖 OpenAi
  - DOMAIN-SUFFIX,oaistatic.com,🤖 OpenAi
  - DOMAIN-SUFFIX,oaiusercontent.com,🤖 OpenAi
  - DOMAIN-SUFFIX,openai.com,🤖 OpenAi
  - DOMAIN-SUFFIX,openaiapi-site.azureedge.net,🤖 OpenAi
  - DOMAIN-SUFFIX,sentry.io,🤖 OpenAi
  - DOMAIN-SUFFIX,stripe.com,🤖 OpenAi
  - DOMAIN-SUFFIX,openai.com,🤖 OpenAi
  - DOMAIN-SUFFIX,openai.nooc.ink,🤖 OpenAi
  - DOMAIN-SUFFIX,AI.com,🤖 OpenAi
  - DOMAIN-SUFFIX,cdn.auth0.com,🤖 OpenAi
  - DOMAIN-SUFFIX,openaiapi-site.azureedge.net,🤖 OpenAi
  - DOMAIN-SUFFIX,opendns.com,🤖 OpenAi
  - DOMAIN-SUFFIX,bing.com,🤖 OpenAi
  - DOMAIN-SUFFIX,civitai.com,🤖 OpenAi
  - DOMAIN,bard.google.com,🤖 OpenAi
  - DOMAIN,ai.google.dev,🤖 OpenAi
  - DOMAIN,gemini.google.com,🤖 OpenAi
  - DOMAIN-SUFFIX,googleapis.com,🤖 OpenAi
  - DOMAIN-SUFFIX,sentry.io,🤖 OpenAi
  - DOMAIN-SUFFIX,intercom.io,🤖 OpenAi
  - DOMAIN-SUFFIX,featuregates.org,🤖 OpenAi
  - DOMAIN-SUFFIX,statsigapi.net,🤖 OpenAi
  - DOMAIN-SUFFIX,claude.ai,🤖 OpenAi
  - DOMAIN-SUFFIX,Anthropic.com,🤖 OpenAi
  - DOMAIN-SUFFIX,opera-api.com,🤖 OpenAi

**Comment by wbbo** [comment]
单独创建一个 groups
```yml
proxy-groups:
  - { name: AUTO, type: url-test, include-all: true }
  - { name: 🤖 OpenAi, type: url-test, include-all: true, filter: "(?i)^(?!.*(?:🇭🇰|港|hk|hongkong|🏷|t\\.me)).*" }
rules:
  # openai
  - DOMAIN-KEYWORD,openai,🤖 OpenAi
  - DOMAIN-SUFFIX,auth0.com,🤖 OpenAi
  - DOMAIN-SUFFIX,challenges.cloudflare.com,🤖 OpenAi
  - DOMAIN-SUFFIX,client-api.arkoselabs.com,🤖 OpenAi
  - DOMAIN-SUFFIX,events.statsigapi.net,🤖 OpenAi
  - DOMAIN-SUFFIX,featuregates.org,🤖 OpenAi
  - DOMAIN-SUFFIX,identrust.com,🤖 OpenAi
  - DOMAIN-SUFFIX,intercom.io,🤖 OpenAi
  - DOMAIN-SUFFIX,intercomcdn.com,🤖 OpenAi
  - DOMAIN-SUFFIX,oaistatic.com,🤖 OpenAi
  - DOMAIN-SUFFIX,oaiusercontent.com,🤖 OpenAi
  - DOMAIN-SUFFIX,openai.com,🤖 OpenAi
  - DOMAIN-SUFFIX,openaiapi-site.azureedge.net,🤖 OpenAi
  - DOMAIN-SUFFIX,sentry.io,🤖 OpenAi
  - DOMAIN-SUFFIX,stripe.com,🤖 OpenAi
  - DOMAIN-SUFFIX,openai.com,🤖 OpenAi
  - DOMAIN-SUFFIX,openai.nooc.ink,🤖 OpenAi
  - DOMAIN-SUFFIX,AI.com,🤖 OpenAi
  - DOMAIN-SUFFIX,cdn.auth0.com,🤖 OpenAi
  - DOMAIN-SUFFIX,openaiapi-site.azureedge.net,🤖 OpenAi
  - DOMAIN-SUFFIX,opendns.com,🤖 OpenAi
  - DOMAIN-SUFFIX,bing.com,🤖 OpenAi
  - DOMAIN-SUFFIX,civitai.com,🤖 OpenAi
  - DOMAIN,bard.google.com,🤖 OpenAi
  - DOMAIN,ai.google.dev,🤖 OpenAi
  - DOMAIN,gemini.google.com,🤖 OpenAi
  - DOMAIN-SUFFIX,googleapis.com,🤖 OpenAi
  - DOMAIN-SUFFIX,sentry.io,🤖 OpenAi
  - DOMAIN-SUFFIX,intercom.io,🤖 OpenAi
  - DOMAIN-SUFFIX,featuregates.org,🤖 OpenAi
  - DOMAIN-SUFFIX,statsigapi.net,🤖 OpenAi
  - DOMAIN-SUFFIX,claude.ai,🤖 OpenAi
  - DOMAIN-SUFFIX,Anthropic.com,🤖 OpenAi
  - DOMAIN-SUFFIX,opera-api.com,🤖 OpenAi
```

**Comment by iseejustdoit** [comment]
> 单独创建一个 groups
> 
> ```yaml
> proxy-groups:
>   - { name: AUTO, type: url-test, include-all: true }
>   - { name: 🤖 OpenAi, type: url-test, include-all: true, filter: "(?i)^(?!.*(?:🇭🇰|港|hk|hongkong|🏷|t\\.me)).*" }
> rules:
>   # openai
>   - DOMAIN-KEYWORD,openai,🤖 OpenAi
>   - DOMAIN-SUFFIX,auth0.com,🤖 OpenAi
>   - DOMAIN-SUFFIX,challenges.cloudflare.com,🤖 OpenAi
>   - DOMAIN-SUFFIX,client-api.arkoselabs.com,🤖 OpenAi
>   - DOMAIN-SUFFIX,events.statsigapi.net,🤖 OpenAi
>   - DOMAIN-SUFFIX,featuregates.org,🤖 OpenAi
>   - DOMAIN-SUFFIX,identrust.com,🤖 OpenAi
>   - DOMAIN-SUFFIX,intercom.io,🤖 OpenAi
>   - DOMAIN-SUFFIX,intercomcdn.com,🤖 OpenAi
>   - DOMAIN-SUFFIX,oaistatic.com,🤖 OpenAi
>   - DOMAIN-SUFFIX,oaiusercontent.com,🤖 OpenAi
>   - DOMAIN-SUFFIX,openai.com,🤖 OpenAi
>   - DOMAIN-SUFFIX,openaiapi-site.azureedge.net,🤖 OpenAi
>   - DOMAIN-SUFFIX,sentry.io,🤖 OpenAi
>   - DOMAIN-SUFFIX,stripe.com,🤖 OpenAi
>   - DOMAIN-SUFFIX,openai.com,🤖 OpenAi
>   - DOMAIN-SUFFIX,openai.nooc.ink,🤖 OpenAi
>   - DOMAIN-SUFFIX,AI.com,🤖 OpenAi
>   - DOMAIN-SUFFIX,cdn.auth0.com,🤖 OpenAi
>   - DOMAIN-SUFFIX,openaiapi-site.azureedge.net,🤖 OpenAi
>   - DOMAIN-SUFFIX,opendns.com,🤖 OpenAi
>   - DOMAIN-SUFFIX,bing.com,🤖 OpenAi
>   - DOMAIN-SUFFIX,civitai.com,🤖 OpenAi
>   - DOMAIN,bard.google.com,🤖 OpenAi
>   - DOMAIN,ai.google.dev,🤖 OpenAi
>   - DOMAIN,gemini.google.com,🤖 OpenAi
>   - DOMAIN-SUFFIX,googleapis.com,🤖 OpenAi
>   - DOMAIN-SUFFIX,sentry.io,🤖 OpenAi
>   - DOMAIN-SUFFIX,intercom.io,🤖 OpenAi
>   - DOMAIN-SUFFIX,featuregates.org,🤖 OpenAi
>   - DOMAIN-SUFFIX,statsigapi.net,🤖 OpenAi
>   - DOMAIN-SUFFIX,claude.ai,🤖 OpenAi
>   - DOMAIN-SUFFIX,Anthropic.com,🤖 OpenAi
>   - DOMAIN-SUFFIX,opera-api.com,🤖 OpenAi
> ```

对于只会对软件界面点鼠标操作人的来说，能否有一个详细可指导的图片文字说明一下，这个怎么使用？！

**Comment by Stephenzero** [comment]
顶你支持你

**Comment by oneyh** [comment]
> > 单独创建一个 groups
> > ```yaml
> > proxy-groups:
> >   - { name: AUTO, type: url-test, include-all: true }
> >   - { name: 🤖 OpenAi, type: url-test, include-all: true, filter: "(?i)^(?!.*(?:🇭🇰|港|hk|hongkong|🏷|t\\.me)).*" }
> > rules:
> >   # openai
> >   - DOMAIN-KEYWORD,openai,🤖 OpenAi
> >   - DOMAIN-SUFFIX,auth0.com,🤖 OpenAi
> >   - DOMAIN-SUFFIX,challenges.cloudflare.com,🤖 OpenAi
> >   - DOMAIN-SUFFIX,client-api.arkoselabs.com,🤖 OpenAi
> >   - DOMAIN-SUFFIX,events.statsigapi.net,🤖 OpenAi
> >   - DOMAIN-SUFFIX,featuregates.org,🤖 OpenAi
> >   - DOMAIN-SUFFIX,identrust.com,🤖 OpenAi
> >   - DOMAIN-SUFFIX,intercom.io,🤖 OpenAi
> >   - DOMAIN-SUFFIX,intercomcdn.com,🤖 OpenAi
> >   - DOMAIN-SUFFIX,oaistatic.com,🤖 OpenAi
> >   - DOMAIN-SUFFIX,oaiusercontent.com,🤖 OpenAi
> >   - DOMAIN-SUFFIX,openai.com,🤖 OpenAi
> >   - DOMAIN-SUFFIX,openaiapi-site.azureedge.net,🤖 OpenAi
> >   - DOMAIN-SUFFIX,sentry.io,🤖 OpenAi
> >   - DOMAIN-SUFFIX,stripe.com,🤖 OpenAi
> >   - DOMAIN-SUFFIX,openai.com,🤖 OpenAi
> >   - DOMAIN-SUFFIX,openai.nooc.ink,🤖 OpenAi
> >   - DOMAIN-SUFFIX,AI.com,🤖 OpenAi
> >   - DOMAIN-SUFFIX,cdn.auth0.com,🤖 OpenAi
> >   - DOMAIN-SUFFIX,openaiapi-site.azureedge.net,🤖 OpenAi
> >   - DOMAIN-SUFFIX,opendns.com,🤖 OpenAi
> >   - DOMAIN-SUFFIX,bing.com,🤖 OpenAi
> >   - DOMAIN-SUFFIX,civitai.com,🤖 OpenAi
> >   - DOMAIN,bard.google.com,🤖 OpenAi
> >   - DOMAIN,ai.google.dev,🤖 OpenAi
> >   - DOMAIN,gemini.google.com,🤖 OpenAi
> >   - DOMAIN-SUFFIX,googleapis.com,🤖 OpenAi
> >   - DOMAIN-SUFFIX,sentry.io,🤖 OpenAi
> >   - DOMAIN-SUFFIX,intercom.io,🤖 OpenAi
> >   - DOMAIN-SUFFIX,featuregates.org,🤖 OpenAi
> >   - DOMAIN-SUFFIX,statsigapi.net,🤖 OpenAi
> >   - DOMAIN-SUFFIX,claude.ai,🤖 OpenAi
> >   - DOMAIN-SUFFIX,Anthropic.com,🤖 OpenAi
> >   - DOMAIN-SUFFIX,opera-api.com,🤖 OpenAi
> > ```
> 
> 对于只会对软件界面点鼠标操作人的来说，能否有一个详细可指导的图片文字说明一下，这个怎么使用？！

cfw中有一个我用起来很好的功能：预处理。
每次更新订阅的时候，会使用node.js按照预定的规则进行处理，这样可以自动的实现上面的内容，当然还有更多更好的效果，不知道verge能否支持？

**Comment by DiYi1999** [comment]
软件界面的   “订阅” --> "全局扩展覆写配置"加入以下代码：
```
proxy-groups:
  - name: 手动选择 
    type: select
    include-all: true
    proxies:
      - 自动选择
      - 自动选择-无香港

  - name: 自动选择
    type: url-test
    include-all: true

  - name: 自动选择-无香港
    type: url-test
    include-all: true
    filter: "(?i)^(?!.*(?:🇭🇰|港|hk|hongkong|🏷|t\\.me)).*"

rules:
  - DOMAIN,www.bilibili.com,DIRECT
  - DOMAIN-SUFFIX,ieeexplore.ieee.org,DIRECT
  - MATCH, 手动选择
```
