### ISSUE TITLE
TUN模式下无法访问IPV6网站[BUG] 

### ISSUE THREAD

**Issue by lqllife** [clash-verge-rev/clash-verge-rev#813]
### 问题描述 / Describe the bug

亲爱的开发者，辛苦了。我遇见到一个问题，不知道是我操作有误还是软件存在bug，特来求助。

我的笔记本有两个网卡，一个是有线，接的是公司的网络，无ipv6地址。另一个是wifi，接的是手机热点，有ipv6地址。

打开TUN模式时，访问 http://testipv6.cn/ 显示没有 ipv6地址，这时如果拔掉有线，只用wifi，再访问 testipv6 就显示有 ipv6 地址。

关闭TUN模式时，开启系统代理，有线和无线同时连接，访问 testipv6 也显示有 ipv6 地址。

所以经过以上步骤的测试，初步断定可能是TUN模式导致无法访问IPV6。

我在使用Clash for Windows时，是开启TUN模式，同时连接有线和wifi访问ipv6网络的，现在换到Clash Verge Rev不能访问了，想请教下是什么原因导致的，谢谢。

### 复现步骤 / To Reproduce

同上

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win 11

### 日志 / Log

日志：
```
04-01 15:02:10WARNING
[TCP] dial DIRECT (match RuleSet/direct) 198.18.0.1:52154(msedge.exe) --> ipv6.testipv6.cn:443 error: dns resolve failed: couldn't find ip
04-01 15:02:10WARNING
[TCP] dial DIRECT (match RuleSet/direct) 198.18.0.1:52155(msedge.exe) --> ipv6.testipv6.cn:443 error: dns resolve failed: couldn't find ip
04-01 15:02:10WARNING
[TCP] dial DIRECT (match RuleSet/direct) 198.18.0.1:52156(msedge.exe) --> ipv6.testipv6.cn:443 error: dns resolve failed: couldn't find ip
04-01 15:02:10WARNING
[TCP] dial DIRECT (match RuleSet/direct) 198.18.0.1:52159(msedge.exe) --> mtu1280.testipv6.cn:443 error: dns resolve failed: couldn't find ip
04-01 15:02:10WARNING
[TCP] dial DIRECT (match RuleSet/direct) 198.18.0.1:52160(msedge.exe) --> mtu1280.testipv6.cn:443 error: dns resolve failed: couldn't find ip
```
运行配置：
```yml
mode: rule
mixed-port: 7897
socks-port: 7898
port: 7899
allow-lan: false
log-level: info
ipv6: true
secret: clash123
external-controller: 127.0.0.1:9097
geo-update-interval: 24
geodata-mode: true
geox-url:
  geoip: https://git.nxnow.top/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat
  geosite: https://git.nxnow.top/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://git.nxnow.top/MetaCubeX/meta-rules-dat/releases/download/latest/Country.mmdb
tun:
  stack: gvisor
  device: Meta
  auto-route: true
  strict-route: false
  auto-detect-interface: true
  dns-hijack:
  - any:53
  mtu: 9000
  enable: true
dns:
  enable: true
  ipv6: true
  default-nameserver:
  - 114.114.114.114
  - tls://223.5.5.5:853
  - system
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  nameserver-policy:
    geosite:cn,private:
    - 119.29.29.29
    - https://dns.alidns.com/dns-query
  fallback: []
  fake-ip-filter:
  - dns.msftncsi.com
  - www.msftncsi.com
  - www.msftconnecttest.com
global-ua: ClashMetaForAndroid/2.10.0
geo-auto-update: true
proxy-providers:
  Fly:
    type: http
    path: ./sub/Fly/Fly.yaml
    url: https://.....
    interval: 1800
proxy-groups:
- name: 🚀 节点选择
  type: select
  use:
  - Fly
  proxies: null
- name: 📢 谷歌FCM
  type: select
  filter: (^(?!.*(游戏|Game).*).*(美|新加坡|日本))
  use:
  - Fly
  proxies:
  - 🚀 节点选择
- name: Ⓜ️ 微软服务
  type: select
  filter: (^(?!.*(游戏|Game).*).*(美|新加坡))
  use:
  - Fly
  proxies:
  - 🚀 节点选择
- name: 🛑 全球拦截
  type: select
  proxies:
  - REJECT
- name: 🐟 漏网之鱼
  type: select
  use:
  - Fly
  proxies:
  - 🚀 节点选择
  - DIRECT
rule-providers:
  reject:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: ./RuleSet/FlyProviders/reject.yaml
    interval: 86400
  google:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt
    path: ./RuleSet/FlyProviders/google.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./RuleSet/FlyProviders/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    path: ./RuleSet/FlyProviders/direct.yaml
    url: https://raw.nxnow.top/Loyalsoldier/clash-rules/release/direct.txt
    interval: 43200
  private:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
    path: ./RuleSet/FlyProviders/private.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
    path: ./RuleSet/FlyProviders/gfw.yaml
    interval: 86400
  greatfire:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt
    path: ./RuleSet/FlyProviders/greatfire.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt
    path: ./RuleSet/FlyProviders/tld-not-cn.yaml
    interval: 86400
rules:
- GEOIP,LAN,DIRECT
- DOMAIN-SUFFIX,nvidia.com,🚀 节点选择
- PROCESS-NAME,git-remote-https.exe,🚀 节点选择
- PROCESS-NAME,python.exe,🚀 节点选择
- DOMAIN-SUFFIX,element-plus.org,DIRECT
- DOMAIN-SUFFIX,npmmirror.com,🚀 节点选择
- DOMAIN-SUFFIX,a-nomad.com,🚀 节点选择
- DOMAIN-SUFFIX,api2d.net,🚀 节点选择
- PROCESS-NAME,v2ray,DIRECT
- PROCESS-NAME,xray,DIRECT
- PROCESS-NAME,naive,DIRECT
- PROCESS-NAME,trojan,DIRECT
- PROCESS-NAME,trojan-go,DIRECT
- PROCESS-NAME,ss-local,DIRECT
- PROCESS-NAME,privoxy,DIRECT
- PROCESS-NAME,leaf,DIRECT
- PROCESS-NAME,v2ray.exe,DIRECT
- PROCESS-NAME,xray.exe,DIRECT
- PROCESS-NAME,naive.exe,DIRECT
- PROCESS-NAME,trojan.exe,DIRECT
- PROCESS-NAME,trojan-go.exe,DIRECT
- PROCESS-NAME,ss-local.exe,DIRECT
- PROCESS-NAME,privoxy.exe,DIRECT
- PROCESS-NAME,leaf.exe,DIRECT
- PROCESS-NAME,Thunder,DIRECT
- PROCESS-NAME,DownloadService,DIRECT
- PROCESS-NAME,qBittorrent,DIRECT
- PROCESS-NAME,Transmission,DIRECT
- PROCESS-NAME,fdm,DIRECT
- PROCESS-NAME,aria2c,DIRECT
- PROCESS-NAME,Folx,DIRECT
- PROCESS-NAME,NetTransport,DIRECT
- PROCESS-NAME,uTorrent,DIRECT
- PROCESS-NAME,WebTorrent,DIRECT
- PROCESS-NAME,aria2c.exe,DIRECT
- PROCESS-NAME,BitComet.exe,DIRECT
- PROCESS-NAME,fdm.exe,DIRECT
- PROCESS-NAME,NetTransport.exe,DIRECT
- PROCESS-NAME,qbittorrent.exe,DIRECT
- PROCESS-NAME,Thunder.exe,DIRECT
- PROCESS-NAME,ThunderVIP.exe,DIRECT
- PROCESS-NAME,transmission-daemon.exe,DIRECT
- PROCESS-NAME,transmission-qt.exe,DIRECT
- PROCESS-NAME,uTorrent.exe,DIRECT
- PROCESS-NAME,WebTorrent.exe,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- GEOSITE,microsoft@cn,DIRECT
- GEOSITE,microsoft,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,google.com,📢 谷歌FCM
- RULE-SET,private,DIRECT
- RULE-SET,reject,REJECT
- RULE-SET,direct,DIRECT
- RULE-SET,google,📢 谷歌FCM
- RULE-SET,proxy,🚀 节点选择
- GEOIP,cn,DIRECT
- MATCH,🐟 漏网之鱼
```

**Comment by MengNianxiaoyao** [comment]
tun模式用的默认网卡应该是有线网卡，得改成无线网卡

**Comment by lqllife** [comment]
> tun模式用的默认网卡应该是有线网卡，得改成无线网卡

要怎么改呢？

**Comment by MengNianxiaoyao** [comment]
> > tun模式用的默认网卡应该是有线网卡，得改成无线网卡
> 
> 要怎么改呢？
![Clip_2024-04-08_11-36-58](https://github.com/clash-verge-rev/clash-verge-rev/assets/103258286/283a1224-c611-4f3c-840d-96b39ded2436)

**Comment by lqllife** [comment]
> > > tun模式用的默认网卡应该是有线网卡，得改成无线网卡
> > 
> > 
> > 要怎么改呢？
> 
> ![Clip_2024-04-08_11-36-58](https://private-user-images.githubusercontent.com/103258286/320346682-283a1224-c611-4f3c-840d-96b39ded2436.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4OTMzOTAsIm5iZiI6MTcxMjg5MzA5MCwicGF0aCI6Ii8xMDMyNTgyODYvMzIwMzQ2NjgyLTI4M2ExMjI0LWM2MTEtNGYzYy04NDBkLTk2YjM5ZGVkMjQzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQwMzM4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Yzc0OTA1NWJiMGRhNTZhMjM5MTgyMTZiMzBkNjYxNzM2MmY5NTAxM2Y4NzgwODY1ODc2OTkzZDFhYmZiYzRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Zc-HMvZwEsCBJ4EM8ER_5b40nHbQeq4x34jRrk5FZjs)
> 
> `interface-name`的注释去掉，`auto-detect-interface`注释掉

试了，还是不行，这是配置文件。
```yml
mode: rule
mixed-port: 7897
socks-port: 7898
port: 7899
allow-lan: true
log-level: info
ipv6: true
secret: clash123
external-controller: 127.0.0.1:9097
dns:
  enable: true
  ipv6: true
  default-nameserver:
  - 114.114.114.114
  - tls://223.5.5.5:853
  - system
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  nameserver-policy:
    geosite:cn,private:
    - 119.29.29.29
    - https://dns.alidns.com/dns-query
  fallback: []
  fake-ip-filter:
  - dns.msftncsi.com
  - www.msftncsi.com
  - www.msftconnecttest.com
global-ua: ClashMetaForAndroid/2.10.0
geox-url:
  geoip: https://git.nxnow.top/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat
  geosite: https://git.nxnow.top/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://git.nxnow.top/MetaCubeX/meta-rules-dat/releases/download/latest/Country.mmdb
geodata-mode: true
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
  - 192.18.0.2:53
  device: Meta
  strict-route: false
  mtu: 9000
```
