### ISSUE TITLE
[BUG] 从Parsers迁移Merge配置不生效

### ISSUE THREAD

**Issue by cstcood** [clash-verge-rev/clash-verge-rev#847]
### 问题描述 / Describe the bug

version：v1.5.11
Clash: alpha-0b4662e Meta/v.18.2 Meta
Parse 文件原文如下：
```
parsers:
  - url: xxxxxxxxxxx
   yaml:
        prepend-proxy-groups:
          - name: PROXY
            type: select
            proxies:
              - DIRECT
              - Proxy
        prepend-rules:
          - PROCESS-NAME,Tailscale.exe,DIRECT
          - PROCESS-NAME,Tailscale Service.exe,DIRECT
          - PROCESS-NAME,tailscaled.exe,DIRECT
          - PROCESS-NAME,tailscale-ipn.exe,DIRECT
          - PROCESS-NAME,tor.exe,Proxy
          - PROCESS-NAME,lyrebird.exe,Proxy
          - RULE-SET,applications,DIRECT
          - DOMAIN,clash.razord.top,DIRECT
          - DOMAIN,yacd.haishan.me,DIRECT
          - RULE-SET,private,DIRECT
          - RULE-SET,reject,REJECT
          - RULE-SET,tld-not-cn,PROXY
          - RULE-SET,gfw,PROXY
          - RULE-SET,telegramcidr,PROXY
          - MATCH,DIRECT
        mix-rule-providers:
          reject:
            type: http
            behavior: domain
            url: "https://cdn.jsdelivr.net/g2h/Loyalsoldier/clash-rules@release/reject.txt"
            path: ./ruleset/reject.yaml
            interval: 86400
  
          icloud:
            type: http
            behavior: domain
            url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
            path: ./ruleset/icloud.yaml
            interval: 86400
  
          apple:
            type: http
            behavior: domain
            url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
            path: ./ruleset/apple.yaml
            interval: 86400
  
          google:
            type: http
            behavior: domain
            url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
            path: ./ruleset/google.yaml
            interval: 86400
  
          proxy:
            type: http
            behavior: domain
            url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
            path: ./ruleset/proxy.yaml
            interval: 86400
  
          direct:
            type: http
            behavior: domain
            url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
            path: ./ruleset/direct.yaml
            interval: 86400
  
          private:
            type: http
            behavior: domain
            url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
            path: ./ruleset/private.yaml
            interval: 86400
  
          gfw:
            type: http
            behavior: domain
            url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
            path: ./ruleset/gfw.yaml
            interval: 86400
  
          tld-not-cn:
            type: http
            behavior: domain
            url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
            path: ./ruleset/tld-not-cn.yaml
            interval: 86400
  
          telegramcidr:
            type: http
            behavior: ipcidr
            url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
            path: ./ruleset/telegramcidr.yaml
            interval: 86400
  
          cncidr:
            type: http
            behavior: ipcidr
            url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
            path: ./ruleset/cncidr.yaml
            interval: 86400
  
          lancidr:
            type: http
            behavior: ipcidr
            url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
            path: ./ruleset/lancidr.yaml
            interval: 86400
  
          applications:
            type: http
            behavior: classical
            url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
            path: ./ruleset/applications.yaml
            interval: 86400
```
迁移到Merge如下
```
prepend-proxy-groups:
    - name: PROXY
        type: select
        proxies:
        - DIRECT
        - Proxy
prepend-rules:
    - PROCESS-NAME,Tailscale.exe,DIRECT
    - PROCESS-NAME,Tailscale Service.exe,DIRECT
    - PROCESS-NAME,tailscaled.exe,DIRECT
    - PROCESS-NAME,tailscale-ipn.exe,DIRECT
    - PROCESS-NAME,tor.exe,Proxy
    - PROCESS-NAME,lyrebird.exe,Proxy
    - RULE-SET,applications,DIRECT
    - DOMAIN,clash.razord.top,DIRECT
    - DOMAIN,yacd.haishan.me,DIRECT
    - RULE-SET,private,DIRECT
    - RULE-SET,reject,REJECT
    - RULE-SET,tld-not-cn,PROXY
    - RULE-SET,gfw,PROXY
    - RULE-SET,telegramcidr,PROXY
    - MATCH,DIRECT

prepend-rule-providers:
    reject:
        type: http
        behavior: domain
        url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
        path: ./ruleset/reject.yaml
        interval: 86400

    icloud:
        type: http
        behavior: domain
        url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
        path: ./ruleset/icloud.yaml
        interval: 86400

    apple:
        type: http
        behavior: domain
        url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
        path: ./ruleset/apple.yaml
        interval: 86400

    google:
        type: http
        behavior: domain
        url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
        path: ./ruleset/google.yaml
        interval: 86400

    proxy:
        type: http
        behavior: domain
        url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
        path: ./ruleset/proxy.yaml
        interval: 86400

    direct:
        type: http
        behavior: domain
        url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
        path: ./ruleset/direct.yaml
        interval: 86400

    private:
        type: http
        behavior: domain
        url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
        path: ./ruleset/private.yaml
        interval: 86400

    gfw:
        type: http
        behavior: domain
        url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
        path: ./ruleset/gfw.yaml
        interval: 86400

    tld-not-cn:
        type: http
        behavior: domain
        url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
        path: ./ruleset/tld-not-cn.yaml
        interval: 86400

    telegramcidr:
        type: http
        behavior: ipcidr
        url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
        path: ./ruleset/telegramcidr.yaml
        interval: 86400

    cncidr:
        type: http
        behavior: ipcidr
        url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
        path: ./ruleset/cncidr.yaml
        interval: 86400

    lancidr:
        type: http
        behavior: ipcidr
        url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
        path: ./ruleset/lancidr.yaml
        interval: 86400

    applications:
        type: http
        behavior: classical
        url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
        path: ./ruleset/applications.yaml
        interval: 86400


prepend-proxies:

prepend-proxy-providers:
```
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/54091889/8978828f-e0a4-4fe4-91a5-324b0210d522)
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/54091889/b9eabbce-b55d-4576-9d8b-73db0181f223)

保存后并启用日志无报错，刷新代理或重新激活当前配置rules中没有相应内容，没有相应PROXY代理组，provider也没有生效 日志没有相关配置操作
日志如下：

### 复现步骤 / To Reproduce

1、新建Merge填入 相关配置项保存 
2、刷新订阅 （或者重启应用）
3、无任何效果

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows 11 专业版 24H2 26100.1

### 日志 / Log

time="2024-04-09T11:14:26.2273424+08:00" level=info msg="Start initial configuration in progress"
time="2024-04-09T11:14:26.2293527+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-04-09T11:14:26.2293527+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-04-09T11:14:26.2338758+08:00" level=info msg="Start initial GeoIP rule cn => Domestic, records: 7435"
time="2024-04-09T11:14:26.2513587+08:00" level=info msg="Initial configuration complete, total time: 24ms"
time="2024-04-09T11:14:26.2518606+08:00" level=info msg="Sniffer is loaded and working"
time="2024-04-09T11:14:26.2518606+08:00" level=info msg="Use tcp concurrent"
time="2024-04-09T11:14:26.3226011+08:00" level=info msg="Start initial Compatible provider Proxy"
time="2024-04-09T11:14:26.3236055+08:00" level=info msg="Start initial Compatible provider Domestic"
time="2024-04-09T11:14:26.3236055+08:00" level=info msg="Start initial Compatible provider GlobalTV"
time="2024-04-09T11:14:26.3236055+08:00" level=info msg="Start initial Compatible provider Others"
time="2024-04-09T11:14:26.3236055+08:00" level=info msg="Start initial Compatible provider AsianTV"
time="2024-04-09T11:14:26.3236055+08:00" level=info msg="Start initial Compatible provider default"
time="2024-04-09T11:14:29.4510313+08:00" level=info msg="[TCP] 127.0.0.1:29426 --> www.gaomon.net:443 match Match using Others[台湾-标准-03]"

**Comment by dongchengjie** [comment]
被merge的配置中必须存在`Proxy`，你下面的配置里用到了，否则无法激活
配置是好使的，就是你写错了，改好了你自己检查去吧
<img width="656" alt="无标题" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/e03d2dde-d015-4ea0-8151-9b32405f5842">
<img width="518" alt="无标题2" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/9f3fea7b-a9e1-4589-aa41-724cf9803336">
<img width="569" alt="无标题22" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/60cf2b00-8bca-4a61-9bd1-07260a1dfd6f">

```
# 假装我有Proxy这个代理，使用prepend-proxies插入一个
prepend-proxies:
  - name: "Proxy"
    type: ss
    server: server
    port: 443
    cipher: aes-128-gcm
    password: "password"
    udp: true
    udp-over-tcp: false
    udp-over-tcp-version: 2
    ip-version: ipv4
    plugin: obfs
    plugin-opts:
      mode: tls
    smux:
      enabled: false

prepend-proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - DIRECT
      - Proxy

prepend-rules:
  - PROCESS-NAME,Tailscale.exe,DIRECT
  - PROCESS-NAME,Tailscale Service.exe,DIRECT
  - PROCESS-NAME,tailscaled.exe,DIRECT
  - PROCESS-NAME,tailscale-ipn.exe,DIRECT
  - PROCESS-NAME,tor.exe,Proxy
  - PROCESS-NAME,lyrebird.exe,Proxy
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,tld-not-cn,PROXY
  - RULE-SET,gfw,PROXY
  - RULE-SET,telegramcidr,PROXY
  - MATCH,DIRECT

prepend-rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400




prepend-proxy-providers:
```

**Comment by cstcood** [comment]
不是 这个问题  我的机场订阅会在更新时候配置自带 Proxy。即使我用你的方案添一个prepend-proxies叫Proxy 也无效，在Parses使用这个配置是没有问题的
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/54091889/198e02f7-202c-46f1-816f-f6b8663df001)

**Comment by abrclano** [comment]
@cstcood  CFW的Parses是匹配了机场订阅链接的，所以可以抓到机场的Proxy，但是Verge的Merge并不会匹配机场订阅链接的，只会覆盖相同字段的配置，所以不能把机场的Proxy添加到你的配置中，要在Verge实现类似Parses的功能目前只能用Script

**Comment by dongchengjie** [comment]
@cstcood 你的层级关系写错了，我发你回复的是纠正过了的。这么长不你可能手打发出来的，肯定是粘贴进评论里的，说明你配置里也差错了
<img width="730" alt="无标题" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/6f9d91cc-41b1-408c-86a8-04e70f53dd76">


@abrclano Verge可以得到订阅中的节点
```
prepend-rules:
  - PROCESS-NAME,Tailscale.exe,自动选择
  - PROCESS-NAME,Tailscale.exe,🇺🇸美国 01-中转
```
<img width="605" alt="无标题" src="https://github.com/clash-verge-rev/clash-verge-rev/assets/37543964/ae880725-8713-462d-86ff-70fff3bb00ab">

**Comment by z1298808165** [comment]
@dongchengjie 大佬您好，可以帮我看下这个配置问题吗

```
# Merge Template for clash verge
# The `Merge` format used to enhance profile

prepend-rules:

prepend-proxies:

prepend-proxy-groups:

append-rules:

append-proxies:

append-proxy-groups:

rule-providers:
  direct:
    type: http
    behavior: domain
    # url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt
    path: ./ruleset/direct.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    # url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt
    path: ./ruleset/proxy.yaml
    interval: 86400
  reject:
    type: http
    behavior: domain
    # url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt
    path: ./ruleset/reject.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    # url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt
    path: ./ruleset/private.yaml
    interval: 86400
  apple_china:
    type: http
    behavior: domain
    # url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt
    path: ./ruleset/apple_china.yaml
    interval: 86400
  icloud:
    type: http
    behavior: domain
    # url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt
    path: ./ruleset/icloud.yaml
    interval: 86400
  google_accessible_in_china_but_not_recommended:
    type: http
    behavior: domain
    # url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/google.txt
    path: ./ruleset/google.yaml
    interval: 86400
  gfwlist:
    type: http
    behavior: domain
    # url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt
    path: ./ruleset/gfw.yaml
    interval: 86400
  greatfire:
    type: http
    behavior: domain
    # url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/greatfire.txt
    path: ./ruleset/greatfire.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    # url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    # url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    # url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt
    path: ./ruleset/lancidr.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    # url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt
    path: ./ruleset/cncidr.yaml
    interval: 86400
  apps:
    type: http
    behavior: classical
    # url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt
    path: ./ruleset/apps.yaml
    interval: 86400
  custom_direct:
    type: http
    behavior: classical
    # url: https://cdn.jsdelivr.net/gh/mo-han/mo-han-toolbox/etc/clash/custom_direct.yaml
    url: https://github.com/mo-han/mo-han-toolbox/raw/master/etc/clash/custom_direct.yaml
    path: ./ruleset/custom_direct.yaml
    interval: 3600
  custom_proxy:
    type: http
    behavior: classical
    # url: https://cdn.jsdelivr.net/gh/mo-han/mo-han-toolbox/etc/clash/custom_proxy.yaml
    url: https://github.com/mo-han/mo-han-toolbox/raw/master/etc/clash/custom_proxy.yaml
    path: ./ruleset/custom_proxy.yaml
    interval: 3600

rules:
  - RULE-SET,custom_proxy,PROXY
  - RULE-SET,custom_direct,DIRECT

  - RULE-SET,apps,DIRECT
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,reject,REJECT

  - RULE-SET,telegramcidr,PROXY
  - RULE-SET,tld-not-cn,PROXY
  - RULE-SET,gfwlist,PROXY
  - RULE-SET,greatfire,PROXY
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple_china,DIRECT

  - MATCH,PROXY

payload:
  - DOMAIN-SUFFIX,hath.network
  - DOMAIN-SUFFIX,mozilla.org
  - DOMAIN-SUFFIX,mozilla.com
  - DOMAIN-SUFFIX,firefox.com
  - DOMAIN-SUFFIX,outlook.com
  - DOMAIN-SUFFIX,steamcontent.com
  - DOMAIN-SUFFIX,vip.ffzy-play5.com
  - DOMAIN-SUFFIX,microsoft.com
  - DOMAIN-SUFFIX,googleads.g.doubleclick.net
  - DOMAIN-SUFFIX,lan
  - DOMAIN-SUFFIX,local

payload:
  - DOMAIN-SUFFIX,googleapis.cn
  - DOMAIN,gotbjbqvnxfkunugorzh.hath.network
  - DOMAIN,zeymhthzcuckefofbybo.hath.network
  - DOMAIN,dmpjnjw.ebphzvhpitfz.hath.network
  - DOMAIN,blwmstv.cpsfrwilqxia.hath.network
  - DOMAIN,btvspwxjexslwpogkyow.hath.network
  - DOMAIN,nwhhvsf.kjobljmxcfea.hath.network
  - DOMAIN,fxopenxszvjxrjfmhydh.hath.network
  - DOMAIN,jefjvvteivphwynrgjdm.hath.network
  - DOMAIN,cyecnzy.xewhfgjjwmuk.hath.network
  - DOMAIN,tmnuvdp.rbmhbefkgqxb.hath.network
  - DOMAIN,hacaqjfrpvthigkeomjq.hath.network
  - DOMAIN,aghqvlkgagdqbynuiyxk.hath.network
  - DOMAIN,dchknpt.zjbztkbyvewq.hath.network
  - DOMAIN,oxrrlaw.toylmckzfddk.hath.network
  - DOMAIN,didxrwa.cpsfrwilqxia.hath.network
  - DOMAIN,ykofnavysaepqurqrbmv.hath.network
  - DOMAIN,jbgbvnr.cpsfrwilqxia.hath.network
  - DOMAIN,kjranpf.sxvbbeecdlmd.hath.network
  - DOMAIN,tkuwrig.fzcdxfolbeqd.hath.network
  - DOMAIN,xmroucd.qkugestqvlju.hath.network
  - DOMAIN,dfpnexq.mvvgnqzwzmow.hath.network
  - DOMAIN,lwujxhaydlqtdzxawoti.hath.network
  - DOMAIN,ykxmgel.ldlvzhfekbus.hath.network
  - DOMAIN,tvlvcus.xubqsectroza.hath.network
  - DOMAIN,wqmhjot.kjobljmxcfea.hath.network
  - DOMAIN,btvspwxjexslwpogkyow.hath.network
  - DOMAIN,ubwpvdm.qgankvrkxxiw.hath.network
  - DOMAIN,rsdalkf.qgankvrkxxiw.hath.network
  - DOMAIN,shioxowwjqzzmcmcjtcc.hath.network
  - DOMAIN,wodmrfmkcovmstjztpdj.hath.network
  - DOMAIN,jihcohulqbwpetewyuia.hath.network
  - DOMAIN,asmrsqqftvbbqqaocggo.hath.network
  - DOMAIN,ewroamb.szngzsqnwfyn.hath.network
  - DOMAIN,gtrpuajiiohkkutplhus.hath.network
  - DOMAIN,kkkjddn.ybfqhpyacupb.hath.network
  - DOMAIN,lkdjvpi.rogbtqungzkk.hath.network
  - DOMAIN,pqbjqft.rogbtqungzkk.hath.network
  - DOMAIN,uuspwui.wrbrjtjhnvkp.hath.network
  - DOMAIN,ziwgdfwwictwelwogupv.hath.network
```



```
const test_url = "http://www.gstatic.com/generate_204";
const proxy_groups_key = "proxy-groups";
const interval = 60;
const tolerance = 150;
const proxy_providers_key = "proxy-providers";
const proxies_key = "proxies";
function main(config) {
  if (!(proxy_groups_key in config)) {
    config[proxy_groups_key] = [];
  }
  config[proxy_groups_key] = [
    {
      name: "PROXY",
      type: "select",
      proxies: ["SELECT", "URL-TEST", "FALLBACK", "DIRECT"],
    },
    { name: "SELECT", type: "select", use: [], proxies: [] },
    {
      name: "URL-TEST",
      type: "url-test",
      url: test_url,
      interval: interval,
      tolerance: tolerance,
      use: [],
      proxies: [],
    },
    {
      name: "FALLBACK",
      type: "fallback",
      url: test_url,
      interval: interval,
      use: [],
      proxies: [],
    },
  ];
  config[proxy_groups_key]
    .filter((group) => group.name !== "PROXY")
    .forEach((group) => {
      if (proxy_providers_key in config) {
        Object.keys(config[proxy_providers_key]).forEach((provider_name) => {
          group.use.push(provider_name);
        });
      }
      if (proxies_key in config) {
        config[proxies_key].forEach((proxy) => {
          group.proxies.push(proxy.name);
        });
      }
    });
  return config;
}
```

这个配置是另一位大佬写的，但是我在实际使用的时候却会报错
```
rules[1] [DOMAIN-SUFFIX,acl4.ssr,🎯 全球直连] error: proxy [🎯 全球直连] not found
```

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/25720725/54ff0ab6-075b-4e76-898b-55533c59d05b)

地址：https://github.com/mo-han/mo-han-toolbox/tree/master/etc/clash
