### ISSUE TITLE
[请教] proxies中，手动添加节点不识别。

### ISSUE THREAD

**Issue by Troray** [clash-verge-rev/clash-verge-rev#863]
### 问题描述 / Describe the bug

v1.5.3和v1.5.11
proxies中，手动添加节点不识别。
**请教一下我是缺少了哪些地方没配置，还是哪里配置错了？**

```
port、dns等等省略
c: &c {type: http, behavior: classical, interval: 86400}
d: &d {type: http, behavior: domain, interval: 86400}
i: &i {type: http, behavior: ipcidr, interval: 86400}
g: &g {type: select, proxies: [Proxy, Auto, Fallback, HongKong, Korea, TaiWan, Singapore, Japan, America, Others, DIRECT]}
p: &p {type: http, interval: 86400, benchmark-timeout: 5, health-check: {enable: true, url: http://www.apple.com/library/test/success.html, interval: 600}}
u: &u {type: select, use: [Subscribe]}
######### 锚点 end #########
# 本地服务器
proxies:
- name: "🇰🇷 韩国"
  type: vmess
  server: mydomain.com
  port: 443
  udp: true
  uuid: 1xxxxxx1-11xx1-11xxx11-b1xxx7-fxxxxxxx6
  alterId: 0
  cipher: auto
  tls: true
  client-fingerprint: chrome
  skip-cert-verify: true
  ws-opts:
    path: /1xxxxxx1-11xx1-11xxx11-b1xxx7-fxxxxxxx6
    headers: 
      Host: 
        mydomain.com
  network: ws

# 远程订阅
proxy-providers: 
  Subscribe: {<<: *p, path: ./proxy_providers/test.yaml, url: "https://myclash.config.com.yaml"}
proxy-groups: 
#省略
- {name: Korea, icon: https://icon...../Korea.png, <<: *u, filter: "韩|韩国|🇰🇷|kr|KR|(?i)Korea"}
#省略

```
大致配置如上，也试过把clash.wiki中的示例配置原封不动复制进去(只修改name),同样识别不到节点。
结果类似下图(图片P过)
![Clash_Verge_GHO68bULhu](https://github.com/clash-verge-rev/clash-verge-rev/assets/16841721/b888b4ea-0a3e-400a-9c92-0d798b0e649f)

节点是自建xui，vmess，通过subconverter转换为clash订阅来的。通过subconverter转换后直接导入clash是可正常使用的。这里各个字段的配置信息都是按照subconverter转换后来填写的。

### 复现步骤 / To Reproduce

-

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

win11

### 日志 / Log

-
