### ISSUE TITLE
[BUG] ArchLinux开启tun模式后网络连接受限

### ISSUE THREAD

**Issue by witt-bit** [clash-verge-rev/clash-verge-rev#925]
### 问题描述 / Describe the bug

操作系统
```shell
❯ screenfetch

 ██████████████████  ████████     witt@witt-SwiftHealth-Manjaro
 ██████████████████  ████████     OS: Manjaro 23.1.4 Vulcan
 ██████████████████  ████████     Kernel: x86_64 Linux 6.6.26-1-MANJARO
 ██████████████████  ████████     Uptime: 5h 1m
 ████████            ████████     Packages: 1460
 ████████  ████████  ████████     Shell: zsh 5.9
 ████████  ████████  ████████     Resolution: 3840x1080
 ████████  ████████  ████████     DE: KDE 5.115.0 / Plasma 5.27.11
 ████████  ████████  ████████     WM: KWin
 ████████  ████████  ████████     GTK Theme: WhiteSur-Dark-nord [GTK2/3]
 ████████  ████████  ████████     Icon Theme: Tela-black-dark
 ████████  ████████  ████████     Disk: 347G / 1.2T (32%)
 ████████  ████████  ████████     CPU: Intel Core i7-10700 @ 16x 4.8GHz [68.0°C]
 ████████  ████████  ████████     GPU: Mesa Intel(R) UHD Graphics 630 (CML GT2)
                                  RAM: 19500MiB / 23779MiB
    /tmp 
```

相关版本:
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/52407727/7c9f3f68-1405-4a86-bcba-3aa552373e0f)

通过排除法发现，开启TUN模式后，托盘内的网络图标显示网络受限，关闭就好了，在网上查找解决方案，留意到
https://bbs.archlinuxcn.org/viewtopic.php?id=13329

通过开关TUN模式，尝试`ping ping.archlinux.org`和浏览器访问`ping.archlinux.org`跟踪clash日志，发现确实是代理导致

所以我添加了Merge的配置文件，启用以下内容
```yaml
# Merge Template for clash verge
# The `Merge` format used to enhance profile

prepend-rules: [
  'DOMAIN,ping.archlinux.org,DIRECT'
]

prepend-rule-providers: {}

prepend-proxies: []

prepend-proxy-providers: {}

prepend-proxy-groups: []

append-rules: []

append-rule-providers: {}

append-proxies: []

append-proxy-providers: {}

append-proxy-groups: []

```

再次跟踪日志，确认不走代理
```log
04-24 17:34:29INFO
[TCP] 198.18.0.1:50062 --> ping.archlinux.org:443 match Domain(ping.archlinux.org) using DIRECT
```

但是`ping.archlinux.org`仍然不通，是否还需要额外的配置

### 复现步骤 / To Reproduce

Arch Linux打开TUN模式

### 操作系统 / OS

Linux

### 操作系统版本 / OS Version

Manjaro 23.1.4 Vulcan

### 日志 / Log

04-24 17:34:29INFO
[TCP] 198.18.0.1:50062 --> ping.archlinux.org:443 match Domain(ping.archlinux.org) using DIRECT

**Comment by xishang0128** [comment]
@witt-bit 1,manjaro不算archlinux
2,这是networkmanager的问题,修改测试链接或者禁用测试
https://wiki.archlinux.org/title/NetworkManager#Checking_connectivity

**Comment by witt-bit** [comment]
> @witt-bit 1,manjaro不算archlinux 2,这是networkmanager的问题,修改测试链接或者禁用测试 https://wiki.archlinux.org/title/NetworkManager#Checking_connectivity

我在订阅配置中添加`fake-ip-filter: ['ping.archlinux.org']`可以ping通

找到https://github.com/clash-verge-rev/clash-verge-rev/issues/143，我想在Merge操作里完成，看到这么一句话

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/52407727/afefffa1-a771-44d3-9738-688cd779416d)


未找到该设置项

**Comment by dongchengjie** [comment]
这个我记得在[v1.5.0](https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v1.5.0)移除了吧
现在直接在merge里写需要额外merge的字段就好了

**Comment by witt-bit** [comment]
> 这个我记得在[v1.5.0](https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v1.5.0)移除了吧 现在直接在merge里写需要额外merge的字段就好了

感谢作者


参考 https://docs.gtk.pw/contents/parser.html#commands-%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95-beta

已经实现
```yaml
# Merge Template for clash verge
# The `Merge` format used to enhance profile
dns:
  fake-ip-filter:
    - ping.archlinux.org


prepend-rules: []

prepend-rule-providers: {}

prepend-proxies: []

prepend-proxy-providers: {}

prepend-proxy-groups: []

append-rules: []

append-rule-providers: {}

append-proxies: []

append-proxy-providers: {}

append-proxy-groups: []

```


如果支持这个操作，可能拓展型更强

![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/52407727/27867c66-3c1b-4318-923e-f35e4f587dd6)
