### ISSUE TITLE
[技术咨询] TUN 模式无法开启，提示 The property set specified does not exist on the object

### ISSUE THREAD

**Issue by xiaoQQya** [clash-verge-rev/clash-verge-rev#953]
### 问题描述 / Describe the bug

Windows11 系统下，正常安装服务模式且打开，开启 TUN 模式失败，服务日志显示 `The property set specified does not exist on the object` 。

我知道该问题或许不是由于 Clash Verge 原因导致的，不过本人实在没有头绪，希望各位大佬能够提供一些解决思路。

### 复现步骤 / To Reproduce

1. 安装 Clash Verge rev 1.6.0 版本；
2. 安装服务模式；
3. 打开服务模式；
4. 开启 TUN 模式，开启失败导致自动关闭；
5. 查看 service 日志，显示 `The property set specified does not exist on the object` ；

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

Windows11 专业版 22631.3527

### 日志 / Log

```
time="2024-04-30T09:36:30.8240064+08:00" level=warning msg="[TUN] default interface changed by monitor,  => 以太网"
time="2024-04-30T09:36:46.0666528+08:00" level=warning msg="Start Tun interface timeout: The property set specified does not exist on the object. [retrying 1/3]"
time="2024-04-30T09:37:01.2142702+08:00" level=warning msg="Start Tun interface timeout: The property set specified does not exist on the object. [retrying 2/3]"
time="2024-04-30T09:37:16.346221+08:00" level=warning msg="Start Tun interface timeout: The property set specified does not exist on the object. [retrying 3/3]"
time="2024-04-30T09:37:16.347295+08:00" level=error msg="Start TUN listening error: configure tun interface: The property set specified does not exist on the object."
```

**Comment by Lsyx-Good** [comment]
在启动tun模式的时候，在设置查看当前配置看生成的配置文件中关于tun的配置是否正确

**Comment by xiaoQQya** [comment]
> 在启动tun模式的时候，在设置查看当前配置看生成的配置文件中关于tun的配置是否正确

```
dns:
  enable: true
  listen: 127.0.0.1:35353
  ipv6: true
  default-nameserver:
  - 180.76.76.76
  - 182.254.118.118
  - 223.5.5.5
  - 114.114.114.114
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - stun.*.*.*
  - stun.*.*
  - time.windows.com
  - time.nist.gov
  - time.apple.com
  - time.asia.apple.com
  - '*.ntp.org.cn'
  - '*.openwrt.pool.ntp.org'
  - time1.cloud.tencent.com
  - time.ustc.edu.cn
  - pool.ntp.org
  - ntp.ubuntu.com
  - ntp.aliyun.com
  - ntp1.aliyun.com
  - ntp2.aliyun.com
  - ntp3.aliyun.com
  - ntp4.aliyun.com
  - ntp5.aliyun.com
  - ntp6.aliyun.com
  - ntp7.aliyun.com
  - time1.aliyun.com
  - time2.aliyun.com
  - time3.aliyun.com
  - time4.aliyun.com
  - time5.aliyun.com
  - time6.aliyun.com
  - time7.aliyun.com
  - '*.time.edu.cn'
  - time1.apple.com
  - time2.apple.com
  - time3.apple.com
  - time4.apple.com
  - time5.apple.com
  - time6.apple.com
  - time7.apple.com
  - time1.google.com
  - time2.google.com
  - time3.google.com
  - time4.google.com
  - music.163.com
  - '*.music.163.com'
  - '*.126.net'
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - '*.kuwo.cn'
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - '*.y.qq.com'
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - '*.xiami.com'
  - '*.music.migu.cn'
  - music.migu.cn
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - localhost.ptlogin2.qq.com
  - '*.*.*.srv.nintendo.net'
  - '*.*.stun.playstation.net'
  - xbox.*.*.microsoft.com
  - '*.ipv6.microsoft.com'
  - '*.*.xboxlive.com'
  - speedtest.cros.wr.pvp.net
  nameserver:
  - 223.6.6.6
  - 180.76.76.76
  - https://223.6.6.6/dns-query
  - https://dns.rubyfish.cn/dns-query
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - 119.28.28.28
  - 114.114.115.115
  - https://dns.rubyfish.cn/dns-query
  - tls://8.8.4.4
  - tls://1.0.0.1:853
  - https://cloudflare-dns.com/dns-query
  - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
    - 127.0.0.1/32
    domain:
    - +.google.com
    - +.facebook.com
    - +.twitter.com
    - +.youtube.com
    - +.xn--ngstr-lra8j.com
    - +.google.cn
    - +.googleapis.cn
    - +.googleapis.com
    - +.gvt1.com
 ```

**Comment by xiaoQQya** [comment]
> 在启动tun模式的时候，在设置查看当前配置看生成的配置文件中关于tun的配置是否正确

不好意思，刚才复制错了

```
tun:
  mtu: 9000
  stack: gvisor
  device: Meta
  auto-route: true
  strict-route: false
  auto-detect-interface: true
  dns-hijack:
  - any:53
  enable: true
```
